### ISSUE TITLE
Improve README to explain that alpakka is a community driven effort

### ISSUE THREAD

**Issue by ktoso** [akka/alpakka#100]
Improve README to explain that alpakka is a community driven effort.
We should be clear about "if you contribute, it would be nice you'd maintain it as well" etc

**Comment by viktorklang** [comment]
Perhaps word it as: Alpakka does not have contributors, it only has maintainers—frequent and infrequent—but everyone helps out. Alpakka loves new maintainers as well as old maintainers. :)

**Comment by ktoso** [comment]
That is very cool wording actually :-) 👍
