### ISSUE TITLE
AWS S3: Implement "proper" proxy support

### ISSUE THREAD

**Issue by Scalahansolo** [akka/alpakka#1017]
Way back when, with the help of the community I implemented the initial (less than ideal) version of proxy support in the S3 module in alpakka. Now that akka-http supports proxy support, as well as authed proxy support I think that we should look into upgrading alpakka to use the authed proxy support. 

I could take a crack at an initial re-work, but based on how many of the tests ended up getting implemented, its going to be a fairly significant re-write of tests as well as the actual S3Stream/HttpRequests codebase.

Wanted to reach out and see if anyone was interested in working with me with this work?

**Comment by ennru** [comment]
We'll upgrade to use Akka Http 10.1.2 with #970 

cc @sfali

**Comment by Scalahansolo** [comment]
I was just now looking back on this ticket to go back through and re work this. I would like to take some time to work on this as I really think this is a better way forward. However, like my comment back in June, this change is going to non-backwards compatible and involve a fairly significant re work in the tests. Before I embark down that path, is this something that would be wanted? @ennru?

**Comment by 2m** [comment]
We are currently working towards Alpakka 1.0 after which we will keep API compatibility between major versions. So now is a good time to work on API braking changes.

**Comment by Scalahansolo** [comment]
Is there any timeline for 1.0? So I have a rough idea how much time I have to get these changes done?

**Comment by floekke** [comment]
Any news about this issue?

**Comment by ennru** [comment]
Fixed with #1639
