### ISSUE TITLE
AMQP: Support auto-recovery

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1034]
The RabbitMQ client library supports adding recovery listeners that can support recovery from broker or connection failures.
@JonathanKnight tried to use this in #332 but seems to have abandoned the PR.

**Comment by adamtrousdale** [comment]
Hi @ennru, I might be misunderstanding/simplifying but it seems this is now enabled by default when using v4.0.0+ of amqp-client? https://www.rabbitmq.com/api-guide.html#recovery

**Comment by juanjoDiaz** [comment]
Yes and not 🙂

The updated happened on #656. However, even though RabbitMQ enables autorecovery automatically. We disable it explicitly on https://github.com/akka/alpakka/blob/master/amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala#L63

I wonder if it makes sense to add autorecovery properly or if we should simply disable it and the user can use `RestartXXX.withBackoff` for recovery.

**Comment by drobert** [comment]
Perhaps I'm misreading, but how does the current code disable this feature explicitly. Rather than defaulting to `Some(false)` the default is `None`, which should bypass the `.foreach` and leave the underlying client with its default configuration, which is to allow for automatic recovery.

**Comment by juanjoDiaz** [comment]
🤦‍♂️ You are right. It should be `Some(false)` to be disabled...

And most likely, it's producing the issue that you mention which sounds like #1270

We should at least add a test to prove this though, instead of simply setting it to `Some(false)` and hope for the best...
