### ISSUE TITLE
`keepAliveInterval` and `connectionTimeout` of MqttConnectionSettings ?

### ISSUE THREAD

**Issue by OutOfBedlam** [akka/alpakka#1042]
I don't know if it is intended.

`MqttConnectionSettings` constructor's parameters. among them these two have default values

- `keepAliveInterval: FiniteDuration = 60.seconds`
- `connectionTimeout: FiniteDuration = 30.seconds`

and when I tried to change keepAliveInterval with `withKeepAliveInterval` method, it doesn't work, there is mis-mappings with variable name and method. 

both of methods change the same parameter `connectionTimeout`. 

```scala
  def withKeepAliveInterval(connectionTimeout: Int, unit: TimeUnit): MqttConnectionSettings =
    copy(connectionTimeout = FiniteDuration(connectionTimeout, unit))

  def withConnectionTimeout(connectionTimeout: Int, unit: TimeUnit): MqttConnectionSettings =
    copy(connectionTimeout = FiniteDuration(connectionTimeout, unit))
```

**Comment by ennru** [comment]
Thanks for reporting.
It is fixed in the source already.
If you're in urgent need of a fix, try a [snapshot version](https://developer.lightbend.com/docs/alpakka/current/other-docs/snapshots.html).
