### ISSUE TITLE
FileTailSource

### ISSUE THREAD

**Issue by patriknw** [akka/alpakka#11]
Move from https://github.com/akka/akka-stream-contrib/tree/master/contrib/src/main/java/akka/stream/contrib

**Comment by patriknw** [comment]
@johanandren perhaps something you would like to pick up
I think we should have an alpakka-file module.

**Comment by johanandren** [comment]
Both that one and the DirectoryChanges then I guess?

**Comment by johanandren** [comment]
Yeap. I can create such a module and move these two.
