### ISSUE TITLE
S3Client is final and not testable

### ISSUE THREAD

**Issue by gleeb** [akka/alpakka#1127]
Hi, 
I do not see any real reason why the S3Client needs to be final and not mockable.

Can you please remove the useless modifier?

Thanks

**Comment by huntc** [comment]
`final` modifiers are used to explicitly declare that a class is not designed for subclassing. This reduces support implications.

Given something like:

```
val (s3Source: Source[ByteString, _], _) = s3Client.download(bucket, bucketKey)
```

You don't have to mock this. Instead, you can create your own `Source[ByteString, NotUsed]`.

Does this help?

**Comment by gleeb** [comment]
This means that I need to encapsulate the client in order to use it and test it. that's what I did.

Can't argue with the reduce support implications.

**Comment by huntc** [comment]
Could you please outline your goals and perhaps provide a sample? Thanks.

**Comment by kafis** [comment]
Hey, I also stumbled over this limitation and had to wrap my s3Client one more time to test my cases.
[Here is a very simple gist](https://gist.github.com/kafis/10f645d05fd1afa4b8aca26a45334b14) that roughly showed my intentions and why I would also have enjoyed the client to be non final.
 I am not sure about the support implications, as the library is provided as is, and if someone likes to mess around with it in his code, it would be his/hers responsibillity to keep his/her hack alive.

**Comment by ennru** [comment]
This should be considered when working with #1086

**Comment by ennru** [comment]
BTW The `S3Client` is no more since quite a while back.
