### ISSUE TITLE
JmsProducerStage is single-session only (fix available)

### ISSUE THREAD

**Issue by andreas-schroeder** [akka/alpakka#1144]
Currently, the JmsProducerStage offers limited throughput only, as it uses a single Jms session only. Thankfully, https://github.com/akka/alpakka/blob/master/jms/src/main/scala/akka/stream/alpakka/jms/JmsProducerStage.scala#L40 indicates very honestly that there is still work to be done.

I've prepared a branch in my fork that I could contribute back to fix this issue: https://github.com/akka/alpakka/compare/master...andreas-schroeder:jms-producer-multi-session
This solution is heavily inspired by Akka Stream's wonderful MapAsyc stage.

Would this be a worthwhile contribution? If so, I would take care of going through the process of contributing, and make this ready for PR.

**Comment by ennru** [comment]
Yes, a contribution would be highly appreciated.

**Comment by andreas-schroeder** [comment]
Hi @ennru,

I'm glad to hear that. For properly preparing my PR, I have three questions:

1.  should the 1-session-case use a separate graph stage logic than the n-session case (as I did implement it)?
2. is it okay to introduce a Mockito-dependency for testing the asynchronous behavior?
3. which additional tests would you like to have for the n-session behavior? Currently, I have created one test that checks that the JmsProducerStage produces the elements in the proper order.
