### ISSUE TITLE
Elasticsearch: Need a way to add extra metadata field to insert

### ISSUE THREAD

**Issue by johanandren** [akka/alpakka#1159]
Use case: we need to specify an ES `pipeline` for ES side postprocessing of bulk inserts (and possibly other ones as well). `pipeline` can also be specified as a query parameter but I think making it possible to pass per payload/message.

Proposed solution, allow for specifying arbitrary metadata in the `IncomingMessage` that will be appended to the JSON. Something like `IncomingMessage.withCustomMetadata(Map[String, String])`.

WDYT?

**Comment by 2m** [comment]
Fixed in #1161
