### ISSUE TITLE
Alpakka doesn't compile under JDK 10

### ISSUE THREAD

**Issue by LarsWestergren** [akka/alpakka#1169]
There are new methods added in Java that conflict with existing imports.

[error] /home/larsw/projects/alpakka/text/src/main/scala/akka/stream/alpakka/text/impl/CharsetLogic.scala:124:60: ambiguous reference to overloaded definition,
[error] both method position in class CharBuffer of type (x$1: Int)java.nio.CharBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]     if (count > 0) push(out, new String(chars.array, chars.position, count))
[error]  

...

[error] /home/larsw/projects/alpakka/kinesis/src/main/scala/akka/stream/alpakka/kinesis/scaladsl/KinesisFlow.scala:55:75: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]     case (request, _) => request.getPartitionKey.length + request.getData.position
[error]

**Comment by ennru** [comment]
For now, we focus on Java's long term supported versions, which is JDK 8 right now.
We'd welcome PRs to fix this, though. ;-)
