### ISSUE TITLE
Doc: GitHub links are not working

### ISSUE THREAD

**Issue by dheerajk** [akka/alpakka#1171]
I am referring following documentation link for Alpakka Apache Cassandra
[Apache Cassandra](https://developer.lightbend.com/docs/alpakka/current/cassandra.html)
It seems like links for [Full source at GitHub](https://github.com/akka/alpakka/tree/master/cassandra/src/test/scala/akka/stream/alpakka/cassandra/scaladsl/CassandraSourceSpec.scala#L41-L45) isn't working.

**Comment by ennru** [comment]
These files have moved and that version of the doc-generator did not issue stable paths (it is fixed there now, but no new docs are released).
See https://github.com/akka/alpakka/blob/master/cassandra/src/test/scala/docs/scaladsl/CassandraSourceSpec.scala#L41-L45 instead.

**Comment by ennru** [comment]
This should now work again.
https://developer.lightbend.com/docs/alpakka/1.0-M1/
