### ISSUE TITLE
Amazon SQS delete msg Flow/Sink

### ISSUE THREAD

**Issue by aserrallerios** [akka/alpakka#118]
I'm wondering if it would be useful for the community to provide a SQS Sink that deletes the messages from the remote queue. As you know, the current SQS Source implementation does not remove messages from the queue, so it must be handled manually.

What I propose is to have a `Sink[com.amazonaws.services.sqs.model.Message, _]` to easily get *at-least-once* semantics on your code:

```
sqsSource.map(x => yourLogic(x.getBody); x).to(sqsDeleteSink)
```

In addition to this, we can also provide a `Flow[com.amazonaws.services.sqs.model.Message, T, _]` to get *at-most-once* semantics:

```
sqsSource.via(sqsDeleteFlow(x => x.getBody)).map(yourLogic).to(ignoreSink)
```

**Comment by s12v** [comment]
+1

I have implemented something similar here: https://github.com/s12v/akka-stream-sqs/blob/master/src/main/scala/me/snov/akka/sqs/shape/SqsAckSinkShape.scala

Also it would be nice to have SqsSink producing SQS messages: https://github.com/s12v/akka-stream-sqs/blob/master/src/main/scala/me/snov/akka/sqs/shape/SqsPublishSinkShape.scala

I can port my code to alpakka

**Comment by dpfeiffer** [comment]
@s12v I just stumbled upon your repo. If you like I can help you porting your code to alpakka.

**Comment by s12v** [comment]
@dpfeiffer, thanks! I'll try to create a PR this weekend
