### ISSUE TITLE
JMS: Should have commit/rollback timeout for transactional consumer

### ISSUE THREAD

**Issue by akara** [akka/alpakka#1188]
The stream gets stuck if message processing fails, whether this is due to application code, recovery by the stream decider, etc. A failure to commit/rollback must not get the stream stuck. The message failing to signal back should be rolled back automatically after timeout.

**Comment by ennru** [comment]
Looking at https://github.com/akka/alpakka/pull/1831 shows this has been available for quite a while now.
Closing.
