### ISSUE TITLE
AWS SQS Connector inverts the order of messages while consuming FIFO queues

### ISSUE THREAD

**Issue by nebtrx** [akka/alpakka#1209]
Hey, 

First, I want to congratulate you guys for the hard work on this. Having said that, I want to report an issue with the AWS SQS Connector while consumig messages from FIFO queues. It basically inverts the order of the produced messages while streaming those. 

At the beginning, we(me and the team and currently working with) thought we were doing something wrong for a while, but then I joked about the posibility of a missplaced `reverse` and .. turns out I think I've found it [here](https://github.com/akka/alpakka/blob/b20c7b39dd76ed0a47153bed970f2900c24d16bd/sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceStage.scala#L78)

So, I'm not sure about the purpose of that `reverse` there but, we quickly tested a local fix removing the `reverse` and it worked like a charm. 

Aside from that, we stumble upon [a discussion thread](http://akka-user.narkive.com/ja82ok7a/alpakka-aws-sqs-connector-with-fifo-queue), asking about the same issue two years ago. Reproducible code snippets, from that discussion thread, can be found [here](https://github.com/hideto0710/alpakka-sqs-sample/blob/master/src/main/scala/com/github/hideto0710/samples/AlpakkaSQSSample.scala)

All in all, let me know if the nature of what I've described here is actually buggy, which I'm 99.99% sure,  and I'll be glad to push a PR fixing it.

BTW, I'm _ccing_ the author of the discussion thread, @hideto0710. I think he'll be happy to know someone else had the same issue 😁

**Comment by ennru** [comment]
Thank you for reporting. Funny that so few complain about it...
Please go ahead and open a PR.

**Comment by nebtrx** [comment]
Cool!
