### ISSUE TITLE
Add Amazon Kinesis Firehose support

### ISSUE THREAD

**Issue by devsprint** [akka/alpakka#122]
Integrate Amazon Kinesis Firehose such that data from streams can be pushed to S3/Redshift to be used for analytic processes.

**Comment by utgarda** [comment]
@devsprint  I believe it's already there:
https://github.com/akka/alpakka/tree/v0.14/kinesis/src

**Comment by ennru** [comment]
This has been around for a while now. https://doc.akka.io/docs/alpakka/current/kinesis.html#kinesis-firehose-streams
