### ISSUE TITLE
Jms: Producer should retry sending messages

### ISSUE THREAD

**Issue by andreas-schroeder** [akka/alpakka#1226]
Thanks to @akara, the Jms connector now has reconnect capabilities that are used during initial connection in both producer and consumers, but only the consumer stage leverages the reconnect logic while the stream is running.

What is missing is to enable reconnection in the producer stage, and implement sending in a way that retries a configurable amount of time on failure.

For this, I have a proposal available that we can discuss (PR will follow).

**Comment by akara** [comment]
Yes please!
