### ISSUE TITLE
AWS SQS: Consider AmazonSQSBufferedAsyncClient

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1238]
Consider using `AmazonSQSBufferedAsyncClient` (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-client-side-buffering-request-batching.html) to simplify the Alpakka implementation.

**Comment by gabfssilva** [comment]
`AmazonSQSBufferedAsyncClient` does not support FIFO  queues yet, so, either we implement both `AmazonSQSBufferedAsyncClient` and `AmazonSQSAsyncClient` to support both queue types or just `AmazonSQSAsyncClient`, as it is used now to support both.

**Comment by ennru** [comment]
This is not relevant anymore after the move to AWS SDK 2.
