### ISSUE TITLE
Spring Web: Alpakka Spring Web doesn't work with Spring Boot 2.0

### ISSUE THREAD

**Issue by wgx731** [akka/alpakka#1246]
Hi there,

I am searching on Spring Akka integrations, and I have found Alpakka. It seems like the current implementation doesn't support Spring Boot 2.0. You can find my example app at: https://github.com/wgx731/dr-spring/blob/master/dr-spring-gateway/src/main/java/com/github/wgx731/gateway/DrSpringGateway.java#L10

The error is Bean **RequestMappingHandlerAdapter** is missing, it seems like Spring Boot 2.0 dropped servelet MVC support by default. 😢I have tried to add **spring-boot-starter-web** or **spring-boot-starter-webmvc** in the dependency, but still no luck. 

Any idea / hint how I can fix this issue?

Thank you very much.

**Comment by 2m** [comment]
I see. Maybe Sprint Boot 2.0 migration guide could point into the direction that Alpakka Spring Web connector needs to be updated? https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide

If you find the solution, PRs are welcome! :)

**Comment by wgx731** [comment]
@2m, sure, let me research on the topic and see how to make the project to support spring boot 2.0 with web flux. 😃

**Comment by sleipnir** [comment]
I created a PR for this item.
https://github.com/akka/alpakka/pull/1439
