### ISSUE TITLE
FTP: subtree keeps mutable state within stage

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1253]
The `doc` field in `Subtree` must be moved to become part of the stage logic, as it contains mutable state and would be shared by multiple materialisations of the stream otherwise.

https://github.com/akka/alpakka/blob/b0537f6c0a1795815e1a08fb30b2a8d3de1e0af8/xml/src/main/scala/akka/stream/alpakka/xml/impl/Subtree.scala#L18-L24

**Comment by 2m** [comment]
I see that `doc` is only used as a factory to create new elements. Does this kind of usage mutate something inside of the `doc` so different materialization would get different elements created because of that?

**Comment by ennru** [comment]
Ah, you're right I didn't look any deeper, the method names misguided me to believe we use the created document to add stuff to it.
