### ISSUE TITLE
PubSub subscriber source spins in tight loop, using 100% CPU

### ISSUE THREAD

**Issue by gabrielreid** [akka/alpakka#1254]
While testing the Google PubSub subscriber (non-GRPC version) using the [PubSub emulator](https://cloud.google.com/pubsub/docs/emulator), I noticed that both the emulator process and my subscriber process were each using 100% of one CPU core, although there was no data being published or read in PubSub.

I traced this back to [this line](https://github.com/akka/alpakka/blob/master/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/HttpApi.scala#L79) of the HttpApi class, where the `returnImmediately` parameter is set to true.

As per the [PubSub subscriber docs](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/pull), setting the `returnImmediately` parameter to true causes HTTP requests to return immediately if there is no data available (instead of blocking for a short time to wait for available data).

In the case of an idle PubSub topic, this seems to have the effect that the PubSub source simply spins in a tight loop, constantly polling the PubSub HTTP endpoint and not getting any data, thereby causing the 100% CPU usage.

This situation is obviously amplified when running with the PubSub emulator locally, as there is virtually no latency in requests (and conversely, when running locally against a "real" PubSub instance, this situation would be not at all visible due to network latency). However, it stands to reason that code running in GCP could also suffer from a similar situation due to the low latency of everything being co-located in GCP.

I've done a local test where I patched Alpakka to set the `returnImmediately` flag to `false`, and it appears to immediately resolve the issue (while not introducing any extra noticeable latency). 

Either setting `returnImmediately` to `false` instead of `true`, or making this an option (somewhat similar to how the [`pollInterval` is a parameter in the GRPC-based implementation](https://github.com/akka/alpakka/blob/master/google-cloud-pub-sub-grpc/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/grpc/scaladsl/GooglePubSub.scala#L46)) would resolve this issue.

**Comment by 2m** [comment]
Yes, it sounds good. Could you create a PR that exposes `returnImmediately` to the user facing API?

**Comment by gabrielreid** [comment]
Ok, created PR #1259 for this
