### ISSUE TITLE
Mention javaAgent for ALPN in pub/sub grpc connector docs

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1255]
We should mention the configuration needed for `javaAgent` that should be added to projects of Google Cloud Pub/Sub gRPC users.

For sbt projects it should be the case of enabling JavaAgent plugin:

https://github.com/akka/alpakka/blob/7404ed625228f46a48b8be1e7f4ed512662c91c4/project/plugins.sbt#L14
https://github.com/akka/alpakka/blob/7404ed625228f46a48b8be1e7f4ed512662c91c4/build.sbt#L132

And adding alpn agent to the `javaAgents` setting:

https://github.com/akka/alpakka/blob/7404ed625228f46a48b8be1e7f4ed512662c91c4/build.sbt#L129

We should also add instructions for [Maven](https://developer.lightbend.com/docs/akka-grpc/current/buildtools/maven.html#starting-your-akka-grpc-server-from-maven) and [Gradle](https://developer.lightbend.com/docs/akka-grpc/current/buildtools/gradle.html#starting-your-akka-grpc-server-from-gradle) users.

**Comment by 2m** [comment]
Related: https://github.com/akka/akka-grpc/issues/412

**Comment by mmatloka** [comment]
Hi, @2m I'm trying to use Alpakka Pub/Sub gRPC with emulator, I've added the lines mentioned in this issue (together with ` rootCa = "none"` etc in the config), and I still get the `  java.lang.IllegalArgumentException: Could not find Jetty NPN/ALPN or Conscrypt as installed JDK providers`. Are you sure any additional config is not needed? Btw is the  `AkkaGrpcPlugin` needed?

**Comment by 2m** [comment]
The ` AkkaGrpcPlugin` should not be needed.

You should not have the `% "test"` part in the `javaAgents` key. Did you remove it?

**Comment by mmatloka** [comment]
🤦‍♂️  that was it!

**Comment by jacobg** [comment]
I'm also running into this error using the Akka Stream connector Google Cloud Pub/Sub gRPC:
```
Error occurred in stream: java.lang.IllegalArgumentException: Could not find Jetty NPN/ALPN or Conscrypt as installed JDK providers
```

I added the sbt configurations documented in the first comment of this issue, and the same error still occurs. The error is occurring in a unit test I'm running inside IntelliJ. Should that work?

**Comment by andrea-zanetti** [comment]
I'm having the same issue too, but trying to connect to the actual APIs: java.lang.IllegalArgumentException: Could not find Jetty NPN/ALPN or Conscrypt as installed JDK providers

I must mention i've configured the publisher programmatically, and not via the config file (i do not think this make any difference, but just in case...):

```scala
val callCredentials: GoogleCredentials = GoogleCredentials
      .fromStream(credentialsInputStream)
      .createScoped(Collections.singletonList("https://www.googleapis.com/auth/pubsub"))

    val settings = PubSubSettings(sys)
      .withHost("pubsub.googleapis.com")
      .withPort(443)
      .withRootCa("GoogleInternetAuthorityG3.crt")
      .withCallCredentials(MoreCallCredentials.from(callCredentials))

    val publisher = GrpcPublisher(settings)
    val attributes = PubSubAttributes.publisher(publisher)

    GooglePubSub
      .publish(parallelism = 1)
      .withAttributes(attributes)
```

**Comment by 2m** [comment]
@andrea-zanetti could you try with the updated gRPC dependencies from this PR (https://github.com/akka/alpakka/pull/1886)? That PR has been merged but not yet published as a snapshot. So I hope it will not be a trouble for you to publish current master locally and try that.

**Comment by ennru** [comment]
I added some docs for this in #2050

**Comment by Javac7** [comment]
Same error here while trying to use the last version of akka gRPC google pubsub.

**Comment by Javac7** [comment]
I'm using javaAgents and AkkaGrpcPlugin but always got error "Could not find Jetty NPN/ALPN or Conscrypt as installed JDK providers"

My build.sbt

```scala
lazy val pubsubStream = project
    .in(file("pubsub-stream"))
    .settings(name := "pubsub-stream")
    .settings(commonSettings)
    .enablePlugins(JavaAgent,AkkaGrpcPlugin, PackPlugin)
    .settings(packMain := Map("Main" -> "com.project.Main"))
    .settings(libraryDependencies ++= Dependencies.generalDependencies)
    .settings(javaAgents ++= Dependencies.grpcNetty)
    .settings(akkaGrpcGeneratedSources := Seq(AkkaGrpc.Client))
    .settings(akkaGrpcGeneratedLanguages := Seq(AkkaGrpc.Scala))
```

**Comment by Javac7** [comment]
TLS error when truing to run with docker container:
```scala
Dec 23, 2019 2:29:46 AM com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
Error caused by 2 => UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
Error caused by 1 => UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]

```
@ennru, this is some bug ?

**Comment by seglo** [comment]
@Javac7 Looks fine to me.  I assume the Java agent SBT plugin is added to your project, and that `Dependencies.grpcNetty` is an alias to `"org.mortbay.jetty.alpn" % "jetty-alpn-agent" % "2.0.9"`?

Can you confirm that the `javaagent` JVM flag is being used in the commandline when you run your program?

**Comment by ennru** [comment]
I believe the updated docs cover the setup required for gRPC sufficiently now.
See https://doc.akka.io/docs/alpakka/snapshot/google-cloud-pub-sub-grpc.html

Please create a new issue (or even better a PR) if there is something we can improve on.
