### ISSUE TITLE
Alpakka docs: links to source code are broken

### ISSUE THREAD

**Issue by agolubev** [akka/alpakka#1260]
https://doc.akka.io/docs/akka-stream-kafka/current/producer.html
You can try first link "Full source at GitHub" and it goes to github 404 (https://github.com/akka/alpakka-kafka/tree/v0.22/docs/src/test/scala/sample/scaladsl/ProducerExample.scala#L30-L33)
This issue is across all links

**Comment by 2m** [comment]
Thanks for reporting! We had a branch with the same name as the latest tag `v0.22`. And that branch pointed to the already moved around code. I have removed the branch and now links work fine.

**Comment by agolubev** [comment]
thanks!
