### ISSUE TITLE
Jackson-based JSON data transformation module

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1266]
For Java users, Jackson is the natural choice for JSON processing. I believe it makes sense to offer pre-packaged Jackson flows for use with Akka Streams.

**Comment by jewertow** [comment]
If it is still to be done I would implement this, but please describe what would you expect from it. Should it be new dsl object, similar to https://github.com/akka/alpakka/blob/master/json-streaming/src/main/scala/akka/stream/alpakka/json/scaladsl/JsonReader.scala, but based on Jackson?

**Comment by seglo** [comment]
@ennru Is this an idea for the existing [json-streaming](https://doc.akka.io/docs/alpakka/current/data-transformations/json.html) library,  or something else?

**Comment by ennru** [comment]
When I wrote this I hade some kind of transformation in mind, not sure how relevant that is. Jackson is not streaming-aware AFAIK, so it might not be the best tool for that job.

But since than [Akka has made Jackson-serialization its recommended choice](https://doc.akka.io/docs/akka/current/serialization-jackson.html), it might be interesting to create some convenience for streams on top of it.

**Comment by seglo** [comment]
The underlying JsonSurfer implementation used by `json-streaming` is using Jackson, so I'm not sure that this issue is still relevant.

https://github.com/akka/alpakka/blob/master/json-streaming/src/main/scala/akka/stream/alpakka/json/impl/JsonStreamReader.scala#L37

**Comment by jewertow** [comment]
So let’s close this issue.
