### ISSUE TITLE
DynamoDb: docs.javadsl.ExampleTest.flow TimeoutException

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1269]
Noticed that lately one test from the DynamoDb javadsl ExampleTest started failing: https://travis-ci.org/akka/alpakka/jobs/439307358

**Comment by 2m** [comment]
Here as well: https://travis-ci.org/akka/alpakka/jobs/438480369

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/439341968

**Comment by ennru** [comment]
Again https://travis-ci.org/akka/alpakka/jobs/443305476
