### ISSUE TITLE
SQS local buffering cannot be deactivated

### ISSUE THREAD

**Issue by aserrallerios** [akka/alpakka#130]
SqsSource is configured using

```scala
object SqsSourceSettings {
  val Defaults = SqsSourceSettings(20.seconds, 100, 10)
}

final case class SqsSourceSettings(longPollingDuration: FiniteDuration, maxBufferSize: Int, maxBatchSize: Int) {
  require(maxBatchSize <= maxBufferSize)
}
```

To deactivate local buffering one would think that it's enough to give as configuration:
* maxBufferSize = 1
* maxBatchSize = 1

That won't work at all. If you look carefully the code you'll see that there are not retries if the buffer is not _below_ the latest batch call:

https://github.com/akka/alpakka/blob/master/sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceStage.scala#L66

For example, if the max buffer size is 100 and the batch size is 10, there's no retry at 90 buffer size. If downstream pulls when the buffer is at 90, there will be a new request and an element will be removed from the buffer: 89 buffer size, and then 99 buffer size at max. If the downstream never pulls (due to an empty response from SQS server), the Source won't retry on it's own if `maxBufferSize` == `maxBatchSize`.

To fix it, either change the configuration validation (this would make local buffering mandatory, at least one element)
```scala
  require(maxBatchSize < maxBufferSize)
```
or the conditions of the Source logic:
https://github.com/akka/alpakka/blob/master/sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceStage.scala#L66
https://github.com/akka/alpakka/blob/master/sqs/src/main/scala/akka/stream/alpakka/sqs/SqsSourceStage.scala#L75

**Comment by dpfeiffer** [comment]
@aserrallerios I agree that for the scenario you tried the Source will stop loading elements from SQS. But also with your proposed changes to the logic you would still have at max 1 element in the buffer:

* buffer.size == 0, downstream pulls
* 1 message received, added to the buffer, removed from the buffer and pushed downstream
* requesting new message from sqs ( `buffer.size <= settings.maxBufferSize - settings.maxBatchSize == true`
* downstream has not pulled yet so we put that new message on the buffer

I think we should go with `maxBatchSize < maxBufferSize` instead.

**Comment by aserrallerios** [comment]
Done with `maxBatchSize <= maxBufferSize`.
