### ISSUE TITLE
Move IBM MQ example code to runnable (or at least compilable) example

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1328]
Currently JMS connector IBM MQ example code is kept inline in the documentation. It should be moved to runnable, or at least compilable source files.

**Comment by NikitaZhevnitskiy** [comment]
Are there opportunity to have `embedded ibm mq broker` for testing purpose? I can not find any useful info. 
Other option is to have it in docker container.

**Comment by NikitaZhevnitskiy** [comment]
Reference to PR #1482

**Comment by ennru** [comment]
Fixed with #1482
