### ISSUE TITLE
SSE: support gzip encoding

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1356]
The Alpakka SSE client doesn't support gzipped replies out of the box.
This can easily be added by amending the `send` function as shown in the test added in https://github.com/akka/alpakka/pull/1355/commits/82b7ac8118c77b47518bc51225ab77acdb8dec64.

**Comment by jefftt** [comment]
Hi! Hopefully this is still wanted. I put up a PR that addresses this.
