### ISSUE TITLE
Use ChildTerminated in Akka 2.5.19 in mqtt connector

### ISSUE THREAD

**Issue by patriknw** [akka/alpakka#1359]
Added in https://github.com/akka/akka/pull/25992 which will be released in Akka 2.5.19

@huntc Would you be able to follow up here when Akka 2.5.19 has been released (scheduled for today)?

**Comment by huntc** [comment]
Absolutely! Thanks.

**Comment by huntc** [comment]
Addressed by https://github.com/akka/alpakka/pull/1361

cc. @chbatey
