### ISSUE TITLE
HTTPS protocol in DynamoDB AwsClient should not be hardcoded

### ISSUE THREAD

**Issue by tPl0ch** [akka/alpakka#1380]
Hi,

we are running our environments based on environment variables through `application.conf`:

```
akka.stream.alpakka.dynamodb {
  region = ""
  region = ${?DYNAMO_DB_REGION}
  host = "localhost"
  host = ${?DYNAMO_DB_HOST}
  port = 8042
  port = ${?DYNAMO_DB_PORT}
  tls = false
  tls = ${?DYNAMO_DB_ENABLE_TLS}
  parallelism = 2
  parallelism = ${?DYNAMO_DB_PARALLELISM}
  credentials {
    access-key-id = "dummy"
    access-key-id = ${?DYNAMO_DB_ACCESS_KEY}
    secret-key-id = "credentials"
    secret-key-id = ${?DYNAMO_DB_SECRET_KEY}
  }
}
```

Unfortunately it is impossible to use the HTTP protocol (required when running tests on our docker based CI runners and the [Local AWS DynamoDB Docker image](https://aws.amazon.com/de/about-aws/whats-new/2018/08/use-amazon-dynamodb-local-more-easily-with-the-new-docker-image/)).

Is there a specific reason to hard-code the `https` protocol?

Regards,
Thomas

**Comment by ennru** [comment]
Doesn't `tls = false` select HTTP?

**Comment by tPl0ch** [comment]
@ennru That was my expectation, but no:

https://github.com/akka/alpakka/blob/master/dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/AwsClient.scala#L78

**Comment by tPl0ch** [comment]
@ennru I certainly do:

https://github.com/akka/alpakka/pull/1384
