### ISSUE TITLE
gRPC external credential file

### ISSUE THREAD

**Issue by barisbolkan** [akka/alpakka#1385]
Hi,

gRPC connector only supports the "google-application-default" type of credentials. Is there a way to give the credentials from an external file?

**Comment by 2m** [comment]
You can set the environment variable `GOOGLE_APPLICATION_CREDENTIALS` to point to an external credentials file ([Google docs](https://cloud.google.com/docs/authentication/production))

**Comment by stephennancekivell** [comment]
As an example of when you may need this.
Consider if your application needs two different credentials. For example read from one google account and publish to another.
Currently this is supported in the other http connector google-cloud-pub-sub connector, where you have to provide the manually.

**Comment by armanbilge** [comment]
This will be fixed in #2613.

**Comment by seglo** [comment]
Fixed in #2613
