### ISSUE TITLE
unresolved dependency [sbt-dependency-graph] on [master] 

### ISSUE THREAD

**Issue by sullis** [akka/alpakka#1388]
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: net.virtual-void#sbt-dependency-graph;0.9.2+10-148ba0ff: configuration not found in net.virtual-void#sbt-dependency-graph;0.9.2+10-148ba0ff: 'master'. It was required from com.lightbend.paradox#sbt-paradox-dependencies;0.1 compile

**Comment by sullis** [comment]
@ennru

**Comment by ennru** [comment]
Ah, sorry. That is the patched version of `sbt-dependency-graph` which we pull in. You can either comment out your own `sbt-dependency-graph` in `~/.sbt` or add the `resolvers += Resolver.bintrayIvyRepo("2m", "sbt-plugins")` globally.

**Comment by huntc** [comment]
I too had this issue. Could you just not add the resolver to the main build?

**Comment by ennru** [comment]
It is there, but something happens when you have the different version as global sbt plugin. As far as I understand.

**Comment by 2m** [comment]
Can you try cleaning `sbt-dependency-graph` from you local ivy cache?

```sh
rm -rf ~/.ivy2/cache/scala_2.12/sbt_1.0/net.virtual-void/sbt-dependency-graph/
```

**Comment by huntc** [comment]
@2m This made no difference for me.
