### ISSUE TITLE
Reuse predefined stages vs create custom ones

### ISSUE THREAD

**Issue by gabfssilva** [akka/alpakka#1453]
I have kind of a stupid question that I've not been able to figure it out myself, so, I thought to ask you guys:

I'm porting a few Alpakka's AWS modules to SDK 2.0 and I've been wondering what could be rewritten in a simpler way. For instance, I can't tell why the SqsSource is written using a custom GraphStage when it could be written like: (...)

```scala
  def receiveMessages(queueUrl: String, settings: SqsSourceSettings = SqsSourceSettings.Defaults, sqsClient: AsyncSqsClient): Future[List[Message]] = _

  def queueSource(queueUrl: String, settings: SqsSourceSettings = SqsSourceSettings.Defaults, sqsClient: AsyncSqsClient): Source[Message, NotUsed] =
    Source
      .repeat((queueUrl, settings, sqsClient))
      .mapAsync(settings.maxParallelRequests)(receiveMessages)
      .mapConcat(identity)
```

(...) instead of the current [SqsSourceStage](https://github.com/akka/alpakka/blob/master/sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsSourceStage.scala) that has over a hundred lines.

What's wrong with reusing predefined stages instead of creating new ones?

**Comment by 2m** [comment]
Hi @gabfssilva. Sorry for a delayed response. We were in a F2F meeting which has decreased the attention we put to the online channels.

There is nothing wrong reusing predefined stages. In fact, that is the preferred way to write stages that integrate with other technologies. As you have noticed, it really brings down the complexity to the minimum. However it is possible to do that only if the external technology that you write the connector for provides simple enough API.

Now when it comes to SQS I see that it is not very straightforward. For example the `sqsClient.receiveMessageAsync` takes the `AsyncHandler` which then is called when the request completes. That is not very easy to integrate with from `mapAsync` operator. Still possible by creating a `Promise` for every request and completing it from the `AsyncHandler`, but at that point it might be worth moving to `GraphStage`.

P.S. You might want to try [the Lightbend forum](https://discuss.lightbend.com/c/akka/streams-and-alpakka) for discussions, as we try to keep the general discussions out of the GitHub issue tracker.
