### ISSUE TITLE
Google Pub/Sub gRPC - Expose acknowledge Sink as a Flow

### ISSUE THREAD

**Issue by josefelixh** [akka/alpakka#1459]
Google Pub/Sub gRPC exposes a Sink to acknowledge processed messages, it would be convenient to expose the acknowledge functionality also as a Flow.

Happy to contribute 😄

**Comment by 2m** [comment]
Sounds good! Just a heads up that quite soon I will do some refactoring where GooglePubSubExternal will go away and GrpcPublisher will be able to be injected via attributes. Same fate that struck S3 and DynamoDb connectors so far.

**Comment by 2m** [comment]
@josefelixh this is the PR I mentioned before #1466

**Comment by josefelixh** [comment]
Cheers @2m are you suggesting I wait for #1466 to be completed/merged? or shall I branch from `2m:wip-pubsub-grpc-attr-2m`?

**Comment by 2m** [comment]
It will be merged quite soon. But if you want to start immediately you can start working from my branch and then rebase when the PR gets merged.

**Comment by josefelixh** [comment]
I see #1466 is merged 🎉

**Comment by ennru** [comment]
Fixed with #2422 and #2425
