### ISSUE TITLE
Timely publication of snapshots

### ISSUE THREAD

**Issue by huntc** [akka/alpakka#1460]
I was wondering why snapshots aren't always published on a commit to the master branch... as per the advertisement. Are tests running and failing which then cause the inability to publish? It doesn't seem so, but just in case, I don't think tests should be a pre-requisite of running the publication of snapshots.

**Comment by ennru** [comment]
We consider the failing tests a stopper for publishing snapshots. We need to keep after those failures and try to keep the master build tests working.
But often they are flaky for Travis' isn't that fast...

**Comment by huntc** [comment]
Thanks @ennru - understood. However, each of the Alpakka sub-projects are quite isolated from each other. Why should one project fail to publish if it can pass its own tests? Again, just for snapshots...

I was thinking that the snapshot page could indicate a version per sub project, rather than one version for them all... WDYT?

**Comment by ennru** [comment]
Another a bit practical factor to this is that our Bintray cleanup is not automated, yet. So publishing after just some master builds requires us to clean less often...

**Comment by huntc** [comment]
I appreciate the bintray cleanup issue. However, I think that needs to be solved no matter what. Perhaps bintray itself could benefit from functionality to cleanup aged artifacts for some repos...

Meanwhile, may be we should correct the language on the snapshot page as it isn’t accurate. WDYT?

Feel free to close this issue if you’d like.
