### ISSUE TITLE
SqsAckFlowStage doesn't honor supervision

### ISSUE THREAD

**Issue by cchantep** [akka/alpakka#1467]
See https://github.com/akka/alpakka/blob/master/sqs/src/main/scala/akka/stream/alpakka/sqs/impl/SqsAckFlowStage.scala#L70

### Versions used 
Alpakka version: 1.0-M1

Akka version: 2.5.17

### Expected Behavior

The `Supervision` must be used in case of error in `SqsAckSink` or `SqsAckFlow`.

### Actual Behavior

`Supervision` is ignored, and the stage is "just" stopped, even in case of recoverable error; e.g.

```
Error in stage [akka.stream.alpakka.sqs.impl.SqsAckFlowStage@2c99266e]: Value AQEBaImVWqfthQQJ2uBeoWd5289aKW0ducuc4DiU04kajlJJAetsjw5VAD8QTz2ijiq9EgwIxLiKk7uzn3K4SDykHP8aHjnjtVSzWbOU23Z7iZZKcVUGwbmTAMizC1JdSJNCdaY8SZdBb4/7VF7+xUh4mXRWcbVX0mV6IdPB12gWgacJmp07O/sANrSnVuVHqjxxmCN2GHgWmY0Qpy5MSByBRoxPk7RrS7Ii5yl4P8DtOqrrgpVjLnWb+O6F6o60TgbaHSxZk+g+NlCokqdoepXMui3Tul+DwzydXWvmdFzgqjLbWRsJX3QLbrqdnLaC3Tt6pdXc2+ymfyZA4titu8psqtIgHjbbOhOLaB25LmMEir2usLkmIHRx3y9UfL2wN2U+vLMsa1V/k7+2xlBQj9pvcXvAFYX+IDc7mXLtiw1IfBE= for parameter ReceiptHandle is invalid. Reason: Message does not exist or is not available for visibility timeout change. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: b44f3c12-5f6a-5303-bb47-68d8e4b88230) (Service: null; Status Code: 0; Error Code: null; Request ID: null)
```

**Comment by gipeshka** [comment]
Was it fixed in M3 with these lines https://github.com/akka/alpakka/pull/1450/files#diff-4de572ec136178da0a5748ab76a05ef5R35 wasn't it?

Using the default `.mapAsync` should automatically honor supervision of a graph.

**Comment by ennru** [comment]
Yes, you are right. This should be solved since the change to the AWS SDK 2.
Thank you.
