### ISSUE TITLE
Create Java example for log rotator + compression + sft

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1479]
The #1476 added a Scala example for LogRotator with compression and uploading file to SFTP. This ticket is for adding the corresponding Java sample.

**Comment by pushpavanthar** [comment]
I would like to pick this up.

**Comment by fagossa** [comment]
@2m The goal is to migrate the same example (`RotateLogsToFtp`) to Java or make a completely new one?

**Comment by 2m** [comment]
Yes, the goal is to have the same example in Scala and Java.

**Comment by fagossa** [comment]
Hello, @2m I proposed a simple PR that migrates `RotateLogsToFtp`, thanks for your time

**Comment by 2m** [comment]
Thanks a lot for doing the migration!
