### ISSUE TITLE
JMS Selectors

### ISSUE THREAD

**Issue by evan108108** [akka/alpakka#149]
How can I add simple JMS Selectors? Like "myfilter='abc'"? 

```scala
session.createConsumer(destination, "myfilter='abc'")
```

**Comment by patriknw** [comment]
@larousso Do you know the answer here?

**Comment by larousso** [comment]
This not implemented, but it could be easily added. 

A workaround is to use the filter from the akka stream api.

**Comment by evan108108** [comment]
@larousso This is what I am doing now (simply filtering each message in the stream). This works fine but it is perhaps not as efficient for some workflows. I hope this can be added in the future.

**Comment by johanandren** [comment]
@evan108108 Maybe the perfect task for a first alpakka PR? ;)

**Comment by larousso** [comment]
@evan108108 @johanandren  I can do PR for this issue but if you want to participate tell me I let you work on this.

**Comment by rafacm** [comment]
@larousso @evan108108 Have a look the wip-jms-selectors-issue-149 branch [here](afacm/alpakka/tree/wip-jms-selectors-issue-149). 

Implemented:
1. Introduced a case class JmsTextMessage to model JMS messages with properties. I followed the same pattern as in the MQTT connector.
2. Added a JmsTextMessageSink and refactored JmsSinkStage to add support for "sending" messages with properties
3. Refactored Java and Scala unit tests and added Scala unit test for the selector feature

Open questions/issues/tasks:
- [ ] I have left the current `JmsSink` that accept String(s). Should we leave it or should we have only one Sink that accepts `JmsTextMessage`s?
- [ ] Add Java unit tests for the selector feature
- [ ] Update documentation with the selector feature

I can implement the above points once we have clarified the options.

**Comment by evan108108** [comment]
@rafacm +1 | This looks great! 

About the first point, I would probably only ever use the JmsTextMessage Sink. I had to implement something very similar as it is now.

**Comment by larousso** [comment]
@evan108108  @rafacm This seems nice. 

For the first point, may be you should only keep the JmsSink that take a TextMessage and add a method like stringSink that take string and do the transformation even if that break the api.

May be TextMessage should extend a JmsMessage trait and the Sink use this trait. For the future we could implement the other type of messages supported by jms extending this trait. 

What do you think ?

**Comment by evan108108** [comment]
@rafacm Where are you with the "Open questions"? Do you need help?

**Comment by johanandren** [comment]
@rafacm A factory that accepts `Strings` can probably easily be achieved through composition? `Flow.fromFunction(text: String => JmsTextMessage(text)).to(JmsSink)`

**Comment by rafacm** [comment]
Support for JMS Selectors implemented in #200. IMHO this issue can be closed.

**Comment by raboof** [comment]
:+1:
