### ISSUE TITLE
JMS: IBM MQ brings in `javax.jms` 2.0.1

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1493]
PR #1482 pulled in `javax.jms % jms-api` 2.0.1 which replaces version 1.1 with new required methods in `javax.jms.ConnectionFactory`.

ActiveMQ 5.15.8 is still on JMS 1.1.

**Comment by ennru** [comment]
cc @NikitaZhevnitskiy

**Comment by NikitaZhevnitskiy** [comment]
@ennru any suggestions how to resolve it for `ActiveMQ`? For instance, wait for new `activemq-client` release?

**Comment by ennru** [comment]
It just affects the test dependencies, so I tried adding the missing methods and everything still works.
I'll create a PR.
