### ISSUE TITLE
question: next release or daily snapshots

### ISSUE THREAD

**Issue by joost-de-vries** [akka/alpakka#150]
I'm interested in using Dynamodb streams. But it isn't available as a part of Alpakka 0.5 it seems. 
There are no snapshot versions published either, right?

I'm curious what my options are here apart from making my own snapshot build. Any ideas?

Btw I noticed that the dynamodb subproject is not part of the overall build since it's not aggregated in the root sbt project. See [here](https://github.com/akka/alpakka/blob/master/build.sbt#L4)
Is that intentional?

**Comment by patriknw** [comment]
It should have been in 0.5, but it's not https://repo1.maven.org/maven2/com/lightbend/akka/

Probably something missing in the build. We'll publish a new release.

We are also having trouble with the documentation publish and therefore was 0.5 not announced yet.

@2m can you take a look at this also?

**Comment by joost-de-vries** [comment]
Btw the unittests of the Dynamodb subproject didn't run on my machine. I kept running into [this problem](http://stackoverflow.com/questions/34137043/amazon-dynamodb-local-unknown-error-exception-or-failure) with starting a local dynamodb that runs embedded in the JVM.

**Comment by 2m** [comment]
Indeed DynamoDB connector artifacts were not published because it was not part of the aggregate. I have published the artifacts for the 0.5 version and they are now in [Bintray repo](https://bintray.com/akka/maven/alpakka/0.5). They will appear in the Maven Central once the synchronization is completed.

I will take a look at DynamoDB unitests.

**Comment by joost-de-vries** [comment]
Tx. Now I can remove my own local built version.
Btw the readme isn't quite correct: it's not
```
    libraryDependencies += "com.typesafe.akka" %% "akka-stream-alpakka-dynamodb" % "0.5"
```
But "com.lightbend.akka" etc.

**Comment by patriknw** [comment]
Then we are all done here
