### ISSUE TITLE
Google Cloud PubSub gRPC: build for Scala 2.13

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1533]
This is a spinoff ticket from #828 that tracks Google Cloud PubSub gRPC connector cross-building for Scala 2.13.

Currently it is disabled because of [akka/akka-grpc#506](https://github.com/akka/akka-grpc/issues/506) which depends on [scalapb/ScalaPB#540](https://github.com/scalapb/ScalaPB/issues/540).

**Comment by ennru** [comment]
Awaiting https://github.com/akka/akka-grpc/pull/599

**Comment by ennru** [comment]
Akka gRPC 0.7.0 is ready to solve this.
