### ISSUE TITLE
Ironmq: build for Scala 2.13

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1534]
This is a spinoff ticket from #828 that tracks IronMq connector cross-building for Scala 2.13.

Currently it is disabled because [hseeberger/akka-http-json#253](https://github.com/hseeberger/akka-http-json/issues/253)

**Comment by ennru** [comment]
Heiko's Akka HTTP JSON is now available https://github.com/hseeberger/akka-http-json/releases
But it drops support for Scala 2.11 so we need to diverge the dependencies for different Scala versions.

**Comment by ennru** [comment]
It is first now that [Circe 0.12.0 is released](https://github.com/circe/circe/releases) the dependency of [akka-http-json Circe](https://github.com/hseeberger/akka-http-json) can be upgraded to a Scala 2.13 compatible version of the Circe module. 
Some modules were released for Scala 2.13 before, but not Circe (as build.sbt shows https://github.com/hseeberger/akka-http-json/blob/master/build.sbt#L63).

**Comment by ennru** [comment]
See https://github.com/hseeberger/akka-http-json/pull/324

**Comment by ennru** [comment]
Fixed with #1957
