### ISSUE TITLE
MongoDb: build for Scala 2.13

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1535]
This is a spinoff ticket from #828 that tracks MongoDb connector cross-building for Scala 2.13.

Currently it is disabled because https://jira.mongodb.org/browse/SCALA-506

**Comment by ennru** [comment]
https://github.com/mongodb/mongo-scala-driver/pull/66

**Comment by aka-bash0r** [comment]
The two referenced tickets / issues seem to be closed for about a month. Anything left to do in order to publish an updated version?

**Comment by 2m** [comment]
Unfortunately only a snapshot version of the Mongo Scala driver is yet available for Scala 2.13: https://oss.sonatype.org/content/repositories/snapshots/org/mongodb/scala/mongo-scala-bson_2.13/2.7.0-17-ge348ba1-SNAPSHOT/

Please ping the mongo-scala-driver project for a final release: https://github.com/mongodb/mongo-scala-driver/pull/66#issuecomment-512855423

**Comment by mikela** [comment]
@2m 
Version 2.7.0 released: 
https://mongodb.github.io/mongo-scala-driver/ 
https://mvnrepository.com/artifact/org.mongodb.scala/mongo-scala-driver
