### ISSUE TITLE
Can't specify maxOpenRequests in DynamoClient

### ISSUE THREAD

**Issue by williamho** [akka/alpakka#1542]
### Short description

Currently both `maxConnections` and `maxOpenRequests` in Dynamo are both always set to the `parallelism` setting, and it isn't possible to set them individually.

### Details

In the code here:
https://github.com/akka/alpakka/blob/a0a5c698033b0bd0e9007dc953b6faabd799e0b8/dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala#L37-L39

both values are always the same as `parallelism` and there doesn't seem to be a way to set them individually. I tried manually setting `akka.http.host-connection-pool.max-open-requests` in my config but it doesn't seem to do anything, and the code above takes precedence.

My use case is that on app startup, initial requests can take a long time (due to JVM warmup, etc) and in this case, the requests pile up in the queue up to a certain limit, and further requests are cancelled immediately rather than being enqueued and eventually completing. After some time, the JVM has warmed up and the requests take a normal amount of time with no backpressure issues.

Essentially, I would like to be able to set `maxOpenRequests` to a larger value to handle this startup case, but I don't want `maxConnections` to be an equally large number.

Or is there another recommended way to do this? I could have my own handler that catches this `BufferOverflowException` and attempts to re-queue it, but it seems weird to reimplement queueing when it's already configurable in akka-http.

**Comment by 2m** [comment]
Hi @williamho, 

I think giving more control over configuration to user is a right thing here. `DynamoSettings` should be expanded to have separate settings for that pool configuration. If you are up for it, PR would be very welcome with this change.
