### ISSUE TITLE
Bucket management in S3 module

### ISSUE THREAD

**Issue by MarcinAman** [akka/alpakka#1546]
### Short description

Implementing bucket management methods:
- create bucket
- remove bucket
- remove bucket with content
- list all buckets

### Details

Wouldn't it be nice to implement bucket management module inside S3? The AWS API is there and we have a generic method to perform requests. How about adding anther layer of abstraction by implementing those methods?

If you give me positive feedback i can give it a shot

**Comment by ennru** [comment]
Yes, it would make sense to offer some S3 admin API in Alpakka S3.

Looking forward to your proposal how it could look like.

**Comment by rmckirby** [comment]
Was going to propose this, would be a good addition :+1:
