### ISSUE TITLE
MQTT streaming: internal Akka streams error triggers in test case prevents shutdown

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1563]
### Expected Behavior

MQTT streams should shut down properly in test cases asserted by `assertAllStagesStopped` if the streams are completed and the MQTT session actors are shut down.

### Actual Behavior

Something triggers an error in the Akka Streams machinery which is evident in the logs and hinders proper shutdown.

### Relevant logs

```
2019-03-06 11:28:23,035 ERROR [mqtt-spec-akka.actor.default-dispatcher-3] [akka.actor.OneForOneStrategy]  56 (of class java.lang.Integer)
 scala.MatchError: 56 (of class java.lang.Integer)
     at akka.stream.impl.fusing.GraphInterpreter.$anonfun$toSnapshot$4(GraphInterpreter.scala:662)
```

### Reproducible Test Case

See `MqttSessionSpec` "MQTT server connector" should "close when no ping request received".

**Comment by huntc** [comment]
In particular, I’m wondering if a bitwise test is being properly performed: https://github.com/akka/alpakka/pull/1561#issuecomment-470401709

**Comment by ennru** [comment]
This hasn't surfaced since over a year.
Closing.
