### ISSUE TITLE
SqsAckResult should be a part of public API

### ISSUE THREAD

**Issue by gipeshka** [akka/alpakka#1590]
Alpakka version: 1.0-M3

Hi guys.

I'm using Alpakka SQS Sink and have faced an issue with writing tests on M3 after migration from M1. As I am using the grouped sink I want to cover this part of my application with unit tests. However I find myself unable to mock a Flow with signature `Flow[MessageAction, SqsAckResult[SqsResponse], NotUsed]`, because `SqsAckResult` is completely private entity.

The current solution I have is another layer of abstraction over the flow, that completely hides `SqsAckResult`.

Anyhow I think `SqsAckResult` isn't really a part of internal API as it is exposed to the clients of the library and therefore would be nice to have it as a public DTO.

**Comment by ennru** [comment]
You're right, the constructors are private and users should be able to construct those for testing.
I've created #1591 to track it.

**Comment by gabfssilva** [comment]
`FifoMessageIdentifiers`, `SqsPublishResult` and `SqsAckResult` are private and could be potentially exposed for testing purposes.

The fix is just remove both `private` modifier and `@InternalApi` for all these classes.

If I have time I can send a PR today.

**Comment by ennru** [comment]
No, please create a message factory for those instead, see #1591.

**Comment by gabfssilva** [comment]
Ok then.

**Comment by ennru** [comment]
Fixed with #1606
