### ISSUE TITLE
SFTP: overwrite existing file doesn't work

### ISSUE THREAD

**Issue by nukky94** [akka/alpakka#1599]
### Versions used 
Alpakka version: 1.0-RC1

### Expected Behavior

Uploading with `Sftp.toPath(path, settings, append = false)` should overwrite existing file.

### Actual Behavior

It doesn't work. New data is written at the start of the existing file.

### Relevant logs

It's perhaps due to missing `TRUNC` mode passed to the handler:

https://github.com/akka/alpakka/blob/v1.0-RC1/ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala#L107

doc:
```
net.schmizz.sshj.sftp.OpenMode.Trunc

  /**
     * Forces an existing file with the same name to be truncated to zero length when creating a file by specifying
     * {@link OpenMode#CREAT}. {@link OpenMode#CREAT} MUST also be specified if this flag is used.
     */
    TRUNC(0x00000010)
```

Fix:
` val openModes = Set(WRITE, CREAT) ++ (if (append) Set(APPEND) else Set(TRUNC))`

**Comment by ennru** [comment]
Thank you for reporting, your explanation makes total sense. I've seen similar things with local files that weren't truncated as that flag was missing.

Would you be able to prepare a PR to fix this?
