### ISSUE TITLE
[SolR] The routingField should not be forced to None

### ISSUE THREAD

**Issue by giena** [akka/alpakka#1635]
Why don't you authorize to set the routerField ? This field should be usefull in some case:
https://github.com/akka/alpakka/blob/3f0b8c62a4f11fcc25a3c05c39104e3a49a8aed6/solr/src/main/scala/akka/stream/alpakka/solr/SolrMessages.scala#L28

This field is useful when you have a composite id in your schema with an id field not the same as the router field used when you have created your collection. Otherwise, the solr client will throw an "Missing Required Field" on your atomic update.

**Comment by giena** [comment]
@ennru ?

**Comment by 2m** [comment]
You can call `withRoutingFieldValue` to set it:

`WriteMessage.createUpdateMessage(...).withRoutingFieldValue(...)`

**Comment by ennru** [comment]
I hope the earlier answer help you to get on with it.
I'll close this issue, please re-open if there is something missing.

**Comment by giena** [comment]
It's ok for me. Thx @ennru & @2m .
