### ISSUE TITLE
CSV: escape char makes valid csv unvalid

### ISSUE THREAD

**Issue by tg44** [akka/alpakka#1643]
[RFC4180](https://tools.ietf.org/html/rfc4180) does not contain any "escape chars". I think it's a nice and usable feature, but bcs I forced to use it, I can't parse big correctly formatted csv-s. (If its big enough its probably contains some `"\,"` and `"\"` like fields, and you need to change the escape char to something which not appears before `"` or `,`, but even with crazy chars like `\255` you can have a hit with Ï and Á and other special UTF8 chars)

After we did a `.map(bs => ByteString(bs.utf8String.replace("\\", "\\\\")))` before the csv parsing everything went green, but I don't think this is the "best" way.

So my proposal is to make the escape char optional.

This is problematic in a lot of levels. Firstly it probably breaks bincomp. And secondly that state-machine is scary, and its not so trivial to refactor to make it "good".

**Comment by ennru** [comment]
You're right, the parser should accept even unescaped input. 
An easy workaround is to set the escape byte to something not present in the input(eg. char 0).

**Comment by tg44** [comment]
We tried 255 and because of unlucky utf8 chars we still got a hit :( maybe 0 is better, but there is a point when you don't want to play with trial and error. 
(Or we should document that if you use 0 as an escape char it will never escape. (If that is generally true ofc.))

**Comment by ennru** [comment]
This is fixed with #1717
