### ISSUE TITLE
Support for Cassandra driver version 4.x

### ISSUE THREAD

**Issue by liff** [akka/alpakka#1647]
### Short description

Add support for the new 4.x series of DataStax’s cassandra driver.

### Details

[Version 4.0](https://docs.datastax.com/en/developer/java-driver/4.0/) of the Cassandra driver was released a short while ago. Would be nice to eventually have support for it in Alpakka.

The new version is [binary and source incompatible](https://docs.datastax.com/en/developer/java-driver/4.0/upgrade_guide/) with 3.x.

**Comment by 2m** [comment]
Thanks for the ticket. Upgrading to 4.x is planned together with #1213

**Comment by ennru** [comment]
Short update: The Akka team works on [Akka Persistence Cassandra 1.0](https://github.com/akka/akka-persistence-cassandra) and has incorporated the Cassandra 4.x driver.

**Comment by naderghanbari** [comment]
I took a stab at this. There are lots of improvements in the `4.x` series of the Cassandra Java Driver including new [Async Paging](https://github.com/datastax/java-driver/tree/4.x/manual/core/async#asynchronous-paging) and [Reactive](https://github.com/datastax/java-driver/tree/4.x/manual/core/reactive#reading-in-reactive-style) APIs.

With the reactive API, reading from Cassandra is as easy as
```scala
Source.fromPublisher(cqlSession.executeReactive(stmt))
```

The only issue left is to cache the Reactive Streams `Publisher` so the resulting `Source` supports multiple down-stream subscribers. 

All in all, given the fact that the driver now has a reactive API compatible with Reactive Streams, is `alpakka-cassandra` still valuable?

**Comment by ennru** [comment]
Hi @naderghanbari,

Thank you for looking into this. You're right, the new Reactive Streams compatible APIs in the Cassandra driver reduce the code Alpakka needs to add significantly.

I'm currently working on the new implementation in https://github.com/akka/akka-persistence-cassandra/pull/660 which will be used as a base for Akka Persistence Cassandra 1.0.
I'll get back to that work the now, please have a look and see how we can create a new and useful Alpakka Cassandra API.

**Comment by naderghanbari** [comment]
Thanks @ennru,

Sure. I have seen the migration to the new Java Driver in `akka-persistence-cassandra` and I have seen the discussions around potentially porting parts of `akka-persistence-cassandra` to `alpakka`. I'll checkout akka/akka-persistence-cassandra#660 to run/test it locally to have a better understanding.

**Comment by ennru** [comment]
This is now implemented with #2182
