### ISSUE TITLE
Is use of AWS SDK 1.11 'AWSCredentialsProvider' over AWS SDK 2 'AwsCredentialsProvider' intentional?

### ISSUE THREAD

**Issue by akauppi** [akka/alpakka#1655]
I'm using Alpakka S3 and Kinesis in a project with AWS SDK 2. In authentication, I cannot pass the 'AwsCredentialsProvider' (SDK 2 class) but need to convert it to 'AWSCredentialsProvider' (SDK 1.11 class).

Here are the places where the latter exists in the code:

https://github.com/akka/alpakka/search?q=AWSCredentialsProvider&unscoped_q=AWSCredentialsProvider

Is this intentional, or just an oversight due to moving between the SDKs? If the latter, I may proceed to suggesting a PR.

### Versions used 

Alpakka 1.0 RC1, 1.0

### Expected Behavior

I'd like to be able to deal with Alpakka 1.0 with AWS SDK 2 classes.

### Actual Behavior

For this case, I need to convert. The code I used for this (for anyone wanting a work-around):

```
def convert(in: AwsCredentialsProvider): AWSCredentialsProvider = {
  val tmp = in.resolveCredentials
  new AWSStaticCredentialsProvider( new BasicAWSCredentials(tmp.accessKeyId, tmp.secretAccessKey) )
}
```

**Comment by ennru** [comment]
This is not intentional for sure, thank you for reporting.
Let's find a way to use the new classes without breaking the Alpakka API.

**Comment by gabfssilva** [comment]
The actual implementation is based on plain Akka HTTP that uses the AWS 1.11.x model classes, we should update the S3 module to use the SDK 2.x instead.

There's an open issue for this already: #1342

**Comment by gabfssilva** [comment]
There's one also for Kinesis: #1347

**Comment by ennru** [comment]
Thank you @gabfssilva -- I was wondering how we would be able to blend the two versions but didn't have a proper look at things.

@akauppi I'll close this and encourage you to propose the necessary changes as of #1342 and #1347.
