### ISSUE TITLE
Ftp - ls does not emit directories in default case

### ISSUE THREAD

**Issue by tgambet** [akka/alpakka#1657]
### Version used

Akka version: 2.5.21
Alpakka FTP version: 1.0.0

### Current behavior

Listing a directory with `Ftp.ls(path, ftpSettings)` doesn't emit any `FtpFile` for directories (`isDirectory` is always false) while  `Ftp.ls(path, ftpSettings, _ => false)` does.

### Expected

`Ftp.ls(path, ftpSettings)` should emit `FtpFile`s for all directories that it finds while traversing the directory tree.

**Comment by 2m** [comment]
Thanks for the ticket. The default value for `branchSelector` is `f => true`, which means it will go down every directory but it does not emit directories themselves in the stream.

It does make sense to emit directories together with files. But when implementing this, we should also give the ability to get the current behaviour.

**Comment by tgambet** [comment]
I believe that the stream should contain both files and directories no matter what `branchSelector` is. It is unexpected that the branch selector changes the behavior of the command regarding what type of files are streamed. 
One can always get the current behavior by filtering the source : `Ftp.ls(...).filter(!_.isDirectory)`

**Comment by 2m** [comment]
That is a fair point. Do you think you could work on a PR to fix this?

**Comment by tgambet** [comment]
Yes, I can try.

**Comment by tgambet** [comment]
PR ready for review
