### ISSUE TITLE
Setting tls=true in DynamoSettings overwrites the configured port to 443

### ISSUE THREAD

**Issue by Ophirr33** [akka/alpakka#1662]
### Versions used 

Alpakka version: 1.0.0

Akka version: 2.5.22

### Expected Behavior
Using the alpakka client with:
```
    val settings = DynamoSettings(region, host)
      .withPort(8080)
      .withParallelism(5)
      .withMaxOpenRequests(Some(4))
      .withTls(true)
    val client  DynamoClients(settings)(someActorSystem, someMat)
    DynamoDb.source(someOp).withAttributes(DynamoAttributes.client(client)).runWith(Sink.head)
```
will attempt to connect to the specified region/host on port 8080

### Actual Behavior

The client attempts to connect on port 443 instead of port 8080

The issue seems to originate here: https://github.com/akka/alpakka/blob/master/dynamodb/src/main/scala/akka/stream/alpakka/dynamodb/impl/DynamoClientImpl.scala#L41

In the `tls = true` branch, no port is passed to `cachedHostConnectionPoolHttps`, whereas in the `tls = false` branch, the port _is_ passed to `cachedHostConnectionPool`.

**Comment by ennru** [comment]
Thanks for reporting. Would you be able to propose a fix in a PR?

**Comment by mavericksid** [comment]
Hi @ennru,

PR has been raised, please have a look:
https://github.com/akka/alpakka/pull/1722

**Comment by ennru** [comment]
The PR is merged and https://github.com/akka/alpakka/pull/1724 as a follow-up, as well.
