### ISSUE TITLE
AWS S3: Invalid credential date. Date is not the same as X-Amz-Date.

### ISSUE THREAD

**Issue by keimoon** [akka/alpakka#1690]
### Versions used 

1.0.0

Akka version: 2.6.0-M1

### Expected Behavior

Upload file to S3 using `S3Stream.multipartUpload` should success

### Actual Behavior

Upload failed with error related to `Invalid credential date. Date is not the same as X-Amz-Date.`

### Relevant logs

```
akka.stream.alpakka.s3.S3Exception: The authorization header is malformed; Invalid credential date. Date is not the same as X-Amz-Date.
        at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$initiateMultipartUpload$4(S3Stream.scala:294)
```
This bug maybe caused by a mismatch between `LocalDate.now()` used in `CredentialScope` and `ZonedDateTime.now(ZoneOffset.UTC)` used in `x-amz-date` header.
For example in my machine:

```
scala> LocalDate.now()
res4: java.time.LocalDate = 2019-05-09

scala> ZonedDateTime.now(ZoneOffset.UTC)
res5: java.time.ZonedDateTime = 2019-05-10T03:56:20.017Z
```

**Comment by ennru** [comment]
Thank you for reporting.
This is fixed in master with #1678 and #1686.

Snapshots are available https://doc.akka.io/docs/alpakka/current/other-docs/snapshots.html

**Comment by oker1** [comment]
The snapshot of this rev is not published yet, the last one I see is 0baab3fba160f9832b28eb430a4711b86b2373c6

**Comment by 2m** [comment]
`1.0.0+45-43918030` is the last one that I can see currently and it has these fixes merged in.

**Comment by ennru** [comment]
Closing this duplicate as it is solved in master and will be released tomorrow.
