### ISSUE TITLE
Add Amazon Kinesis support

### ISSUE THREAD

**Issue by alexmnyc** [akka/alpakka#170]

**Comment by sarveshseri** [comment]
Is there anyone working on it ?

If not then I would like to take this up.

**Comment by areyouspiffy** [comment]
I pretty much finished it [here](https://github.com/areyouspiffy/reactive-aws/tree/master/kinesis/src/main/scala/reactive/kinesis). You're welcome to take whatever you like from it. It uses the same AwsClient used by the existing DynamoDB connector.

**Comment by areyouspiffy** [comment]
@sarveshseri Are you working on this? If not, I will submit a PR for this in the next couple days.

**Comment by sarveshseri** [comment]
@areyouspiffy I had the notion that you were already working on it so I did not pick it up.

You should go ahead with your PR.

**Comment by easel** [comment]
This looks awesome! Any thoughts of doing a Sink as well?

**Comment by areyouspiffy** [comment]
@easel I don't personally has a use for a sink but I'm more than happy to add that if you think find it useful 👍

**Comment by easel** [comment]
@areyouspiffy I'd definitely use it and be willing to collaborate on it and test it -- I'm going to have to write one otherwise =p

**Comment by aserrallerios** [comment]
We've implemented one Flow that publishes messages to a Kinesis stream and we're currently testing it on production. If you're patient I can port it to alpakka.

**Comment by 2m** [comment]
I will close this as initial Kinesis support (Source) has been merged. Please open tickets for sink and flow discussions correspondingly.
