### ISSUE TITLE
Alpakka Google Cloud Pub/Sub: Allow HTTP(S) proxy configuration

### ISSUE THREAD

**Issue by cokeSchlumpf** [akka/alpakka#1705]
### Short description

The Alpakka Google Cloud Pub/ Sub Connector does not support configuration of a Proxy. In our enterprise environment we have to go through a proxy to reach Google API endpoints. Thus I would suggest to implement the support for Proxy configuration.

### Details

It should be possible to configure the proxy, I see two options to implement it:

a) Check for `http_proxy`, `https_proxy` as well as `no_proxy` environment variables to configure proxy for request as described in [Akka HTTP documentation](https://doc.akka.io/docs/akka-http/current/client-side/client-transport.html). Theoratically this could also be a feature of Akka HTTP.

b) Make Proxy configurable via Alpakka's Google Pub/Sub API. Similar to authentication properties.

I could also imagine that a combination of both might be implemented where as b) wins over a) when configured at both places.

I could support implementing it, but would first like to discuss which option might be the better one. Or maybe there is even another option....

**Comment by ennru** [comment]
Please note that a similar feature was recently added to Alpakka S3 in [#1639](https://github.com/akka/alpakka/pull/1639).

Please feel free to suggest a similar solution for Google Pub/Sub.

**Comment by gkatzioura** [comment]
Hi all! In my recent pull request for [BigQuery](https://github.com/akka/alpakka/pull/2106) I added the proxy feature from Alpakka S3.  Is it ok to proceed on this issue and add the proxy feature on Pub/Sub?

**Comment by seglo** [comment]
@gkatzioura That would be wonderful!  Please go ahead.

**Comment by armanbilge** [comment]
This will be fixed in #2613.

**Comment by seglo** [comment]
Fixed in #2613
