### ISSUE TITLE
No longer able to catch alpakka s3 exceptions.

### ISSUE THREAD

**Issue by thadeusb** [akka/alpakka#1706]
How do I catch a akka.stream.alpakka.s3.impl.FailedUpload? 

We have code that used to be able to catch this, specifically because we need to tell the difference between this exception so we know to retry an upload, or other exceptions that would not need a retry. Basically we have `case e: FailedUpload if e.getMessage.contains("Cannot find etag") =>` but this code is now impossible to execute it seems since the exceptions have been marked as private. 

I'm also really confused as to why an exception would ever be marked as private because that prevents anyone using the API from ever catching that exception and handling it properly.

**Comment by 2m** [comment]
This was an oversight. This exception is defined together with other case classes which are indeed internal and are converted to a public case classes when exposed to API. But no such convention is mage for this exception. It should be made public and moved to the appropriate package.

We should fix this for the next Alpakka bugfix release.
