### ISSUE TITLE
CSV line scanner skipping final line when last column is empty in 1.0.1

### ISSUE THREAD

**Issue by RoccoMathijn** [akka/alpakka#1710]
With version 1.0.1 of Alpakka CSV the line scanner skips the final line when the last line does not have a line ending and the last column in this line is empty.

I've recreated the issue using the demo app from kciesielski from this slightly related issue: https://github.com/akka/alpakka/issues/315

With 1.0.0 both of the tests succeed. With 1.0.1 the last one fails.
https://github.com/RoccoMathijn/akka-quickstart-scala/blob/master/src/test/scala/com/lightbend/akka/sample/CsvTest.scala

edit: I simplified some things in the issue. First I thought the problem only occurred when the last line had a column less than the rest AND the last column was empty. But the number of columns doesn't seem to matter.

**Comment by ennru** [comment]
Thank you for reporting, this must have been introduced by the optimisations in #1685.

**Comment by ennru** [comment]
Fixed with #1711
