### ISSUE TITLE
Move splitter example to Akka stream cookbook

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1732]
[Splitter](https://doc.akka.io/docs/alpakka/current/patterns.html#splitter) should become part of [Stream Cookbook](https://doc.akka.io/docs/akka/current/stream/stream-cookbook.html)
... and the Cookbook should point to Alpakka, as well.

**Comment by anthonyhlcheng** [comment]
Moved Splitter and Aggregator to Cookbook - with a reference to Alpakka
Cookbook PR: https://github.com/akka/akka/pull/31203

Removed the Splitter and Aggregator from Alpakka docs and removed the example java / scala classes
Alpakka Docs PR: https://github.com/akka/alpakka/pull/2834

**Comment by ennru** [comment]
Fixed with #2834
