### ISSUE TITLE
HDFS: Overwrite target file

### ISSUE THREAD

**Issue by markarasev** [akka/alpakka#1761]
### Versions used 

Akka version: 2.5.22
Alpakka version: 1.0.2

### Expected Behavior

Given an existent file in HDFS, overwriting it with a different content should change the file's contents.

### Actual Behavior

The stream execution succeeds but the target file's contents are unchanged.

### Reproducible Test Case

Run `docs.scaladsl.HdfsWriterSpec` from https://github.com/akka/alpakka/pull/1760

**Comment by 2m** [comment]
Thanks for the reproducer. Are you willing to take a stab at fixing this?

**Comment by markarasev** [comment]
I could try but I first need to be sure that I'm not misusing the API in the reproducer. Can someone confirm this is a bug and not an error from my side?
