### ISSUE TITLE
Need getter method for data in Alpakka UDP Datagram

### ISSUE THREAD

**Issue by dlmutart** [akka/alpakka#1768]
### Short description

The Alpakka UDP Datagram class need a getter method to access the data member variable.

### Details

Similar to java.net.DatagramPacket class, the Datagram class in Alpakka UDP needs a getter method such as getData() to return the data as a ByteString.  This would be especially helpful when working with UDP bindFlow flows where the outlet of Datagrams are then used in subsequent functions.

**Comment by 2m** [comment]
Yes, the Java API might be nicer with a `getData()` getter. But you should be able to use `data()` method to get the `ByteString` from the `Datagram class`.
