### ISSUE TITLE
DynamoDB: TransactWriteItem.Update Results in 500 When Using withReturnValuesOnConditionCheckFailure

### ISSUE THREAD

**Issue by pulltab** [akka/alpakka#1769]
### Versions used 

Akka version:  2.5.21

### Expected Behavior

I am using the following Update as part of a `WriteTransactionRequest`, however, any `Update` operation will exhibit this behavior when coupled `withReturnValuesOnConditionCheckFailure`:

```
   new Update()
      .withTableName("AnyOldTable")
      .withKey(Map("partition" -> "some-id"))
      .withExpressionAttributeNames(Map("#v" -> "value"))
      .withExpressionAttributeValues(Map(":value" -> new AttributeValue("foo")))
      .withUpdateExpression("SET #v = :value")
      .withConditionExpression("attribute_not_exists(#v)")
      .withReturnValuesOnConditionCheckFailure("ALL_NEW")
  }
```

I expect this Update would not result in localstack and dynamodb-local returning a 500 code.   I have confirmed that without `withReturnValuesOnConditionCheckFailure` that the above `Update` works as expected.

I am able to reproduce the above code in Python and Java.  Under these circumstances the localstack and dynamodb-local emulators behave as expected.

### Actual Behavior

Both emulators return 500 codes.

localstack emits the following debug output: 

```
localstack_1            | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
localstack_1            | 2019-06-18T22:55:59:ERROR:localstack.services.generic_proxy: Error forwarding request: object of type 'NoneType' has no len() Traceback (most recent call last):
localstack_1            |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 241, in forward
localstack_1            |     updated_response = self.proxy.update_listener.return_response(**kwargs)
localstack_1            |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 202, in return_response
localstack_1            |     if len(records) > 0 and 'eventName' in records[0]:
localstack_1            | TypeError: object of type 'NoneType' has no len()
```

### Relevant logs

See the previous section. 

### Reproducible Test Case

I will send some time later putting together a canned example.

**Comment by RustedBones** [comment]
Seems to be a issue on the `localstack` side IMHO.

By experience, `localstack` has some discrepancy compared to AWS specs or throws internal errors when using mode advanced features (like dynamodb streams or condition expressions)

**Comment by pulltab** [comment]
@RustedBones The 500 codes are returned by `dynamodb-local` as well as `localstack`.

alpakka-dynamodb is currently the "odd man out" as both the official Python and Java libraries work as expected (no 500 codes) against both `dynamodb-local` and `localstack`.

**Comment by RustedBones** [comment]
Checking the AWS sdk API documentation for [`ConditionCheck.withReturnValuesOnConditionCheckFailure`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/ConditionCheck.html#withReturnValuesOnConditionCheckFailure-java.lang.String-), valid values are `ALL_OLD` or `NONE`.
It is durprising that setting `ALL_NEW` didn't throw an exception.
I usually try to use the API taking the enum, here [`ReturnValuesOnConditionCheckFailure`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/ConditionCheck.html#withReturnValuesOnConditionCheckFailure-com.amazonaws.services.dynamodbv2.model.ReturnValuesOnConditionCheckFailure-) to avoid this kind of issue

**Comment by RustedBones** [comment]
The AWS documentation is really confusing me. On [`Update.withReturnValuesOnConditionCheckFailure`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/Update.html#withReturnValuesOnConditionCheckFailure-com.amazonaws.services.dynamodbv2.model.ReturnValuesOnConditionCheckFailure-), valid parameter values are  `NONE`, `ALL_OLD`, `UPDATED_OLD`, `ALL_NEW`, `UPDATED_NEW`
However, the [`ReturnValuesOnConditionCheckFailure`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/ConditionCheck.html#withReturnValuesOnConditionCheckFailure-com.amazonaws.services.dynamodbv2.model.ReturnValuesOnConditionCheckFailure-) only contains `NONE`, `ALL_OLD`. So I get why you are using the `String` signature on `Update`.

So I wanted to check if the produced `json` from alpakka was OK, and it is:
```json
{
  "TransactItems": [
    {
      "Update": {
        "Key": {
          "partition": {
            "S": "some-id"
          }
        },
        "UpdateExpression": "SET #v = :value",
        "TableName": "AnyOldTable",
        "ConditionExpression": "attribute_not_exists(#v)",
        "ExpressionAttributeNames": {
          "#v": "value"
        },
        "ExpressionAttributeValues": {
          ":value": {
            "S": "foo"
          }
        },
        "ReturnValuesOnConditionCheckFailure": "ALL_NEW"
      }
    }
  ],
  "ClientRequestToken": "08faf851-353d-41ed-b2a8-d79736e50b26"
}
```

However by checking the AWS CLI doc [here](https://docs.aws.amazon.com/cli/latest/reference/dynamodb/transact-write-items.html#options) to validate the json corectness, `ALL_NEW` is not stated as valid value.

Have you checked your code with `ALL_OLD` ?

**Comment by pulltab** [comment]
@RustedBones Let me prepare a canned example.    I am 9/10s sure that I used the `ALL_OLD` value originally and still received the 500 code previously, but a focused example will be useful here.

**Comment by pulltab** [comment]
@RustedBones See https://github.com/pulltab/alpakka-dynamodb-update-example

Sure enough, "ALL_OLD" does not result in a 500 code while "ALL_NEW" does.  So much for my 9/10s confidence. 

Thanks for all the help.

**Comment by pulltab** [comment]
Just closing the loop here as well, the Python client also returns a 500 when "ALL_NEW" is specified as the following script demonstrates:

```johnk@SEA-WL-15556:~$ more test.py
#!/usr/bin/python3
import boto3

client = boto3.client('dynamodb', endpoint_url="http://localhost:4569")

update = {
  "Key": {"partition": {"S": "foo"},"sort": {"S": "bar"}},
   "TableName": "foobar",
   "ConditionExpression": "attribute_not_exists(#v)",
   "UpdateExpression": "SET #v = if_not_exists(#v, :value)",
   "ExpressionAttributeNames": {"#v": "value"},
   "ExpressionAttributeValues": {":v" : {"S": "testing"}},
   "ReturnValuesOnConditionCheckFailure": "ALL_NEW"
}

response = client.transact_write_items(TransactItems=[{'Update': update}])

print(response)
```
