### ISSUE TITLE
Google Cloud Pub/Sub: refactor model from case classes

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1797]
### Short description

Some of the model classes in user facing API are still case classes. These should refactored to regular classes according to the conventions in the reference and other connectors to allow evolving them in a binary compatible way.

### Details

The following case classes should be refactored to regular classes:

https://github.com/akka/alpakka/blob/d29127099fdd96c002a160108e1a914a2d3e48b5/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala#L87

https://github.com/akka/alpakka/blob/d29127099fdd96c002a160108e1a914a2d3e48b5/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala#L109

https://github.com/akka/alpakka/blob/d29127099fdd96c002a160108e1a914a2d3e48b5/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala#L121

https://github.com/akka/alpakka/blob/d29127099fdd96c002a160108e1a914a2d3e48b5/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala#L123

Private classes should be moved to `impl` package:

https://github.com/akka/alpakka/blob/d29127099fdd96c002a160108e1a914a2d3e48b5/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala#L130

https://github.com/akka/alpakka/blob/d29127099fdd96c002a160108e1a914a2d3e48b5/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/model.scala#L132

**Comment by LGLO** [comment]
I volunteer for this one.
I'd like to use `PublishMessage` or `PublishPubSubMessage` (also change type inside `PublishRequest`) together.

**Comment by 2m** [comment]
`PublishMessage` sounds good, as there is `pubsub` in the package name already.

**Comment by ennru** [comment]
Now is a good time to suggest PRs to do this!

**Comment by LGLO** [comment]
I'll try to dig out my code for that in next 3 days

**Comment by LGLO** [comment]
https://github.com/akka/alpakka/pull/1881
I'll have to update docs as well.

**Comment by ennru** [comment]
Implemented with #1881.
