### ISSUE TITLE
1.1.0 incompatibility between google-pub-sub and google-storage

### ISSUE THREAD

**Issue by francisdb** [akka/alpakka#1811]
jwt-core dependency on google-pub-sub diverges from google-storage

### Versions used 

Alpakka `1.1.0`

We use both modules and have the following exceptions
###

```
java.lang.NoSuchMethodError: pdi.jwt.JwtTime$.nowSeconds()J
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleTokenApi.now(GoogleTokenApi.scala:26)
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleTokenApi.getAccessToken(GoogleTokenApi.scala:41)
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleSession.getNewToken(GoogleSession.scala:18)
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleSession.$anonfun$getToken$1(GoogleSession.scala:29)
```

jwt-core 3.x has some breaking changes where implicit Clock was added to time functions

All alpakka modules should depend on jwt-core 3.x (`JwtCoreVersion` in build.sbt), currently GooglePubSub and GoogleFcm still depend on 2.x

related?
https://github.com/akka/alpakka/blob/07443516b9fc7f3c0fdd5b582b6422b7a5cea3bd/build.sbt#L161

**Comment by francisdb** [comment]
Let me come up with a PR to fix this

**Comment by ennru** [comment]
Yes, they diverged as only the later version supports Scala 2.13 and included a version jump. That is why Alpakka Google Pub/sub is not published for Scala 2.13 yet.

**Comment by ennru** [comment]
See #1762 and #1763

**Comment by francisdb** [comment]
@ennru So what compatibility investigations need to be done?

**Comment by ennru** [comment]
I'm afraid your problem shows that the upgrade is not binary compatible. 
We've collected our rules about versioning in https://doc.akka.io/docs/alpakka/current/other-docs/versioning.html
So this will need to wait for Alpakka 2.0 as far as I can see. We intend to start merging 2.0 things by the end of July.

**Comment by francisdb** [comment]
@ennru any chance of doing milestone releases of Alpakka 2.0.0? Alpakka is the only thing remaining holding up our scala 2.13.x migration.

**Comment by ennru** [comment]
Yes, thank you for your interest, we will start doing that.
