### ISSUE TITLE
FTP connector - add toPath Sink

### ISSUE THREAD

**Issue by svezfaz** [akka/alpakka#182]
I would find it useful to have a `Ftp.toPath` sink - mirroring `Ftp.fromPath` source.

Has this been considered already? I would be happy to provide a PR if not.

**Comment by johanandren** [comment]
Sounds like a good idea to me.

**Comment by eharik** [comment]
Agreed on the proposal to add "modes".  In addition to "overwrite", "append", "create", and "safe overwrite" I would imagine we'd want something along the lines of "don't overwrite."  Not sure if appropriate behavior is to return a failed Future in the case where the file already exists?

A couple other options that might be useful would be "atomic" and "chmod".  I don't know the underlying libraries well enough to know if atomic writes are the default option, or potentially the *only* option.  But if not I could see a user wanting to ensure that the file is created atomically.  And a user may also want to set the file permissions of the file they are creating.

**Comment by johanandren** [comment]
Modes sounds like a good idea if the underlying FTP clients support it. I think "Don't overwrite" would be "create" and should fail if the file already exists. 

I think there is a level where you should just drop down to an imperative FTP client, we can and should not cover every thinkable use case for putting files on a FTP server.

**Comment by NicolaeNMV** [comment]
Will be really interested to start using the FTP sink. Does anybody know if there are any plans for the a new alpakka release ?

**Comment by johanandren** [comment]
Thanks for this one @svezfaz !
