### ISSUE TITLE
Allow JSON string in Elasticsearch Flow and Sink

### ISSUE THREAD

**Issue by djm1329** [akka/alpakka#1825]
### Short description

ElasticsearchFlow (and ElasticsearchSink) are missing a way to pass strings that already represent JSON docs. 

### Details

It appears the flow wants to convert whatever is flowing through to a string itself (using spray json). The use case I am thinking of is where the user of the connector already has a JSON string at hand (read from a file say, or obtained via some other means). Right now, AFAICT the user needs to pre-parse such a string to a JsValue and pass that, only to have the flow re-serialize to a string.

**Comment by 2m** [comment]
Hi @Douglas, this sounds good to me as additional API. Are you willing to work on a PR to implement this? :)

**Comment by djm1329** [comment]
Yes I can give it a shot, thanks!

Doug

**Comment by ennru** [comment]
I looked into the more and discovered it is already possible with the Scala DSL. So I added test cases and opened the Java API for it in #1862.

**Comment by ennru** [comment]
Fixed with #1862
