### ISSUE TITLE
AWS SQS: Asking for attributes fails with a 'UNKNOWN_TO_SDK_VERSION'

### ISSUE THREAD

**Issue by janjaali** [akka/alpakka#1838]
### Versions used 

Akka version: 2.5.23

### Expected Behavior

Setting attributes in the applied `SqsSourceSettings` for a `SqsSource` causes that retrieved messages have the set attributes.

### Actual Behavior

Setting attributes in the applied `SqsSourceSettings` for a `SqsSource` does not affect in retrieved attributes. Unless you set 'All' as attribute, that will retrieve all existing attributes. 

### Relevant logs

No.

### Reproducible Test Case

akka/alpakka#1839

**Comment by janjaali** [comment]
I just created an issue in the aws-sdk-java project for this strange signature https://github.com/aws/aws-sdk-java#2061

**Comment by ennru** [comment]
Fixed with a work-around in #1839
