### ISSUE TITLE
Dynamodb: Unable to Access TransactionCanceledException Contents

### ISSUE THREAD

**Issue by pulltab** [akka/alpakka#1847]
### Versions used 

Akka version:  1.0-M3

### Expected Behavior

When a [TransactionCanceledException ](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/TransactionCanceledException.html )is encountered that code is able to easily to detect (via case and/or other type assertions) and respond to the specific transaction cancellation reasons. 

### Actual Behavior

Alpakka-dynamodb is returning a generic AmazonDynamoDBException which cannot be `case`'d or otherwise converted into a TransactionCanceledException.  Users have to either parse raw response content themselves or parse strings to determine the exact reasons a transaction was cancelled. 

### Reproducible Test Case

See - https://github.com/pulltab/alpakka-dynamodb-update-example

The following snippet illustrates the issue:

```
  def main(args: Array[String]) = {
    val table = "foobar"

    println(s"Ensuring table $table exists...")
    ensure_table(table)
      .onComplete {
        _ => Done
      }

    val update =
      new TransactWriteItem()
        .withUpdate(
          new Update()
            .withTableName(table)
            .withKey(
              Map(
                "partition" -> new AttributeValue().withS("foo"),
                "sort" -> new AttributeValue().withS("bar")) asJava)
            .withExpressionAttributeNames(Map("#v" -> "value") asJava)
            .withExpressionAttributeValues(Map(":v" -> new AttributeValue().withS("test")) asJava)
            .withConditionExpression("attribute_exists(#v)") //This condition is expected to fail
            .withUpdateExpression("SET #v = :v")

    val request = new TransactWriteItemsRequest().withTransactItems(List(update) asJava)

    DynamoDb
      .single(request)
      .map {
        result => println(s"Result: $result")
      }
      .recover {
        case oops: AmazonDynamoDBException =>
          if( oops.isInstanceOf[TransactionCanceledException] ){
            // This branch is not reached, but expected to.
            println("TransactionCanceled!")
          } else if( oops.getErrorCode() == "TransactionCanceledException") {
            // This branch is reachable, however, one is unable
            // to easily access cancellation reasons.
            //
            // Note - The raw response object contains the expected type,
            // the type returned by alpakka is a generic AmazonDynamoDBException.
            println(s" RAW: ${oops.getRawResponseContent()}")i
          } else {
            println(s"Unhandled Exception - $oops")
          }
      }
      .onComplete {
        _ => System.exit(0)
      }
```

**Comment by ennru** [comment]
Thank you for reporting this problem. Would you be up to suggest an improvement in a Pull Request?

**Comment by pulltab** [comment]
@ennru Happy to make an attempt.

As I am new to this code base, can someone point out a few places of interest for me to begin investigating?

**Comment by pulltab** [comment]
Turned out to be pretty trivial.  See above, @ennru.
