### ISSUE TITLE
JMS: txSource should report rollbacks

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1855]
### Short description

When a JMS transactional message is rolled back, this should be inspectable by the user at least via log messages with a hint to the `ack-timeout` setting.

Possibly, the users should be able to let the stream fail if the ACK timeout is hit and a message is rolled back.
 
### Details

The current `JMS.txSource` automatically calls rollback when the `ack-timeout` (default 1 s) is hit, but this can't be noticed by the consumer.

https://github.com/akka/alpakka/blob/85f65b132852ba2a347228cedb311828f1c8c3a6/jms/src/main/scala/akka/stream/alpakka/jms/impl/JmsTxSourceStage.scala#L53-L58

See https://github.com/akka/alpakka/pull/1831

**Comment by WellingR** [comment]
Actually,  just a log message may not be enough. I would rather see that the commit (and maybe also rollback) methods on the `TxEvenlope` would throw an exception to make it clear that the message was already rolled back.

**Comment by ennru** [comment]
Yes, that makes sense and would be expected. Changing it would break backwards compatibility for code that handles duplicated messages correctly today, though.

**Comment by WellingR** [comment]
Perhaps an alternative could be for the commit/rollback method to return a future which completes when the commit/rollback has actually been handled

**Comment by ennru** [comment]
In #1857 I suggest a backwards-compatible way to improve this.
For Alpakka 2.0 we could look into further improvements.

**Comment by ennru** [comment]
Improved with #1857.
