### ISSUE TITLE
JmsMessage withProperties needs Java API

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1900]
### Expected Behavior

JmsMessage.withProperties needs a Java API that takes `java.util.Map`.

### Actual Behavior

Currently JmsMessage.withProperties takes only a Scala immutable.Map:

https://github.com/akka/alpakka/blob/99fd53dc4eb1e48882e931b4a0dbc85a1629cb24/jms/src/main/scala/akka/stream/alpakka/jms/JmsMessages.scala#L84

**Comment by ennru** [comment]
Implemented with #1904.
