### ISSUE TITLE
Unable to initiate the rabbit ConnectionFactory with default value for SSL protocol

### ISSUE THREAD

**Issue by Dnomyar** [akka/alpakka#1901]
Hey lads,

### Versions used 

Akka version: `"com.lightbend.akka" %% "akka-stream-alpakka-amqp" % "1.1.1"` 

### Expected Behavior
Being able to call `factory.useSslProtocol()` with the default value: without having to specify any protocol. 

### Actual Behavior
As far as I can tell, for the moment, the line 139 is not reachable :

https://github.com/akka/alpakka/blob/99fd53dc4eb1e48882e931b4a0dbc85a1629cb24/amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala#L131-L141

because either one of `protocol` and `context` won't be `None` given the constructor of the class `AmqpConnectionProvider` is private and the apply methods below :

https://github.com/akka/alpakka/blob/99fd53dc4eb1e48882e931b4a0dbc85a1629cb24/amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnectionProvider.scala#L267-L272

### Relevant logs
N/A

### Reproducible Test Case
N/A
    
### Workaround
As a workaround, you can create `AmqpSSLConfiguration`, using the default parameters found in the java rabbit library : 
```
.withSSLConfiguration(
AmqpSSLConfiguration(ConnectionFactory.computeDefaultTlsProcotol(SSLContext.getDefault.getSupportedSSLParameters.getProtocols))
)
```

### Possible solution
A possible solution would be add another `apply` without any parameter so that the object `AmqpSSLConfiguration` is created with only None values. This would allow the line `factory.useSslProtocol()` to be reachable.

```
def apply(): AmqpSSLConfiguration = new AmqpSSLConfiguration()
```

I am happy to give it a try and create a PR

Cheers

**Comment by 2m** [comment]
Great catch. Yes, a factory method without parameters sounds good!
