### ISSUE TITLE
AMQP: Provide full configuration of the ConnectionFactory

### ISSUE THREAD

**Issue by avandendaele** [akka/alpakka#191]
Currently, the `AmqpConnector` only supports `setUri`, `setHost`, `setPort`, `setUsername`, `setPassword`, `setVirtualHost` and `useSslProtocol` to configure the  `ConnectionFactory`.
I would like to be able to configure all settings of the `ConnectionFactory` such as `setRequestedHeartbeat `, `setConnectionTimeout `, `setHandshakeTimeout`, `setShutdownTimeout `, `setNetworkRecoveryInterval `, `setAutomaticRecoveryEnabled `, `setTopologyRecoveryEnabled ` and `setExceptionHandler`.

**Comment by johanandren** [comment]
Sounds like a relatively simple change, up for making a PR adding those to the connection DSL?

**Comment by avandendaele** [comment]
@johanandren Yes it is. I'll make a PR as soon as I have time to.

**Comment by johanandren** [comment]
Awesome!

**Comment by matsluni** [comment]
There is also a method called newConnection, which takes an Address or a list of addresses. I think it would also be a good addition to support those, e.g. to list all cluster nodes.

**Comment by avandendaele** [comment]
@johanandren Any naming convention or preference about the variable pattern [here](https://github.com/akka/alpakka/blob/master/amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnector.scala#L18) ? I mean with or without `maybe` prefix ?

**Comment by johanandren** [comment]
I'd skip the `maybe`, the type makes it obvious, but it doesn't matter much with a small local scope IMO.

**Comment by matsluni** [comment]
I could also help out on this. Let me know if this helps.
