### ISSUE TITLE
S3: Implement Get List Bucket call

### ISSUE THREAD

**Issue by jotsif** [akka/alpakka#192]
As an Alpakka S3 user I would like to use Alpakka for listing the contents of S3 buckets, so that I can see what is there before I decide what to download.

**Comment by Scalahansolo** [comment]
Myself and a couple of co-workers have a forked version that does exactly this. https://github.com/andrewrapp/alpakka/blob/master/s3/src/main/scala/akka/stream/alpakka/s3/scaladsl/S3Client.scala

Reason for not merging this back in - Akka Http does not have proxy support currently which is a blocker for us, so we have a our version until that exists. 

There is an open ticket to get proxy support, but it just doesn't seem like its a priority to get done currently. https://github.com/akka/akka-http/pull/583

**Comment by johanandren** [comment]
Free for picking up as PR #193 was closed.

**Comment by francisdb** [comment]
Listing bucket contents is currently available including object metadata (#347). Please close.

**Comment by ennru** [comment]
As @francisdb stated in July, this is supported nowadays.
