### ISSUE TITLE
PubSub Http acknowledge failures are siliently discarded

### ISSUE THREAD

**Issue by LGLO** [akka/alpakka#1929]
### Versions used 

Akka version: 2.5.23
Alpakka version: 1.1.1

### Expected Behavior

`acknowledge` sink output `Future[Done]` fails when HTTP request result code is other than 200.
This test should pass: https://github.com/LGLO/alpakka/blob/acknowledge-silent-failure/google-cloud-pub-sub/src/test/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApiSpec.scala#L233-L252

### Actual Behavior

When `acknowledge` result code is other than 200, there is exception created but not thrown. Unit value `()` is returned and `Future` succeeds.
IMO there is missing `throw` here: 
https://github.com/akka/alpakka/blob/master/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala#L164

**Comment by ennru** [comment]
Thank you for suggesting an improvement in #1928

**Comment by LGLO** [comment]
Can we close it now?

**Comment by ennru** [comment]
Yes, thank you for the ping.
Fixed with #1928
