### ISSUE TITLE
Cassandra: not consuming the entire resultset in all cases

### ISSUE THREAD

**Issue by anzecesar** [akka/alpakka#1934]
### Versions used 

Alpakka 1.1.1

Akka version: 2.5.25

### Expected Behavior

When using `setFetchSize`, the source should always load all pages

### Actual Behavior

Under certain conditions, which I find hard to reproduce, it seems like the source completes just after loading a few pages of results. Looks like that happens when the page size is small and downstream consumer is fast.

In my tests I needed to have a small page size due to larger response size.

I'll open a PR with a fix

**Comment by ennru** [comment]
Fixed with #1935
