### ISSUE TITLE
S3: Enable X-Ray tracing

### ISSUE THREAD

**Issue by vigoo** [akka/alpakka#1938]
### Short description

I'm currently working on enabling AWS X-Ray tracing of our services using Akka-HTTP and Alpakka. With the current Alpakka S3 API this is not possible as it requires injecting a new header into all requests, and also capturing at least the request ID from the response headers.

### Details
To trace S3 calls the following steps would be necessary:
- Needs some operation-specific metadata before sending the request, such as bucket name and key. This is not a problem currently as the existing API can be wrapped to capture this information.
- An `X-Amzn-Trace-Id` header has to be injected to _all_ requests to S3 (its value is generated by the X-Ray implementation outside the scope of the Alpakka S3 lib). This is currently only possible in `multipartUploadWithHeaders` not for the other operations.
- Needs to capture some information from the response such as the request ID, content length (coming as a header), and status code.

To enable injecting the header I would add an `S3Headers` parameter to _all_ public operations on the `S3` object, defaulting to an empty set of headers. 
I'm not so sure about extracting things from the response though as we should not break the current quite clean API with these unnecessary metadata. Maybe all methods could have an "advanced" version annotating the return value with these elements?

I would be happy to implement this and send in a PR if we can agree on how it should work.

**Comment by jypma** [comment]
Other solutions like [kamon's jaeger tracing](https://github.com/kamon-io/kamon-jaeger) use AOP techniques for this ([kanela](https://github.com/kamon-io/kamon-akka-http/blob/master/kamon-akka-http/src/main/scala-2.12/kamon/instrumentation/akka/http/AkkaHttpServerInstrumentation.scala#L29) in their case, AspectJ would do as well).

Using AOP has the advantage that you shield the "unnecessary metadata", as you rightly say, from ordinary API callers that have no interest in the tracing. It's a cross-cutting concern, after all. Additionally, using AOP would allow you to add it to _all_ `akka-http` calls, if so desired.

The downside of AOP of course is, that it's AOP :)

**Comment by ennru** [comment]
Thank you for this suggestion.
I agree with @jypma that tracing should be as little intrusive to the normal use case as possible. If we can come up with a solution that doesn't affect other users, that would good. Duplicating the API is not an option.

**Comment by vigoo** [comment]
I agree with trying to be as little intrusive as possible. My problem with the AOP solutions like the one linked above, beside being AOP is that it relies on accessing the "current trace" stored in a thread-local variable which I want to avoid. The library I'm working on constructs the tracing context in an akka-http directive which is then passed around and used wherever it is needed (custom subsegments, downstream akka-http calls, slick, dynamodb, and hopefully s3).

I was playing a bit with the library to help discussing this idea, here is a commit (not pull-request ready):
https://github.com/vigoo/alpakka/commit/57fc646b8bc23b7443a28228aabfa2e3a50cf5f1

What this does is it adds the possibility to pass any custom headers to any of the operations implemented by `S3Stream`. I feel like this part of the change even makes the code a bit more consistent. The question then is how to expose this on the API, and for this in this commit I created a "copy" of the `S3` factory object to keep binary compatibility. (If breaking the binary compatibility is not a requirement then of course it could be changed on the existing API but I guess this is not an option).

If we could add this ability of passing in custom headers to all operations, it would enable me creating a X-ray tracing wrapper around it. Metadata like operation name, bucket etc. could be filled on construction time from the wrapper then would then generate the tracing header and pass it to Alpakka, and closing the tracing segment and figuring out the status code is possible by capturing `S3Exception`. Tracing the content length is optional and we could live without it :) 

What do you think?

**Comment by ennru** [comment]
You are right, adding `headers` to all methods as an overload is a good idea as it becomes more consistent.

**Comment by vigoo** [comment]
Then I will create a proper pull request from this and we can discuss the further details there.

**Comment by francisdb** [comment]
Related PR is merged, this can be closed

**Comment by ennru** [comment]
With the merged support to provide headers to all methods, X-Ray tracing should be possible now.
(Thank you for the ping)
