### ISSUE TITLE
S3: Alpakka should allow un-prefixed headers

### ISSUE THREAD

**Issue by jurisk** [akka/alpakka#194]
I'd like to set a `Content-Encoding: gzip` header, however `buildHeaders` in ` HttpRequests` is prefixing the `MetaHeaders` with a `x-amz-meta-` prefix, therefore it is not possible.

It would be useful if un-prefixed headers would also be available.

I could contribute a pull request, but we should agree on the API - are we passing another map of `rawHeaders` in to `initiateMultipartUploadRequest` and further methods which would not get prefixed, or should we add a `contentEncoding` parameter instead.

**Comment by francisdb** [comment]
I would mimic the official client. How do you set it there? (also check their new async client)

**Comment by francisdb** [comment]
This can be closed as it is available in `S3Headers(headers: Seq[HttpHeader])`

**Comment by ennru** [comment]
Thank you for pointing this out.
