### ISSUE TITLE
XML: uptake aalto-xml version 1.2.2 for thread-safety fix

### ISSUE THREAD

**Issue by jphelp32** [akka/alpakka#1944]
### Short description

Uptake aalto-xml version 1.2.2.
https://github.com/FasterXML/aalto-xml/blob/master/release-notes/VERSION

### Details

aalto-xml 1.2.2 fixes a thread-safety issue where its internal buffers may be corrupted when there are multiple concurrently processing materializations of XmlParser/XmlWriter w/in the same akka stream.

**Comment by ennru** [comment]
Yes, now that we are approaching Alpakka 2.0 would be a good time for this upgrade. Can you create a PR for it?

**Comment by jphelp32** [comment]
pull request #1948 created

**Comment by ennru** [comment]
Fixed with #1948
