### ISSUE TITLE
S3 max chunk size limit unnecessary?

### ISSUE THREAD

**Issue by bpiper** [akka/alpakka#1955]
### Versions used 

Alpakka: 1.1.0
Akka: 2.5.23

### Expected Behavior

When performing a multipart S3 upload with Alpakka, one should be able to use chunks up to (Integer.MAX_VALUE / 2) in size if sufficient memory/disk is provisioned for chunk buffering.

### Actual Behavior

Chunk size is restricted to < 10 MB by the SplitAfterSize sub-flow.

This behaviour was introduced by the fix for https://github.com/akka/alpakka/issues/980.  The PR implies that the maximum part size that can be uploaded to S3 is 10 MB, which is incorrect.  S3 allows part sizes up to 5 GB in size (provided the total is <= 5 TB).  The responsibility is on the user to ensure that they have sufficient memory or disk space (depending on which buffer type is used) to accommodate whatever chunk size is specified.

In a previous version of Alpakka (1.0-RC1), we've been using a 20 MB chunk size (memory-buffered) without issue.

A 10 MB chunk size effectively limits the maximum file size to 100 GB, and some of the files we deal with are bigger than that (though < 200 GB), so this is preventing us from upgrading.

It seems to me that `minChunkSize` in `SplitAfterSize` is a misnomer, and should always have been `maxChunkSize`, i.e. the upper limit (the lower limit already having been validated in `S3Stream.createRequests`) at which we should emit the remaining `count - maxChunkSize` bytes and then emit whatever remains to a new stream.  I think what the code in 1.0-RC1 was missing was simply that handling of the case where `elem` is greater than the max chunk size and therefore needs to be recursively chopped up instead of just emitting it.  I think the additional arbitrary size limit was unnecessary.

**Comment by bpiper** [comment]
Upon making some changes and running the unit test, I realised that `SplitAfterSize` isn't trying to maintain a consistent part/chunk size (I guess for performance reasons), so having a min and max chunk size does make sense, but I think the issue is just that the max should be restricted to the smaller of `chunkSize * 2` and `Integer.MAX_VALUE` instead of 10 MB.

**Comment by ennru** [comment]
It would require to increase the chunk buffer accordingly so it doesn't overflow. But that buffer should be configurable and not default to `(Integer.MAX_VALUE / 2)`, I guess.

**Comment by bpiper** [comment]
Given the chunk buffer is currently sized at `chunkSize * 2` (a.k.a. `minChunkSize * 2`), that can probably remain proportionately fixed, so long as it's ensured that the max chunk size is no bigger than that (i.e. it could just be set to that value - probably no need for it to be configurable).  I only mentioned `Integer.MAX_VALUE / 2` because currently if you do configure chunk size to be any larger than that then you'll get an error since all that stuff uses `Int`.  Possibly `Long` should be used instead, unless the intent is to avoid issues with 32-bit filesystems or memory addressing.

**Comment by ennru** [comment]
Fixed with #1979
