### ISSUE TITLE
Multiple Kafka producer network threads created

### ISSUE THREAD

**Issue by kolapkardhaval** [akka/alpakka#1956]
I am running alpakka kafka producer in akka stream and multiple producer processes are getting run:

"kafka-producer-network-thread | producer-20" #49 daemon prio=5 os_prio=31 tid=0x00007f80562c1800 nid=0x8903 runnable [0x000070000e3f9000]

I am using singleton and not creating multiple kafka producers instances but still seeing 10k kafka-producer-network-thread created.

**Comment by seglo** [comment]
@kolapkardhaval Can you create log this issue in https://github.com/akka/alpakka-kafka?  To address the question though, these network threads are created by the `KafkaProducer` internally.

**Comment by kolapkardhaval** [comment]
Thanks @seglo I have created this issue in alpakka kafka https://github.com/akka/alpakka-kafka/issues/920 . We could discuss there but seems like this is causing our server cpu to go to 99 %

**Comment by ennru** [comment]
Moved to Alpakka Kafka.
