### ISSUE TITLE
MQTT: Cannot customize MqttCallback

### ISSUE THREAD

**Issue by tdroxler** [akka/alpakka#196]
Hi everyone,

I don't see how we can modify the [`MqttCallback`](https://github.com/akka/alpakka/blob/master/mqtt/src/main/scala/akka/stream/alpakka/mqtt/Mqtt.scala#L146) is there a way or what would be the best way to add this feature? 

thx

edit: maybe if we could create a `Source` from a `MqttAsyncClient` this would give the freedom to configure more in depth the client. Because I don't see either a way to add some `MqttConnectOptions` like a ssl cert.

**Comment by mwegrz** [comment]
@tdroxler please give some more info your use case that needs an extension of `MqttCallback`.

**Comment by tdroxler** [comment]
sorry after digging more into MQTT I realize I didn't need to modify `MqttCallback`, my bad. 

Closing the issue
