### ISSUE TITLE
[Failure] ArchiveSpec, should archive file

### ISSUE THREAD

**Issue by seglo** [akka/alpakka#1989]
Failure from PR #1981 build

https://travis-ci.com/akka/alpakka/jobs/244115447#L756

**Comment by seglo** [comment]
https://travis-ci.com/akka/alpakka/jobs/260670103#L519

**Comment by seglo** [comment]
https://travis-ci.com/akka/alpakka/jobs/261114508#L367

**Comment by seglo** [comment]
https://travis-ci.com/akka/alpakka/jobs/275777719#L370

**Comment by ennru** [comment]
Most likely fixed with #2105.
