### ISSUE TITLE
Alpakka PubSub gRPC connector does not work as expected

### ISSUE THREAD

**Issue by alessandrolumino** [akka/alpakka#1992]
Hi guys.. I am trying to produce messages to a Pub/Sub topic.
The following steps have been performed:

1.  The topic has been created
2. A subscription for that topic has been created.
3. A service account with Publisher and Subscriber roles has been created
4. The json key associated has been generated.
5. I have set the env variable GOOGLE_APPLICATION_CREDENTIALS with the location of the key
6. The application runs smoothly but no messages can be seen on PubSub

I don't know where the problem is.

Can you help me?

**Comment by ennru** [comment]
Have you seen the certificate problems described in #1878?

**Comment by ennru** [comment]
No further replies. I'll close this.
