### ISSUE TITLE
Alpakka PubSub for Scala 2.13

### ISSUE THREAD

**Issue by btomala** [akka/alpakka#1994]
I asked this question here https://discuss.lightbend.com/t/alpakka-pubsub-for-scala-2-13/5226 but didn't get any response there in 18 days. So I'm asking it again here.

I found that `akka-stream-alpakka-google-cloud-pub-sub` is not released for 2.13 any more. There is no 1.1.x version for scala 2.13 in maven 3. Previous version 1.0.x has support for milestone version of 2.13.

I found that release note for 1.1.x 2 said that Versions for Scala 2.13.0 is released.

How can we fix this? Or where I can find it if it is not released to central maven repository?

**Comment by ennru** [comment]
Answered on the forum.

**Comment by francisdb** [comment]
@btomala 2.0.0-M1 [has been released containing the pub-sub module for 2.13]( https://repo1.maven.org/maven2/com/lightbend/akka/akka-stream-alpakka-google-cloud-pub-sub_2.13/2.0.0-M1/)

**Comment by btomala** [comment]
Thanks!
