### ISSUE TITLE
IronMQ connector

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#2]
Continued from https://github.com/akka/akka-stream-contrib/issues/57

**Comment by patriknw** [comment]
@filosganga This looks interesting. PR is welcome.

**Comment by filosganga** [comment]
@patriknw I will do that hopefully today. Should I open a PR on s3-stream or rather here?

**Comment by filosganga** [comment]
Never mind bad thread

**Comment by filosganga** [comment]
I have started to integrate my ironmq.rx in alpakka. For testing, as you are using docker, I am looking at this:
http://dev.iron.io/mq/3/on-premise/installation/single.html

More news coming.

**Comment by 2m** [comment]
Fixed in #110
