### ISSUE TITLE
Issues connecting when using custom SSH client

### ISSUE THREAD

**Issue by varbues** [akka/alpakka#2007]
I'm having some issues while trying to create new instances of the SftpApi with a custom SSH client as described in the [documentation](https://doc.akka.io/docs/alpakka/current/ftp.html#configuring-the-connection-settings).
```
import akka.stream.alpakka.ftp.scaladsl.{Sftp, SftpApi}
import net.schmizz.sshj.{DefaultConfig, SSHClient}

val sshClient: SSHClient = new SSHClient(new DefaultConfig)
val configuredClient: SftpApi = Sftp(sshClient)
```

### Versions used 

Alpakka version: 1.1.1
Akka version: 2.5.23

### Expected Behavior

When using the `Sftp` object, there is no issues at all.

### Actual Behavior

When using the `configuredClient`,  we get these two errors:

```
Caused by: net.schmizz.sshj.transport.TransportException: Server closed connection during identification exchange
```

```
java.lang.IllegalThreadStateException: null
	at java.lang.Thread.start(Thread.java:708)
	at net.schmizz.sshj.transport.TransportImpl.init(TransportImpl.java:184)
```

Is worth mentioning that the idea behind is to have more than one `Sftp` instance. We got several data pipelines running on a container and having one shared `Sftp` makes our stream apps quite slow (we solve this by having less pipelines per app, but that's not ideal).

The question here is, can we get around these errors?

**Comment by ennru** [comment]
Could you try [Alpakka 2.0.0-M1](https://doc.akka.io/docs/alpakka/2.0/)? It contains updates of the client libraries.

**Comment by DanieleSassoli** [comment]
@ennru I believe this issue can be closed, worked on this with @varbues(which has since come off the project) and this has been fixed.
