### ISSUE TITLE
AWS S3 List only one hierarchy level of objects by using the delimiter parameter

### ISSUE THREAD

**Issue by an-tex** [akka/alpakka#2021]
### Short description

By using the [delimiter parameter](https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingKeysHierarchy.html) it is possible to list the common prefixes of only one hierarchical level.

### Details

In the current implementation only the prefix can be set. To allow browsing level by level it should be possible to set the delimiter parameter as well. See: [S3 API Documentation](https://docs.amazonaws.cn/en_us/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax)

I have already started working on a PullRequest and will add it shortly.

**Comment by seglo** [comment]
Good idea.  Looking forward to the PR!

**Comment by seglo** [comment]
Implemented in #2023
