### ISSUE TITLE
Alpakka fails to import as new project into IntelliJ

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#2028]
### Versions used 

IntelliJ IDEA: 2019.2.4
Scala plugin: 2019.2.37

### Expected Behavior

IntelliJ imports the Alpakka project from the sbt build configuration including all its (sub)projects.

### Actual Behavior

A fresh import of the Alpakka project does not show any of its modules in IntelliJ and can't be used for development.
I suspect IntelliJ's translation from the sbt project structure to its internal representation can't handle the projects `csvBench`, `mqttStreamingBench`, `docs`, `whitesourceSupported` which don't relate to the root project `alpakka`.

When I remove those from the sbt build description the project import works nicely, which I tried in https://github.com/ennru/alpakka/tree/import-build

https://github.com/akka/alpakka/compare/master...ennru:import-build

**Comment by huntc** [comment]
For me, I recall if I disabled ‘docs’ then I could move forward.

**Comment by ennru** [comment]
Thank you, that minimised the search space...

**Comment by ennru** [comment]
Yes, commenting out the `docs` project is enough to make IntelliJ import it correctly.
Once imported that commenting can be removed and reloading works, but `docs` doesn't become a module (which does not matter).

**Comment by ennru** [comment]
But the IntelliJ sbt import complains about versions that are not found:
```
:: com.lightbend.akka#akka-stream-alpakka-file_2.12;2.0.0-M1+8-40e91a32+20191127-1421: not found
:: com.lightbend.akka#akka-stream-alpakka-mqtt_2.12;2.0.0-M1+8-40e91a32+20191127-1421: not found
:: com.lightbend.akka#akka-stream-alpakka-ftp_2.12;2.0.0-				M1+8-40e91a32+20191127-1421: not found
```
