### ISSUE TITLE
How to tear down S3 streams correctly?

### ISSUE THREAD

**Issue by aquamatthias** [akka/alpakka#203]
I use the alpakka S3 extension (0.6) to download a file from s3.
How do I teardown the stream correctly?

Example:
```scala
  def main(args: Array[String]): Unit = {
    implicit val system = ActorSystem("Test")
    implicit val materializer = ActorMaterializer()
    try {
      val result = new S3Client(AWSCredentials("access", "secret"), "eu-central-1").download("bucket", "test.txt").map(_.utf8String).runWith(Sink.last)
      val string = Await.result(result, Duration.Inf)
      logger.info(s"Action complete. Got $string")
    } catch {
      case NonFatal(ex) => logger.error(s"Error: ${ex.getMessage}", ex)
    } finally {
      Await.result(Http().shutdownAllConnectionPools(), Duration.Inf)
      materializer.shutdown()
      system.terminate()
    }
  }
```

I get this output:
```
INFO  Action complete. Got Hello World
ERROR Outgoing request stream error (akka.actor.ActorSystemImpl:Backup-akka.actor.default-dispatcher-4)
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://Test/user/StreamSupervisor-1/flow-2-0-unknown-operation#-1527921734]] terminated abruptly
```

**Comment by johanandren** [comment]
The S3 client uses Akka HTTP for talking to S3 and HTTP keeps connection pools, I think this may be because of that. What happens if you do a `Http().shutdownAllConnectionPools()` and wait for the returned future before you shutdown the materializer?

**Comment by aquamatthias** [comment]
@johanandren I already tried this (updated my description). I see the same result.

**Comment by timcharper** [comment]
There is a known issue with Akka HTTP: https://github.com/akka/akka-http/issues/907

In short, `Http().shutdownAllConnectionPools()` does not work if you use any SSL connections, which the S3Client definitely depends on.

The error message is relatively harmless, except that it could make your application appear broken.

**Comment by timcharper** [comment]
The following Scala Script can be run to reproduce the issue:

https://gist.github.com/timcharper/dc8e5b8b9a790852394d0fb78f2c016c

**Comment by johanandren** [comment]
Since the issue is actually in Akka HTTP I think we can close this one?

**Comment by aquamatthias** [comment]
Thanks for investigation!
