### ISSUE TITLE
AWS Kinesis: add support for enhanced fan-out

### ISSUE THREAD

**Issue by regiskuckaertz** [akka/alpakka#2037]
### Short description

From the [documentation](https://docs.aws.amazon.com/streams/latest/dev/introduction-to-enhanced-consumers.html)

> This feature enables consumers to receive records from a stream with throughput of up to 2 MiB of data per second per shard

### Details

As an alternative to the current poll-based mechanism, this one has Kinesis pushing records over an HTTP2 pipeline, speeding up message propagation. Enhanced fan-out also guarantees throughput per shard no matter how many consumers, i.e. goodbye to throughput exceeded exceptions. [Details](https://docs.aws.amazon.com/streams/latest/dev/building-consumers.html)

**Comment by YikSanChan** [comment]
@aserrallerios I am not familiar with this, do you mind confirming enhanced fan-out is not covered by your contribution to alpakka-kinesis? Thanks

**Comment by aserrallerios** [comment]
From the documentation:

> The following diagram shows the enhanced fan-out architecture. If you use version 2.0 or later of the Amazon Kinesis Client Library (KCL) to build a consumer, the KCL sets up the consumer to use enhanced fan-out to receive data from all the shards of the stream

https://docs.aws.amazon.com/streams/latest/dev/enhanced-consumers.html

Alpakka has KCL support since 2.0, so I think we're covered on that regard.

**Comment by YikSanChan** [comment]
@regiskuckaertz Shall we close?

**Comment by regiskuckaertz** [comment]
@YikSanChan yes, great stuff !
