### ISSUE TITLE
Incorrect handling of "ETag" in S3 multi-part upload and copy

### ISSUE THREAD

**Issue by sfali** [akka/alpakka#2060]
### Versions used 

Akka version:  2.6.1

### Expected Behavior
`multiPartCopy` is not working because of incorrect handling of etag`.

### Actual Behavior

Both `multiPartUpload` and `multiPartCopy` should work.

### Relevant logs

As per documentation of S3 API the value of `ETag` always wrapped in double quotations, either in the header or as part of a request or response XML.
In the `chunkAndRequest` function of `S3Stream` at line 671 `etag` is retrieved as follows:
`val etag = r.headers.find(_.lowercaseName() == "etag").map(_.value)`
This `etag` value should have been wrapped in double quotation but double quotaions never got removed in:
`Future.successful(SuccessfulUploadPart(upload, index, t)`
The code should have been:
 `Future.successful(SuccessfulUploadPart(upload, index, t.drop(1).dropRight(1)))`.

Fortunately `multipartUpload` would work becuase complete request would be constructed in `completeMultipartUploadRequest` function of `HttpRequests` as follows:
```
val payload = <CompleteMultipartUpload>
                    {
                      parts.map { case (partNumber, etag) => <Part><PartNumber>{ partNumber }</PartNumber><ETag>{ etag }</ETag></Part> }
                    }
                  </CompleteMultipartUpload>
```

As per S3 documentation, the `ETag` element should have been wrapped in `"` since the quotations were never removed when reading from header the `multipartUpload` would work, but unfortunately `multipartCopy` would fail because of missing quotations.

A solution to this would be:

- Add quotations in the payload
```
val payload = <CompleteMultipartUpload>
                    {
                      parts.map { case (partNumber, etag) => <Part><PartNumber>{ partNumber }</PartNumber><ETag>"{ etag }"</ETag></Part> }
                    }
                  </CompleteMultipartUpload>
```
- Remove quotations when reading from header
 `Future.successful(SuccessfulUploadPart(upload, index, t.drop(1).dropRight(1)))`.

### Reproducible Test Case

I would provide a PR to fix this.

If the issue is more complex or requires configuration, please provide a link to a project that reproduces the issue.

**Comment by ennru** [comment]
Hi @sfali 
Did you get to put a fix together? Would be great.

**Comment by sfali** [comment]
@ennru 

There is something going on, I am trying to test against AWS.

**Comment by sfali** [comment]
Sorry for delayed response.

AWS accepts requests both with and without quotations in ETAG, hence this is not an issue.

I am not sure how I got the error, I'll try to figure out in my side.

This issue can be closed.

Regards,

Syed

**Comment by ennru** [comment]
That is good new, I think.
Thank you for digging into it!
