### ISSUE TITLE
Quotes around apidoc links

### ISSUE THREAD

**Issue by johanandren** [akka/alpakka#2068]
Noticed here: https://doc.akka.io/docs/alpakka/current/mongodb.html

<img width="564" alt="Screenshot 2020-01-03 at 08 54 05" src="https://user-images.githubusercontent.com/666915/71712687-9acc8e80-2e06-11ea-9f86-9d488709873b.png">

**Comment by seglo** [comment]
Thanks.  Enno updated apidocs to automatically add the fixed width formatting for apidoc links.

**Comment by seglo** [comment]
This will be resolved once Alpakka 2.0.0 is released and `/current/` points to it.  You can see the updated docs from the last milestone here: https://doc.akka.io/docs/alpakka/2.0.0-M2/mongodb.html
