### ISSUE TITLE
GCS file downloads are limited to 8 MB

### ISSUE THREAD

**Issue by gabrielreid** [akka/alpakka#2084]
### Versions used 

2.0.0-M2

Akka version: 2.6.0

### Expected Behavior

It should be possible to download files of any size from Google Cloud Storage, limited only by local resources. 

### Actual Behavior

Attempting to download any file larger than 8 MB from GCS fails with ```Outgoing request stream error
EntityStreamSizeException: incoming entity size (while streaming) exceeded size limit```

This can be worked around by setting the `akka.http.client.parsing.max-content-length` config setting to an arbitrarily large value.

akka/alpakka#2069 was intended to resolve this issue, but instead it only resolved it for rewriting files, and not for downloads.

**Comment by ennru** [comment]
Fixed with #2085
