### ISSUE TITLE
MQTT Streaming does not work with Akka 2.6.1 due to an internal api change from Akka 2.6.0 to Akka 2.6.1

### ISSUE THREAD

**Issue by jcroig** [akka/alpakka#2088]
### Versions used 

Master HEAD

Akka version: 

2.6.1

### Expected Behavior

Alpakka MQTT streaming should work with Akka 2.6.1

### Actual Behavior

Alpakka MQTT fails to compile with Akka 2.6.1 or it fails to start a MQTT server if used along with Akka 2.6.1

### Reproducible Test Case

Just try to build the project with Akka 2.6.1 dependency and it won't compile.

**Comment by jcroig** [comment]
Fixed in https://github.com/akka/alpakka/pull/2087

**Comment by ennru** [comment]
Fixed with #2087
