### ISSUE TITLE
S3: Cannot delete files ending with "/" in the name

### ISSUE THREAD

**Issue by dl-mai** [akka/alpakka#2089]
Hello there,
I stumbled across an issue where i cannot delete S3 files when the last character for the key is a slash. Those files occur if you for example want to create a folder like structure in S3 which basically creates an slash file with zero bytes.

After some investigation I found in the akka.stream.alpakka.s3.impl.HttpRequests file and requestUri method the key is split by the slash. 
The result is a missing slash in the request uri. Is there something I'm missing or is it maybe a bug?

Kind regards

**Comment by ennru** [comment]
Thanks for reporting. We can consider it a bug.
Would you be in a position to suggest necessary changes in a Pull Request?

**Comment by dl-mai** [comment]
Hello and thanks for the reply,
I need to figure out how to actually create a pull request on github.
My suggestion would be passing `limit=-1` to the `split` method call to include trailing empty strings/path.

**Comment by ennru** [comment]
Fixed with #2095
