### ISSUE TITLE
Separated dsl projects for scala and java.

### ISSUE THREAD

**Issue by psycho-ir** [akka/alpakka#209]
Hi, I was thinking about splitting the dsls binaries based on the user needs.
By doing so client can simply depends his application to the specific language module that he needs and does not suffer the wrong imports that can happen by IDEs. (and of course less classes in the classpath).
as a suggestion we can have 3 projects for each of the projects that already exist. e.g:
* {project-name}-core
* {project-name}-scaladsl
* {project-name}-javadsl

 I would be more than happy to do it for one of the existing projects as an experiment If you guys think it makes sense.

**Comment by stephennancekivell** [comment]
I dont think there is enough work in the java dsl's to justify them being in another project. And I like how little work is required by the library author to support both languages.

This is the same as in `akka-streams` itself. Its nice that `alpakka` is consistent.

Just my 2 cents, others might think differently.

**Comment by johanandren** [comment]
I agree with @stephennancekivell, there is often so little glue logic for the language the stages are not implemented in that the artifact overhead is minimal, the wrong-import problem is annoying but I don't think it motivates the overhead of three modules per connector.

**Comment by patriknw** [comment]
I agree that we should keep one jar per project. Thanks for the suggestion and offering to do the work, @psycho-ir
