### ISSUE TITLE
MQTT Streaming: incompatibility with Akka 2.6.0 or Akka 2.6.1

### ISSUE THREAD

**Issue by jcroig** [akka/alpakka#2097]
### Versions used 

Akka version: 

2.6.0

### Expected Behavior

We should be able to start an MQTT Server using alpakka mqtt streaming when running last Alpakka artifact in a project along with Akka 2.6.1. 

### Actual Behavior

Get this runtime exception:
```
java.lang.NoClassDefFoundError: akka/actor/typed/scaladsl/adapter/package$UntypedActorRefOps$ at akka.stream.alpakka.mqtt.streaming.scaladsl.ActorMqttServerSession.<init>(MqttSession.scala:455)
```
The problem is that implicit class UntypedActorRefOps has been renamed to ClassicActorRefOps from Akka 2.5.27 to Akka 2.6.x so when the artifact is built compiling with Akka 2.5.27 it fails to run with Akka 2.6.x

### Reproducible Test Case

Build Alpakka with Akka 2.5.27 and then use the artifact in a project with Akka 2.6.1. Try to start a MQTT broker with akka.stream.alpakka.mqtt.streaming.scaladsl.ActorMqttServerSession.

**Comment by ennru** [comment]
The implicit conversion class for `ActorRef` has been renamed between Akka 2.5 and 2.6 (there was not binary-compatibility guarantee for Akka Typed).

**Comment by huntc** [comment]
There shouldn’t be an expectation of binary compatibility between 2.5 and 2.6, right? https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html

**Comment by ennru** [comment]
Exactly. Some Akka Typed API changes between 2.5 and 2.6. What is nasty for Alpakka with this is that it is source-compatible, but not binary-compatible. So we can't distribute just one jar to support both Akka versions.

**Comment by huntc** [comment]
> So we can't distribute just one jar to support both Akka versions.

I think you’re going to have to have two jars.

**Comment by ennru** [comment]
We will tweak the build to just build and publish an Akka 2.6 compatible jar for Alpakka MQTT streaming.

**Comment by raboof** [comment]
> There shouldn’t be an expectation of binary compatibility between 2.5 and 2.6, right? https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html

2.6 is binary compatible with 2.5, except for API's that were already deprecated in 2.5 or marked may-change or experimental. The typed API's were still marked may-change in 2.5, so that's why they could still change there.

**Comment by huntc** [comment]
> 2.6 is binary compatible with 2.5, except for API's that were already deprecated in 2.5 or marked may-change or experimental. 

While that may be the case now, it is permissible that 2.6 APIs can become binary incompatible with 2.5 in the future though.

**Comment by ennru** [comment]
#2118 changed MQTT streaming to be Akka 2.6 compatible (and can't be used with Akka 2.5 anymore).
