### ISSUE TITLE
AWS S3: retry multipart upload chunks on transient errors

### ISSUE THREAD

**Issue by bpiper** [akka/alpakka#2114]
### Short description

The multipart upload sink (`S3Stream.multipartUpload`) should ideally protect upstream stages from the occasional transient error that S3 is susceptible to (be they 5xx errors or connection resets) by retrying a chunk upload when such an error occurs.

### Details

This has been discussed briefly in https://discuss.lightbend.com/t/alpakka-s3-retry-multipartupload-parts-on-failure/4403.

With the recent introduction of `akka.stream.scaladsl.RetryFlow`, this should hopefully be fairly straightforward, albeit that stuff is quite new and dependent on Akka 2.6.

I can probably offer a PR for this sometime soon, though I'm not sure about the unit testing side of things and how easy/difficult it is to simulate failures in Akka HTTP.

**Comment by bpiper** [comment]
Oh, naturally the one existing test (in `S3SinkSpec`) that's failing is the one that simulates a failure, so I think I can figure that out.

**Comment by ennru** [comment]
Would be great if you can come up with a proposal. Since recently Alpakka Elasticsearch uses `RetryFlow` via a copy from main Akka.

**Comment by bpiper** [comment]
I've created a PR, though it's not mergeable as yet, as I'm not sure if it's better/easier to use a copy of the RetryFlow stuff or just wait until Alpakka is officially on Akka 2.6.

**Comment by seglo** [comment]
Feel free to create a PR with a backported copy of `RetryFlow` like in `alpakka-elasticsearch`.  We want to release Alpakka 2.0 sometime soon, but we don't have a firm timeline yet.
