### ISSUE TITLE
MQTT Streaming: version of MQTT

### ISSUE THREAD

**Issue by mb-quant** [akka/alpakka#2137]
### Short description
Docs don't have information about MQTT version.
According to https://mqtt.org/ there are few MQTT versions already (not compatible). It would be nice to add this information to docs.

### Details
Update docs with MQTT version for MQTT Streaming (and maybe for mqtt as well).

**Comment by huntc** [comment]
Agreed. It is 3.1.1: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

I’d love to work on 5.0 support.

**Comment by ennru** [comment]
Added with #2184

**Comment by saumilsdk** [comment]
hi @huntc have you looked into 5.0 support? I am waiting for akka mqtt 5.0 client support.

**Comment by huntc** [comment]
> hi @huntc have you looked into 5.0 support? I am waiting for akka mqtt 5.0 client support.

Unfortunately I’ve not.
