### ISSUE TITLE
AWS S3: AwsRegionProvider.getRegion causing significant delays in stream processing

### ISSUE THREAD

**Issue by bpiper** [akka/alpakka#2150]
### Versions used 

Latest master (currently 2.0.0-M2+).  Issue not present in 2.0.0-M2.

### Actual Behavior

As discussed in https://github.com/akka/alpakka/pull/2116, as of version 2.10.43 of the AWS v2 Java SDK, an `AwsRegionProvider` (perhaps more specifically `DefaultAwsRegionProviderChain`, and even more specifically `InstanceProfileRegionProvider`) appears to be taking almost exactly 1 second to execute the first `getRegion` call (subsequent calls to the same instance use the cached value).

This wouldn't normally be a major issue, as generally you'd instantiate a `DefaultAwsRegionProviderChain` once in the lifetime of the JVM and re-use it, meaning that only one expensive `getRegion` call is ever made.  However, in the Alpakka S3 module, `S3Stream.resolveSettings` is called regularly on the fly to get the Alpakka S3 config (mainly for the sake of unit tests I think), and each time it will create a new `AwsRegionProvider` from scratch.  In the case of multipart uploads, this is done at least 3 or 4 times for just a single upload, resulting in a fairly major performance degradation (because each S3 request results in a `getRegion` call) of several seconds per upload.

I haven't been able to pinpoint what the key change in version 2.10.43 of the AWS SDK was yet.  I believe it may be specific to `InstanceProfileRegionProvider`, because it was only when running in an EC2 instance that I noticed this degradation.  I may investigate this further, but for Alpakka's part, I think it's fair to say that it should be possible to resolve the config once and just re-use that on all subsequent occasions.  The exception would be where someone chooses to explicitly provide the settings for a specific graph using `withAttributes` (which can actually be used as a workaround for this issue).  The `S3Stream` object could maybe just load the 'default' settings (i.e. using the default config path) as a lazy val that is used by `S3Stream.resolveSettings` when it finds no `S3SettingsValue` or `S3SettingsPath` attributes.

I would imagine that others are likely to hit this issue too.  Given the severity of the performance hit, I think this warrants fixing before the next Alpakka release.  I may have time to submit a PR in the near future.

**Comment by ennru** [comment]
Fixed with #2162
