### ISSUE TITLE
Add support for AWS EventBridge

### ISSUE THREAD

**Issue by jmnarloch** [akka/alpakka#2151]
### Short description

AWS EventBridge is service launched in August 2019, previously know as CloudWatch Events. Amazon EventBridge is a serverless event bus that allows developers to decouple their applications by submitting events through event bus and subscribing to them.

### Details

The goal would be to add to Alpakka support for AWS EventBridge as first class citizen similarly as SNS and SQS are supported today.

Reference:
https://docs.aws.amazon.com/eventbridge/latest/userguide/what-is-amazon-eventbridge.html

**Comment by seglo** [comment]
Hi @jmnarloch.  Are you aware of this ongoing effort to implement an EventBridge connector?  https://github.com/akka/alpakka/pull/2061

**Comment by jmnarloch** [comment]
@seglo sorry should had done better search through the issues. Cool that there is ongoing effort to do that.

**Comment by seglo** [comment]
No problem.  Maybe you can take a peek and see if there's anything you would like to see.  It's still in progress.  Appreciate the effort none-the-less!
