### ISSUE TITLE
Use google/cloud-sdk emulator to add integration tests for Google Pub Sub

### ISSUE THREAD

**Issue by seglo** [akka/alpakka#2167]
There's no integration testing currently done in the google-pub-sub connector.  This issue was raised in https://github.com/akka/alpakka/issues/2163 .

Some posts about using the `google/cloud-sdk` Docker image in a test suite:

https://medium.com/@mrkrijgsman/integration-testing-pub-sub-interactions-in-your-application-45e35476de23 
https://medium.com/google-cloud/using-google-cloud-emulators-for-integration-tests-7812890ebe0d

**Comment by ennru** [comment]
Both Pub/Sub connectors use the official Google cloud emulator for testing now.
