### ISSUE TITLE
[Failed] Scheduled build fails on Cassandra

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#2199]
https://travis-ci.com/github/akka/alpakka/jobs/297794147#L1957

**Comment by ignasi35** [comment]
I can reproduce the problem locally if I disable the `insideCI.value` forcing `Seq("-Werror")`. But I'm not sure why this didn't fail on thge PR validation.

Problem is Tikerpop's annotation processor:

```
[warn] Supported source version 'RELEASE_8' from annotation processor 'org.apache.tinkerpop.gremlin.process.traversal.dsl.GremlinDslProcessor' less than -source '11'
[error] warnings found and -Werror specified
```

I will try to override the dependencies in the OrientDb and Cassandra connectors to use `3.5.0` artifacts of TinkerPop (where [Java 11 support was introduced](https://groups.google.com/forum/#!topic/gremlin-users/gUGz6yqNw4M)).

**Comment by ignasi35** [comment]
More info. The tinkerpop dependency is transitively added by `cassandra` (not `orientdb`) connector. 

I suspect the recent [Java Driver upgrade](https://github.com/akka/alpakka/pull/2182/files#diff-0ecdbc5a001d52fb34f5eafb7cd1aaa6) is the culprit. _(Just checked past `CRON` builds and that's exactly where we added the issue)_

**Comment by ignasi35** [comment]
Raised https://github.com/akka/alpakka/issues/2200
