### ISSUE TITLE
Cassandra: Override gremlin-core to 3.5.0

### ISSUE THREAD

**Issue by ignasi35** [akka/alpakka#2200]
In order to fix #2199 `gremlin-core` was excluded from the transitive dependencies of the cassandra java driver.

When `gremlin-core` `3.5.0` is out instead of excluding we could override the transitive dependency (`gremlin-core` `3.4.6`).

Alternatively, we can wait until the cassandra java driver depends on `gremlin-core` `3.5.0`.

**Comment by ennru** [comment]
Solved for now with #2201

**Comment by ignasi35** [comment]
Ah, I didn't know about https://github.com/akka/alpakka/pull/2201#issuecomment-599454639

If Grmlin is only for non-OSS features of Cassandra, then this issue which aimed to restore the transitive dependency is not required.
