### ISSUE TITLE
Cassandra: remove Netty dependency override

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#2226]
As there is some change in Netty 4.1.45 which made throughput drop, Alpakka Cassandra downgrades Netty to 4.1.39.

References 
* https://github.com/akka/akka-persistence-cassandra/pull/730
* https://datastax-oss.atlassian.net/browse/JAVA-2676

**Comment by patriknw** [comment]
Until this has been fixed we will have a security vulnerability reported by Whitesource on the Netty 4.1.39 dependency.

**Comment by chbatey** [comment]
https://github.com/akka/alpakka/pull/2320

**Comment by ennru** [comment]
Fixed with #2320
