### ISSUE TITLE
Add readme page for every connector

### ISSUE THREAD

**Issue by hepin1989** [akka/alpakka#2244]
as `Pravega connector`,  there is no readme there.
![image](https://user-images.githubusercontent.com/501740/77847525-35632080-71f0-11ea-9217-87b5aae2c44c.png)

**Comment by ennru** [comment]
We don't want more places that get out of sync.
Docs are at https://doc.akka.io/docs/alpakka/snapshot/pravega.html

**Comment by hepin1989** [comment]
Okay，that's fine I think ,so I would like to close this.
