### ISSUE TITLE
Akka GCP Pub Sub 2.0.0 not discarding entity bytes

### ISSUE THREAD

**Issue by cullender-skew** [akka/alpakka#2296]
### Versions used 

om.lightbend.akka', name: 'akka-stream-alpakka-google-cloud-pub-sub_2.12 version 2.0.0

Akka version: 

2.6.1

### Expected Behavior

Pull messages from GCP Pub Sub

### Actual Behavior

exception is thrown: cp pub sub team - I recently upgraded to version 2.0.0 and now I am getting java.util.concurrent.TimeoutException: Response entity was not subscribed after 1 second. Make sure to read the response entity body or calldiscardBytes()on it.

on the :pull request

**Comment by Habitats** [comment]
Can confirm that this is happening, though I can still pull messages.

It also seem to only happen on busy topics. For topics with only a few events now and then, this does _not_ happen. However, for my busy ones (~30-50 messages/s) it happens basically every other second.

I've tried setting this in `application.conf` but it didn't change anything
```
stream {
  materializer {
     subscription-timeout {
        mode = warn
        timeout = 5s
      }
  }
}
```

**Comment by ennru** [comment]
More details by @Habitats on [Gitter](https://gitter.im/akka/alpakka-kafka?at=5eaa94b7a9de3d01b1dc32cb)

**Comment by ennru** [comment]
One thing I can think of when staring at the code is the interaction between unmarshalling in `mapAsync` and the `mapConcat`. This might lead to backpressure which makes the `mapAsync` wait too long so the no entity subscription timer kicks in.

**Comment by Habitats** [comment]
But should the `subscription-timeout` config still not apply? Or am I confusing that flag with something else?

**Comment by ennru** [comment]
Incidentally, a similar problem was just reported to Akka HTTP https://github.com/akka/akka-http/issues/3134

**Comment by jrudolph** [comment]
> But should the `subscription-timeout` config still not apply? Or am I confusing that flag with something else?

It's another setting in akka-http which is responsible in that case, `akka.http.host-connection-pool.response-entity-subscription-timeout`.

In akka/akka-http#3134, I have outlined a possibly path forward.

**Comment by jrudolph** [comment]
> In [akka/akka-http#3134](https://github.com/akka/akka-http/issues/3134), I have outlined a possibly path forward.

Currently, the implementation uses 

https://github.com/akka/alpakka/blob/668c6cacab9c09a7dc1bd93222720790df6fb36e/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/PubSubApi.scala#L139

Until https://github.com/akka/akka-http/issues/2120 is implemented, the flow-based client interfaces in akka-http are not much more than a single wrapper that does a `mapAsyncUnordered(settings.maxConnections)` over the `Http().singleRequest` API. The `mapAsync` has an internal buffer of the given parallelism size. I see that `PubSubApi` processes the responses with `mapAsync` itself again with yet another parallelism setting. So, all of those `mapAsync` usages will introduce buffers that can introduce delay between getting a response and handling it.

So, the recommendation for fixing this is:

 * use `singleRequest` directly and make sure responses are not stuck in buffers for a long time until they are processed. The timeout can be avoided if the unmarshalling or discarding of entities is done right away when the response comes in
 * in a stream pipeline setting consider how parallelism is used, especially make sure not to run more requests in parallel (and then buffer) in the upstream part of the stream
 * run unmarshalling or `toStrict` right away when responses come in. For that memory usage needs to be taken into account. If, instead, streaming processing of entities is desired, make sure to start the streams right away.

**Comment by khemtat** [comment]
Hi, any updates on this problem? I just ran into this kind of error and can't get my application to works.

These are two error messages that I got. 

Is there any workaround to fix these errors or I have to wait for the library to update.

BTW the topics which I consume don't have any messages in it but having more than 5-10 subscriptions per application is causing this problem.

```
akka.http.impl.engine.client.PoolGateway - [3 (WaitingForResponseEntitySubscription)]
Response entity was not subscribed after 1 second. Make sure to read the response entity body or call `discardBytes()` on it. 
POST /v1/projects/project_id/subscriptions/topic:pull Strict(45 bytes) -> 200 OK Chunked
```

```
akka.stream.scaladsl.RestartWithBackoffSource - Restarting graph due to failure. stack_trace:
akka.stream.BufferOverflowException: Exceeded configured max-open-requests value of [32].
This means that the request queue of this pool 
(HostConnectionPoolSetup(pubsub.googleapis.com,443,ConnectionPoolSetup(ConnectionPoolSettings(4,0,5,32,1,Duration.Inf,100 milliseconds,2 minutes,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.1.12),10 seconds,1 minute,512,None,WebSocketSettings(<function0>,ping,Duration.Inf,akka.http.impl.settings.WebSocketSettingsImpl$$$Lambda$906/1173213008@28aa237e),List(),ParserSettings(2048,16,64,64,8192,64,8388608,8388608,256,1048576,Strict,RFC6265,true,Set(),Full,Error,HashMap(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, If-None-Match -> 0, User-Agent -> 32, Content-MD5 -> 0, Date -> 0, If-Match -> 0),false,true,akka.util.ConstantFun$$$Lambda$689/348209600@6018e3ad,akka.util.ConstantFun$$$Lambda$689/348209600@6018e3ad,akka.util.ConstantFun$$$Lambda$690/1636256669@19d08d03),100 milliseconds,None,TCPTransport),New,1 second),akka.http.scaladsl.HttpsConnectionContext@49ff5179,akka.event.MarkerLoggingAdapter@4c24969b)))
has completely filled up because the pool currently does not process requests fast enough to handle the incoming request load. 
Please retry the request later. See http://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html for more information.
```

```scala
RestartSource.withBackoff(1.second, 30.seconds, 0.3, 7) { () =>
    GooglePubSub.subscribe(subscription, pubSubConfig)
      .map { received =>
        //process the message

        received.ackId
      }
  }
    .map(ackId => AcknowledgeRequest(ackId))
    .runWith(ackSink)
```

**Comment by jrudolph** [comment]
@khemtat we are not currently working on this (this module is community-driven) but maybe someone would step up and try a fix based on the above notes?

**Comment by ennru** [comment]
@karlssonsimon Switched this to `singleRequest` in #2403 which should solve this.
