### ISSUE TITLE
Elasticsearch - ElasticsearchFlow provide groupedWithin alternative flow

### ISSUE THREAD

**Issue by KGoodale13** [akka/alpakka#2305]
### Short description

Controlling the size of bulk index requests is an important part to achieving maximum indexing throughput in Elasticsearch. Providing alternative flows that make use of "groupedWithin" as opposed to "batch" is a requirement for users of alpakka who would like to tune their bulk index request sizes.

### Details

I'm not entirely sure the best way to implement this but I believe the most straight forward way would be to add the following methods to ElasticsearchFlow.
- createGrouped
- createGroupedWithPassthrough
- createGroupedWithContext

This would also require an optional FiniteDuration value be added to the ElasticsearchWriteSettings in order to control the interval of the "groupedWithin". Or possibly a FiniteDuration parameter added to the above proposed methods. 

If I could get some feedback on if/how the maintainers of this project would like this to be implemented, I would be happy to do so.

**Comment by ennru** [comment]
I believe the best would be to offer a factory method that exposes `stageFlow: Flow[immutable.Seq[WriteMessage[T, C]], immutable.Seq[WriteResult[T, C]], NotUsed]` so users can group messages for bulk updates as they like. Maybe `createBulk` is a suitable name.

**Comment by KGoodale13** [comment]
Makes sense to me. I'll cook up a PR for that!

**Comment by KGoodale13** [comment]
Fixed with #2306 merged
