### ISSUE TITLE
[Elasticsearch] Log errors from failed indexing in ElasticsearchFlow

### ISSUE THREAD

**Issue by KGoodale13** [akka/alpakka#2313]
### Short description

Currently errors returned from Elasticsearch on indexing failure are not logged. These errors are incredibly valuable when debugging issues. I would like to add a log.error to the retryLogic in the stageFlow here: https://github.com/akka/alpakka/blob/master/elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/scaladsl/ElasticsearchFlow.scala#L175

**Comment by KGoodale13** [comment]
Looking into this now and I've noticed there are no logs in the elasticsearch module at all. Wondering what the best way to introduce some logging into this module is?

**Comment by KGoodale13** [comment]
I think the proper place to log these indexing failures is the ElasticsearchSimpleFlowStage since there is a logging context available there. I'll open a PR for that.

**Comment by ennru** [comment]
Fixed with #2317
