### ISSUE TITLE
ShardSettings API doesn't allow for unordered configuration

### ISSUE THREAD

**Issue by vaslabs** [akka/alpakka#2315]
### alpakka kinesis
If you want to set the iterator to AFTER_SEQUENCE_NUMBER, AT_SEQUENCE_NUMBER or
AT_TIMESTAMP you have to set first the value of the sequence number (or timestamp). Which
means that simple mistakes can be made which can be avoided.

### Details

We can define a ShardIterator ADT which accepts its dependencies if any and doesn't require subsequent methods to set it up.
E.g. `withShardIterator(ShardIterator.AfterSequenceNumber(sequence))` which will avoid this runtime issue.

If you agree please assign the ticket to me and I can follow up with a pull request.

Source: https://github.com/akka/alpakka/blob/master/kinesis/src/main/scala/akka/stream/alpakka/kinesis/ShardSettings.scala#L25

**Comment by ennru** [comment]
Fixed with #2331
