### ISSUE TITLE
Remove obsolete reference configuration from Alpakka DynamoDB

### ISSUE THREAD

**Issue by vigoo** [akka/alpakka#2334]
The `reference.conf` in Alpakka DynamoDB remained untouched during the refactoring to AWS SDK v2. The new implementation no longer uses these configuration keys. 

This is confusing for the library users who try to gather the available configuration from the libraries' reference configs.

I propose to delete it completely (as none of it is in use):
https://github.com/akka/alpakka/pull/2333

**Comment by ennru** [comment]
Fixed with #2333
