### ISSUE TITLE
S3: Consider not deprecating path-style access

### ISSUE THREAD

**Issue by mpdn** [akka/alpakka#2364]
While AWS is deprecating path-style access, many other providers of S3-like services are not. Path-style access is usually the easiest way to setup MinIO as it does not require fudging around with the DNS.

So while path-style access for AWS should be deprecated, path-style access for custom endpoints are still relevant.

For the same reason, it would be nice to have a way to disable the warning here: https://github.com/akka/alpakka/blob/4c01bb13fc31cd8900955127356cff6f2601d13b/s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala#L179

I would be willing to put some work into this. The simplest way of achieving this would probably be something like un-deprecating the `withPathStyleAccess` function and remove the warning for custom endpoints.

**Comment by ennru** [comment]
You are right, for compatible storage solutions Alpakka should continue to allow path-style access in one way or the other.

Would it be possible to use the `enpoint-url` setting to achieve something without removing the deprecation?
https://github.com/akka/alpakka/blob/01bb7e4c35f1550dc04b82ab211fa9a9768dae4a/s3/src/main/resources/reference.conf#L87-L91

**Comment by KGausel** [comment]
@ennru I tried that, but maybe I configured it wrong. Do you have any input on how to make it work with MinIO using the `endpoint-url` template method you are suggesting?

I tried `http://myminio.local/{bucket}` and `http://myminio.local/{bucket}/`

**Comment by ennru** [comment]
Alpakka uses Minio with virtual-host style access. The trick is to configure a forward-proxy and a dynamic `enpoint-url`:

https://github.com/akka/alpakka/blob/63b22cb0735215fece5ce91b7d09f0a733b3e0c1/s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3IntegrationSpec.scala#L638-L657

**Comment by KGausel** [comment]
This might not be an option for all users though and seems like an overly complicated way to stop Alpakka from spamming log warnings of path style access being deprecated.

**Comment by ennru** [comment]
@KGausel Good news, @laszlovandenhoek just convinced me that we can should [re-think the path-style access settings](https://github.com/akka/alpakka/pull/2193#issuecomment-686304485

**Comment by ennru** [comment]
With #2392 the deprecation shows only if you don't use an `endpointUrl` thus use AWS' services.
This cleaner solution resolved your request.
