### ISSUE TITLE
Elasticsearch WriteMessage.createIndexMessage documentation misguides developers

### ISSUE THREAD

**Issue by yannisf** [akka/alpakka#2385]
If you check the latest Alpakka Elasticsearch documentation, under `Writing to Elasticsearch` (https://doc.akka.io/docs/alpakka/current/elasticsearch.html#writing-to-elasticsearch) it states the following for the `WriteMessage.createIndexMessage` message factory:

> "Create a new document. If id is specified and it already exists, do nothing." 

This is not consistent with the Elasticsearch documentation and actually misinforms. The `createIndexMessage` triggers an `index` bulk action and according to the official Elasticsearch documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) it states:

> Indexes the specified document. If the document exists, replaces the document and increments the version.

So the `do nothing` should be replaced with `replaces the document and increments the version`.

Obviously I can submit a PR if you agree.

**Comment by seglo** [comment]
Makes sense to me.  Yes, a PR would be appreciated. :+1:

**Comment by seglo** [comment]
Fixed in #2387
