### ISSUE TITLE
AWS S3: Unsupported Content-Type `text/event-stream` during multipart upload to minio

### ISSUE THREAD

**Issue by bgahagan** [akka/alpakka#2394]
Hello,

When doing a S3 multipart upload of a large file (>2GB in my case) to a Minio server, I occasionally see the upload
 fail with the following error message:

```
akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type [Some(text/event-stream)], supported: application/xml; charset=UTF-8
```

A `tcpdump` revels that under some conditions, Minio will send a `ContentType: text/event-stream` header in the CompleteMultipartUpload response.

### Expected Behavior

Alpakka S3 treats the `ContentType: text/event-stream` header the same as the usual `ContentType: application/xml` header and successfully completes the upload

### Actual Behavior

Alpakka S3 fails after receiving the CompleteMultipartUpload response from the server with the following exception: 

```text
[info]   akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type [Some(text/event-stream)], supported: application/xml; charset=UTF-8
[info]   at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:191)
[info]   at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:200)
[info]   at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$.$anonfun$forContentTypes$3(Unmarshaller.scala:116)
[info]   at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
[info]   at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$.$anonfun$mapWithInput$3(Unmarshaller.scala:93)
[info]   at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
[info]   at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$transform$3(Unmarshaller.scala:23)
[info]   at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
[info]   at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:25)
[info]   at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$signAndGetAs$6(S3Stream.scala:793)
[info]   at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1376)
[info]   at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
[info]   at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:409)
[info]   at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
[info]   at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:485)
[info]   at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
[info]   at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
[info]   at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
[info]   at akka.actor.Actor.aroundReceive(Actor.scala:539)
[info]   at akka.actor.Actor.aroundReceive$(Actor.scala:537)
[info]   at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
[info]   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
[info]   at akka.actor.ActorCell.invoke(ActorCell.scala:583)
[info]   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
[info]   at akka.dispatch.Mailbox.run(Mailbox.scala:229)
[info]   at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
[info]   at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]   at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]   at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]   at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### Alpakka version
```
"com.lightbend.akka" %% "akka-stream-alpakka-s3" % "2.0.1"
```

## Why is Minio sending `ContentType: text/event-stream`?

I've tracked down the [change](https://github.com/minio/minio/pull/7909) where this was introduced. Minio sets the
 ContentType header of a CompleteMultipartUpload response to be `text/event-stream` if the operation takes longer than
 10 seconds to process. According to the [PR](https://github.com/minio/minio/pull/7909), this is to prevent
 connections from timing out due to inactivity when Minio is behind a reverse proxy.

After 10 seconds of inactivity on the connection, minio will send HTTP headers back to the client
 with `ContentType: text/event-steam`. It will then send a space character every 10 seconds until the operation is complete (e.g. the parts have been concatenated into a single file on disk) and the response xml is
 ready to be sent.  The code to send the space every 10 seconds is
 [here](https://github.com/minio/minio/blob/fbd1c5f51a900158013e8d8e4593d9ca898f8b7e/cmd/object-handlers.go#L2444-L2479),
 and the code to set the ContentType is
 [here](https://github.com/minio/minio/blob/fbd1c5f51a900158013e8d8e4593d9ca898f8b7e/cmd/object-handlers.go#L2623)

## Reproducible Test Case

I've been able to reliably reproduce this by creating a minio instance with i/o throttling enabled so that the
 CompleteMultipartUpload takes longer than 10 seconds to process.

### Setup a throttled Minio instance

Setup a Minio instance with reads and writes to the `/data` directory limited to 1 mb/s in docker:

```shell script
#!/bin/bash

# Create a loopback device to throttle
LO_FILE="/tmp/minio-loopback.img"
LO_DEV=$(losetup -f)

dd if=/dev/zero of="$LO_FILE" bs=100M count=50
mkfs.ext4 "$LO_FILE"
sudo losetup -P "$LO_DEV" "$LO_FILE"

# Start Minio
# - Use the local volume driver to mount /dev/loopX directly - this allows us to pass the correct device to
#   device-write-bps for throttling. I wasn't able to get throttling to work with the usual -v/bind mounts
# - Set CONFIG_BLK_CGROUP and CONFIG_BLK_DEV_THROTTLING to enable throttling, following this guide:
#   https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/blkio-controller.html#throttling-upper-limit-policy
# - MINIO_FS_OSYNC needs to be set so that Mionio fsyncs to the disk, and throttling can take effect
docker run -i --rm \
  --name minio \
  --device "$LO_DEV" \
  --device-read-bps "$LO_DEV":1mb --device-write-bps "$LO_DEV":1mb \
  -e MINIO_ACCESS_KEY=TESTKEY -e MINIO_SECRET_KEY=TESTSECRET -e MINIO_DOMAIN=s3minio.alpakka -e MINIO_FS_OSYNC=true \
  -e CONFIG_BLK_CGROUP=y -e CONFIG_BLK_DEV_THROTTLING=y \
  --mount "type=volume,source=miniodata,target=/data,volume-driver=local,volume-opt=type=ext4,volume-opt=device=$LO_DEV" \
  -p 9001:9000 \
  minio/minio \
  server /data

# We can verify that the throttling is properly configured by running dd
# This command should take about 5 seconds to write 5 x 1mb blocks to our disk throttled to 1mb/s throttle
# docker exec minio sh -c "dd if=/dev/zero of=/data/test5 bs=1M count=5 conv=fsync"

# Cleanup loopback device and image
sudo losetup -d "$LO_DEV"
rm "$LO_FILE"
docker volume rm miniodata
```

### Perform a multipart upload

We need to perform the upload with a reasonably large payload so that the CompleteMultipartUpload request takes longer
 than 10 seconds:

```scala
val objectKey = "slow"
val hugeString = "0123456789abcdef" * 64 * 1024 * 11 // ~ 11mb
Source
  .single(ByteString(hugeString))
  .runWith{
    S3.multipartUpload(defaultBucket, objectKey, MediaTypes.`application/octet-stream`)
  }
```

## Proposed fix

It should be easy enough to add `text/event-stream` to the list of allowed ContentTypes in the
 [CompleteMultipartUploadResultUnmarshaller](https://github.com/akka/alpakka/blob/b3bb8d5c1c77b9124c90ef7ea0819c7b18d172ce/s3/src/main/scala/akka/stream/alpakka/s3/impl/Marshalling.scala#L34).

However, adding an integration test to cover this might be more difficult. My plan is to create a test, but annotated it
 with `@Ignore` since:
 * Manual setup will be required to create a throttled Minio instance
 * The test will take about 20-30 seconds to run, which may be annoying to have run in the normal test suite

If there are no objections, I'll look at creating a PR with the fix. Thanks!

**Comment by ennru** [comment]
Thank you for such a well researched issue report.
