### ISSUE TITLE
Client identity string: SSH-2.0-SSHJ_0.27.0 failed to connect to SSH-2.0-7.9.0.0_openssh Globalscape

### ISSUE THREAD

**Issue by Alexandru40** [akka/alpakka#2415]
Hello,

It would be helpful you can give us a hint on why the connection always failed. We are using alpakka-ftp library (2.0.0-RC2) which uses sshj (0.27.0) ssh library underneath.

Generating random seed from SecureRandom.
Creating random seed took 0 ms
Available cipher factories: [aes128-cbc, aes128-ctr, aes192-cbc, aes192-ctr, aes256-cbc, aes256-ctr, blowfish-cbc, blowfish-ctr, cast128-cbc, cast128-ctr, idea-cbc, idea-ctr, serpent128-cbc, serpent128-ctr, serpent192-cbc, serpent192-ctr, serpent256-cbc, serpent256-ctr, 3des-cbc, 3des-ctr, twofish128-cbc, twofish128-ctr, twofish192-cbc, twofish192-ctr, twofish256-cbc, twofish256-ctr, twofish-cbc, arcfour, arcfour128, arcfour256]
Client identity string: SSH-2.0-SSHJ_0.27.0
Server identity string: SSH-2.0-7.9.0.0_openssh Globalscape
Sending SSH_MSG_KEXINIT
Received SSH_MSG_KEXINIT
Negotiated algorithms: [ kex=diffie-hellman-group-exchange-sha256; sig=ssh-rsa; c2sCipher=aes128-cbc; s2cCipher=aes128-cbc; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none ]
Sending KEX_DH_GEX_REQUEST
Received kex followup data
Got message KEXDH_31
Received server p bitlength 8192
Sending KEX_DH_GEX_INIT
Received kex followup data
Got message KEX_DH_GEX_REPLY
Trying to verify host key with net.schmizz.sshj.transport.verification.PromiscuousVerifier@1a2bee29
Sending SSH_MSG_NEWKEYS
Received SSH_MSG_NEWKEYS
Key exchange took 0.724 seconds
Sending SSH_MSG_SERVICE_REQUEST for ssh-userauth
Setting active service to ssh-userauth
Trying `password` auth...
Requesting password for [AccountResource] i_0488_test@Ip Address
Setting active service to ssh-connection
`password` auth successful
Attaching `session` channel (#0)
Initialized - < session channel: id=0, recipient=0, localWin=[winSize=2097152], remoteWin=[winSize=0] >
Will request `sftp` subsystem
Sending channel request for `subsystem`
Received window adjustment for 2097152 bytes
Increasing by 2097152 up to 2097152
Consuming by 9 down to 2097143
Consuming by 9 down to 2097143
Server version 3
Sending Request{1;OPENDIR}
Consuming by 36 down to 2097107
Consuming by 14 down to 2097129
Received HANDLE packet
Sending Request{2;READDIR}
Consuming by 14 down to 2097093
Consuming by 32 down to 2097097
Received STATUS packet
Closing `RemoteResource{/produced-sims/uploaded}`
Sending Request{3;CLOSE}
Consuming by 14 down to 2097079
Consuming by 28 down to 2097069
Received STATUS packet
Sending close
Error during postStop in [akka.stream.alpakka.ftp.impl.FtpSourceFactory$$anon$1@22f24a6f]: Timeout expired\nnet.schmizz.sshj.connection.ConnectionException: Timeout expired\n\tat net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:32)\n\tat net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:26)\n\tat net.schmizz.concurrent.Promise.retrieve(Promise.java:139)\n\tat net.schmizz.concurrent.Event.await(Event.java:105)\n\tat net.schmizz.sshj.connection.channel.AbstractChannel.close(AbstractChannel.java:266)\n\tat net.schmizz.sshj.sftp.SFTPEngine.close(SFTPEngine.java:253)\n\tat net.schmizz.sshj.sftp.SFTPClient.close(SFTPClient.java:250)\n\tat akka.stream.alpakka.ftp.impl.SftpOperations.disconnect(SftpOperations.scala:69)\n\tat akka.stream.alpakka.ftp.impl.SftpOperations.disconnect$(SftpOperations.scala:68)\n\tat akka.stream.alpakka.ftp.impl.FtpLike$$anon$3.disconnect(FtpLike.scala:62)\n\tat akka.stream.alpakka.ftp.impl.FtpLike$$anon$3.disconnect(FtpLike.scala:62)\n\tat akka.stream.alpakka.ftp.impl.FtpGraphStageLogic.$anonfun$disconnect$1(FtpGraphStageLogic.scala:67)\n\tat akka.stream.alpakka.ftp.impl.FtpGraphStageLogic.$anonfun$disconnect$1$adapted(FtpGraphStageLogic.scala:67)\n\tat scala.Option.foreach(Option.scala:437)\n\tat akka.stream.alpakka.ftp.impl.FtpGraphStageLogic.disconnect(FtpGraphStageLogic.scala:67)\n\tat akka.stream.alpakka.ftp.impl.FtpGraphStageLogic.postStop(FtpGraphStageLogic.scala:49)\n\tat akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:599)\n\tat akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:579)\n\tat akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:438)\n\tat akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:55)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:51)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$RequestMore.execute(ActorGraphInterpreter.scala:273)\n\tat akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)\n\tat akka.actor.Actor.aroundReceive(Actor.scala:534)\n\tat akka.actor.Actor.aroundReceive$(Actor.scala:532)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)\n\tat akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)\n\tat akka.actor.ActorCell.invoke(ActorCell.scala:543)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:230)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.util.concurrent.TimeoutException: Timeout expired\n\tat net.schmizz.concurrent.Promise.retrieve(Promise.java:139)\n\tat net.schmizz.concurrent.Event.await(Event.java:105)\n\tat net.schmizz.sshj.connection.channel.AbstractChannel.close(AbstractChannel.java:266)\n\tat net.schmizz.sshj.sftp.SFTPEngine.close(SFTPEngine.java:253)\n\tat net.schmizz.sshj.sftp.SFTPClient.close(SFTPClient.java:250)\n\tat akka.stream.alpakka.ftp.impl.SftpOperations.disconnect(SftpOperations.scala:69)\n\tat akka.stream.alpakka.ftp.impl.SftpOperations.disconnect$(SftpOperations.scala:68)\n\tat akka.stream.alpakka.ftp.impl.FtpLike$$anon$3.disconnect(FtpLike.scala:62)\n\tat akka.stream.alpakka.ftp.impl.FtpLike$$anon$3.disconnect(FtpLike.scala:62)\n\tat akka.stream.alpakka.ftp.impl.FtpGraphStageLogic.$anonfun$disconnect$1(FtpGraphStageLogic.scala:67)\n\tat akka.stream.alpakka.ftp.impl.FtpGraphStageLogic.$anonfun$disconnect$1$adapted(FtpGraphStageLogic.scala:67)\n\tat scala.Option.foreach(Option.scala:437)\n\tat akka.stream.alpakka.ftp.impl.FtpGraphStageLogic.disconnect(FtpGraphStageLogic.scala:67)\n\tat akka.stream.alpakka.ftp.impl.FtpGraphStageLogic.postStop(FtpGraphStageLogic.scala:49)\n\tat akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:599)\n\tat akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:579)\n\tat akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:438)\n\tat akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:55)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:51)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$RequestMore.execute(ActorGraphInterpreter.scala:273)\n\tat akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)\n\tat akka.actor.Actor.aroundReceive(Actor.scala:534)\n\tat akka.actor.Actor.aroundReceive$(Actor.scala:532)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)\n\tat akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)\n\tat akka.actor.ActorCell.invoke(ActorCell.scala:543)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:230)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n
Generating random seed from SecureRandom.
Creating random seed took 0 ms
Available cipher factories: [aes128-cbc, aes128-ctr, aes192-cbc, aes192-ctr, aes256-cbc, aes256-ctr, blowfish-cbc, blowfish-ctr, cast128-cbc, cast128-ctr, idea-cbc, idea-ctr, serpent128-cbc, serpent128-ctr, serpent192-cbc, serpent192-ctr, serpent256-cbc, serpent256-ctr, 3des-cbc, 3des-ctr, twofish128-cbc, twofish128-ctr, twofish192-cbc, twofish192-ctr, twofish256-cbc, twofish256-ctr, twofish-cbc, arcfour, arcfour128, arcfour256]
Client identity string: SSH-2.0-SSHJ_0.27.0
Server identity string: SSH-2.0-7.9.0.0_openssh Globalscape
Sending SSH_MSG_KEXINIT
Received SSH_MSG_KEXINIT
Negotiated algorithms: [ kex=diffie-hellman-group-exchange-sha256; sig=ssh-rsa; c2sCipher=aes128-cbc; s2cCipher=aes128-cbc; c2sMAC=hmac-sha1; s2cMAC=hmac-sha1; c2sComp=none; s2cComp=none ]
Sending KEX_DH_GEX_REQUEST
Received kex followup data
Got message KEXDH_31
Received server p bitlength 8192
Sending KEX_DH_GEX_INIT
Received kex followup data
Got message KEX_DH_GEX_REPLY
Trying to verify host key with net.schmizz.sshj.transport.verification.PromiscuousVerifier@28f7a638
Sending SSH_MSG_NEWKEYS
Received SSH_MSG_NEWKEYS
Key exchange took 0.766 seconds
Sending SSH_MSG_SERVICE_REQUEST for ssh-userauth
Setting active service to ssh-userauth
Trying `password` auth...
Requesting password for [AccountResource] i_0488_test@Ip Address
Setting active service to ssh-connection
`password` auth successful
Attaching `session` channel (#0)
Initialized - < session channel: id=0, recipient=0, localWin=[winSize=2097152], remoteWin=[winSize=0] >
Will request `sftp` subsystem
Sending channel request for `subsystem`
Received window adjustment for 2097152 bytes
Increasing by 2097152 up to 2097152
Consuming by 9 down to 2097143
Consuming by 9 down to 2097143
Server version 3
Sending Request{1;OPENDIR}
Consuming by 22 down to 2097121
Consuming by 14 down to 2097129
Received HANDLE packet
Sending Request{2;READDIR}
Consuming by 14 down to 2097107
Consuming by 294 down to 2096835
Received NAME packet
Sending Request{3;READDIR}
Consuming by 14 down to 2097093
Consuming by 32 down to 2096803
Received STATUS packet
Closing `RemoteResource{/raw_cdrs}`
Sending Request{4;CLOSE}
Consuming by 14 down to 2097079
Consuming by 28 down to 2096775
Received STATUS packet
Sending close
Dying because - Connection reset\njava.net.SocketException: Connection reset\n\tat java.net.SocketInputStream.read(SocketInputStream.java:210)\n\tat java.net.SocketInputStream.read(SocketInputStream.java:141)\n\tat net.schmizz.sshj.transport.Reader.run(Reader.java:49)\n
Disconnected - UNKNOWN
Got notified of net.schmizz.sshj.common.SSHException: Connection reset
Notified of net.schmizz.sshj.common.SSHException: Connection reset
Channel #0 got notified of net.schmizz.sshj.common.SSHException: Connection reset
Forgetting `session` channel (#0)
Setting active service to null-service
Stopping

**Comment by raboof** [comment]
Interesting, it seems the operations actually work but the 'close' times out:

```
Sending Request{1;OPENDIR}
Received HANDLE packet
Sending Request{2;READDIR}
Received STATUS packet
Closing RemoteResource{/produced-sims/uploaded}
Sending Request{3;CLOSE}
Received STATUS packet
Sending close
Error during postStop in [akka.stream.alpakka.ftp.impl.FtpSourceFactory$$anon$1@22f24a6f]: Timeout expired
```

I'm afraid this doesn't look like something we can fix on the alpakka level. You could try upgrading sshj to the latest version (0.30.0)? It could be a problem in sshj, but generally that library is very high-quality, so it is also possible the server is simply misbehaving...

(closing for now since it seems out of our control, but feel free to re-open when there appears there is something we can do after all)
