### ISSUE TITLE
Pub/Sub Grpc Support for Akka 2.6 and higher

### ISSUE THREAD

**Issue by yapily-gkatzioura** [akka/alpakka#2423]
### Short description

Akka 2.6 and akka-streams cannot be used with the Pub/Sub grpc connector due to a conflict with the akka-discovery dependency (needs to be Akka 2.5). 

### Details

Akka 2.6 and akka-streams come with nice features like logWithMarker. Due to the grpc pub/sub connector using an older version of the akka-discovery through the akka grpc runtime dependency, it is not possible to combine Akka 2.6 and the pub/sub grpc connector. 
Is it possible to migrate to a higher version of the akka-discovery for this module? 
If there are certain guidelines I am also ok to go for a PR if there are no obstacles.

**Comment by raboof** [comment]
> Due to the grpc pub/sub connector using an older version of the akka-discovery through the akka grpc runtime dependency

Because we provide binary compatibility I think you can just upgrade akka-discovery in your project - but I guess you figured that out when you closed this ;)
