### ISSUE TITLE
Pub/Sub Grpc Support for Akka 2.6 and higher 

### ISSUE THREAD

**Issue by gkatzioura** [akka/alpakka#2424]
### Short description

Akka 2.6 and akka-streams cannot be used with the Pub/Sub grpc connector due to a conflict with the akka-discovery dependency (needs to be Akka 2.5).

### Details

Akka 2.6 and akka-streams come with nice features like logWithMarker. Due to the grpc pub/sub connector using an older version of the akka-discovery through the akka grpc runtime dependency, it is not possible to combine Akka 2.6 and the pub/sub grpc connector.
Is it possible to migrate to a higher version of the akka-discovery for this module?
If there are certain guidelines I am also ok to go for a PR if there are no obstacles.

**Comment by ennru** [comment]
Akka 2.6 works fine with Pub/Sub gRPC. 

You need to pull up the version of Akka Discovery to the Akka version you use.
Eg. shown in https://doc.akka.io/docs/alpakka/current/google-cloud-pub-sub-grpc.html#artifacts

(You might need to fix the grpc-auth dependency, as well. See https://github.com/akka/alpakka/pull/2420/files)

**Comment by gkatzioura** [comment]
I confirm that handling the dependencies as show on https://doc.akka.io/docs/alpakka/current/google-cloud-pub-sub-grpc.html#artifacts and fixing the grpc-auth dependency works.
