### ISSUE TITLE
Dependency incompatibilities in alpakka 2.0.2

### ISSUE THREAD

**Issue by DanieleSassoli** [akka/alpakka#2428]
### Versions used 

Akka version: 2.6.9 (But I've experienced it with 2.6.4 and 2.6.8, haven't tried other versions)

### Expected Behavior

When I upgrade from alpakka 2.0.1 to 2.0.2 I would expect to not have incompatibility issues with other akka dependencies.

### Actual Behavior

Once I upgraded I got
```  
java.lang.IllegalStateException: You are using version 10.2.0 of Akka HTTP, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 10.2.0 of the [akka-http-spray-json, akka-parsing, akka-http2-support, akka-http-xml, akka-http-core] artifacts to your project
```
I then inspected the dependency tree and could see that alpakka itself was importing old versions of this module(10.1.11)

### Relevant logs

This is the output of the plugin I use to browse the dependencies ("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
<img width="629" alt="Screenshot 2020-09-23 at 16 56 04" src="https://user-images.githubusercontent.com/4007741/94037842-aeb58780-fdbd-11ea-9dd2-f3e3aa67d4be.png">

I could work around this by explicitly importing newer versions of all the mentioned libraries but I don't believe this is desirable.

**Comment by ennru** [comment]
The dependency setup for Alpakka S3 didn't change.
Your code needs to select a consistent version of Akka HTTP including `akka-http-xml` which is brought in by Alpakka.
We improved how we show the dependency setup in the docs recently:
https://doc.akka.io/docs/alpakka/current/s3.html#artifacts

**Comment by DanieleSassoli** [comment]
Sorry, that's my bad, I reported S3 as an example but I'm having this problem in pretty much any alpakka dependency I import(there's quite a few).
When I raised the issue I believed Akka HTTP 10.2.0 was brought in by another akka/alpakka library in my project, after having a second look it seems like `de.heikoseeberger/akka-http-circe` is the one bringing in the latest akka HTTP.

I've managed to work around the issue in the way described in the link you provide, so I'm happy to close this issue, but I would have expected alpakka to be up to date with akka dependencies?

**Comment by raboof** [comment]
> I would have expected alpakka to be up to date with akka dependencies?

The backstory is that we *support* the latest Akka HTTP version, but we don't *require* it.

In practice this means we depend on the latest Akka HTTP versions we *support* (10.1.11), and that's what you'll get when you don't do anything else. Since Akka HTTP provides binary compatibility, everything still works fine when you upgrade to a newer version in your project (i.e. 10.2.0), but as you noticed you'll have to make sure you update all submodules.

It would be great to have a way to automatically 'pull up' the other submodules when you update one, but we haven't found a nice way to achieve that.
