### ISSUE TITLE
IOException: Error accessing /home/travis/.cache

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#2436]
https://travis-ci.com/github/akka/alpakka/jobs/395191944
```
java.io.IOException: Error accessing /home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/cats-kernel_2.13/2.0.0/cats-kernel_2.13-2.0.0.jar
[error] 	at scala.reflect.io.FileZipArchive.scala$reflect$io$FileZipArchive$$openZipFile(ZipArchive.scala:169)
[error] 	at scala.reflect.io.FileZipArchive.root$lzycompute(ZipArchive.scala:207)
[error] 	at scala.reflect.io.FileZipArchive.root(ZipArchive.scala:204)
[error] 	at scala.reflect.io.FileZipArchive.allDirs$lzycompute(ZipArchive.scala:240)
[error] 	at scala.reflect.io.FileZipArchive.allDirs(ZipArchive.scala:240)
[error] 	at scala.tools.nsc.classpath.ZipArchiveFileLookup.findDirEntry(ZipArchiveFileLookup.scala:79)
[error] 	at scala.tools.nsc.classpath.ZipArchiveFileLookup.list(ZipArchiveFileLookup.scala:66)
[error] 	at scala.tools.nsc.classpath.ZipArchiveFileLookup.list$(ZipArchiveFileLookup.scala:65)
[error] 	at scala.tools.nsc.classpath.ZipAndJarClassPathFactory$ZipArchiveClassPath.list(ZipAndJarFileLookupFactory.scala:58)
```

**Comment by raboof** [comment]
Also at https://travis-ci.com/github/akka/alpakka/jobs/395060547

**Comment by raboof** [comment]
My guess is that an invalid zip somehow ended up in the cache. Unfortunately it doesn't seem possible to inspect the cache manually, plus it seems (?) deleted now. Weird that apparently downloading a dependency is not atomic and/or the checksum is not checked?

**Comment by raboof** [comment]
hum it's still there after clearing the cache... something that got cached incorrectly in travis' cache then?

**Comment by raboof** [comment]
now it stopped failing on master too :/

**Comment by seglo** [comment]
FYI I deleted the travis cache for master yesterday.  Not sure if that had any affect with your troubleshooting.

**Comment by raboof** [comment]
> FYI I deleted the travis cache for master yesterday. Not sure if that had any affect on your troubleshooting.

thx - possibly, but I really thought I saw the failure even after I cleared all travis caches myself at some point yesterday...
