### ISSUE TITLE
Pravega setting builder issue.

### ISSUE THREAD

**Issue by cheleb** [akka/alpakka#2441]
### Versions used 

Akka version: 

### Expected Behavior
keyExtractor is never set by the builder.

Please describe the expected behavior of the issue, starting from the first action.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

routing key extractor is never set from the Builder

### Relevant logs

If you identified a section in your logs that explains the bug or might be important to understand it, please add it.

### Reproducible Test Case

Please provide a PR with a failing test.

If the issue is more complex or requires configuration, please provide a link to a project that reproduces the issue.

**Comment by ennru** [comment]
Fixed with #2442
