### ISSUE TITLE
S3: Class ADT for BucketAccess

### ISSUE THREAD

**Issue by Yomanz** [akka/alpakka#2443]
### Versions used 
```scala
  "com.lightbend.akka" %% "akka-stream-alpakka-s3" % "2.0.2",
  "com.typesafe.akka" %% "akka-stream" % "2.5.31",
  "com.typesafe.akka" %% "akka-http" % "10.1.11",
  "com.typesafe.akka" %% "akka-http-xml" % "10.1.11",
```
### Expected Behavior

You're able to match `BucketAccess` like 
![image](https://user-images.githubusercontent.com/5119107/95502799-4c09e180-09a2-11eb-8e4f-d76cc47f8b47.png)

### Actual Behavior

You need to match `_` because its a sealed class instead of a trait
![image](https://user-images.githubusercontent.com/5119107/95503537-6b553e80-09a3-11eb-8ede-a687caf8fe91.png)

### Relevant logs

If you identified a section in your logs that explains the bug or might be important to understand it, please add it.

### Reproducible Test Case

```scala
def bucketAccess: BucketAccess = ???

  bucketAccess match {
    case BucketAccess.AccessDenied => println("AccessDenied")
    case BucketAccess.AccessGranted => println("AccessGranted")
    case BucketAccess.NotExists => println("NotExists")
  }
```
This causes the error:
```
Error:(80, 3) match may not be exhaustive.
It would fail on the following input: BucketAccess()
  bucketAccess match {
```

causing you to have to do:
```scala
def bucketAccess: BucketAccess = ???

  bucketAccess match {
    case BucketAccess.AccessDenied => println("AccessDenied")
    case BucketAccess.AccessGranted => println("AccessGranted")
    case BucketAccess.NotExists => println("NotExists")
    case _ => println("_ case")
  }
```

I might be missing a potential use-case but I do not understand the reason for a class based ADT

**Comment by ennru** [comment]
There is an unfinished PR about this https://github.com/akka/alpakka/pull/2366

**Comment by Yomanz** [comment]
Closed with https://github.com/akka/alpakka/pull/2513
