### ISSUE TITLE
pub/sub: connection refused

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#2448]
Interestingly both for the 'normal' and the grpc version: https://travis-ci.com/github/akka/alpakka/builds/190220863

We are using `google/cloud-sdk:latest`, perhaps something changed there?

**Comment by ennru** [comment]
Interesting indeed. That's the curse of using the latest...

```
[info] - should receive a published message and acknowledge it *** FAILED *** (68 milliseconds)
[info]   The future returned an exception of type: akka.stream.StreamTcpException, with message: Tcp command [Connect(localhost:8538,None,List(),Some(10 seconds),true)] failed because of java.net.ConnectException: Connection refused. (IntegrationSpec.scala:117)
```

**Comment by ennru** [comment]
Rolling back to an older image version makes the tests work again.

**Comment by ennru** [comment]
At least for the gRPC version the HTTP client gets nice replies:
`{"error":{"code":500,"message":"Panic! This is a bug!","status":"INTERNAL"}}`

**Comment by raboof** [comment]
> Rolling back to an older image version makes the tests work again.

Let's PR that for starters then? :)

**Comment by ennru** [comment]
Trying a bit more before PRing.
