### ISSUE TITLE
Alpakka 3.0 plans

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#2455]
## Making Alpakka 3.0 happpen

Alpakka 2.0 was released in April 2020. Why would we go for another major version?

As Alpakka depends on many third-party libraries, we need to upgrade those from time to time, even if that might bring changes to Alpakka or other code that uses those libraries. In some cases Alpakka users will use the library Alpakka brings in even directly from their code.

To make it obvious things may have changed with the new Alpakka version, we pull for a new major version.

"For major release upgrades of a library, the Alpakka team will decide case-by-case if the upgrade motivates an upgrade of the Alpakka major version.

* For source incompatible library upgrades, Alpakka will do a major version upgrade.
* If the library indicates it is considered binary-compatible, Alpakka may upgrade within a minor release." 

From https://doc.akka.io/docs/alpakka/current/other-docs/versioning.html

## Breaking APIs

As this is a major version upgrade, Alpakka may change user facing APIs. But we should be restrictive to with it so that most Alpakka 2.0 code should work even with Alpakka 3.0.

## Goals

- Upgrade third-party libraries
- Become Akka 2.6 only (Alpakka made use of manual backports of things that are available in Akka nowadays)
- Drop Scala 2.11 (will simplify code here and there)

## Issues and PRs

[3.0.0-M1 milestone](https://github.com/akka/alpakka/milestone/43)

## Pre-releases

Once some connectors have gotten refreshed for 3.0 we'll start doing milestone releases.

**Comment by mrooding** [comment]
@ennru what's the status & roadmap for moving to Alpakka 3.0? I'd be happy to help out. Not all Alpakka binaries support Akka 2.6 and it's starting to become a hassle

**Comment by seglo** [comment]
Answering on @ennru behalf since he's busy on other things these days..

Aside from outstanding issues targeting the `3.0.0-M1` milestone we also need to finish converting the rest of the connectors to use Akka 2.6. You can search for issues of the pattern "<connector>: Akka 2.6 features" to find them (these need to be updated to the `3.0.0-M1` milestone).

Any help would be greatly appreciated. I would like to issue a release soon as well!

**Comment by ennru** [comment]
Thank you @mrooding for pushing many many of the Akka 2.6 things forward!
