### ISSUE TITLE
mqtt: Akka 2.6 features

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#2490]
- [ ] Backports: If a `RetryFlow(Coordinator)` is used, remove it and use the Akka implementation
- [ ] Replace `Source.setup` / `Flow.setup` with `Source.fromMaterializer` / `Flow.fromMaterializer` 
- [ ] Tests: Use `ActorSystem` instead of `Materializer` when creating a stream
- [ ] Resolve other Akka deprecations
- [ ] Enable `fatalWarnings` for the connector
- [ ] Docs: Remove references about the `Materializer` from the text

(This is a bulk-created issue to manage updating Alpakka for the 3.0 release. Not all items apply to all connectors.)

**Comment by ennru** [comment]
Fixed with #2590

**Comment by saumilsdk** [comment]
Hi @ennru when will akka mqtt paho client will support mqtt 5.0?

**Comment by seglo** [comment]
@saumilsdk Most of the Alpakka connectors are community-maintained. At this time there are no plans to do any upgrades to the alpakka-mqtt connector in particular. If this is something you're interested in doing we can work with you to update the project.

I recall you asking about using alpakka-mqtt-streaming several weeks ago. This is the most up-to-date mqtt library. Does it support your requirements?

**Comment by seglo** [comment]
I just bumped into your comment asking about mqtt 5.0 support mqtt-streaming. Sorry.

**Comment by seglo** [comment]
MQTT 5.0 support can be tracked here: https://github.com/akka/alpakka/issues/2622

**Comment by saumilsdk** [comment]
> @saumilsdk Most of the Alpakka connectors are community-maintained. At this time there are no plans to do any upgrades to the alpakka-mqtt connector in particular. If this is something you're interested in doing we can work with you to update the project.
> 
> I recall you asking about using alpakka-mqtt-streaming several weeks ago. This is the most up-to-date mqtt library. Does it support your requirements?

@seglo You are right about me asking for mqtt-streaming TLS related doubts. In regards to this issue, I am more looking for mqtt paho connector and not the mqtt-streaming for MQTT v5 support. I am definitely interested in v5 client as it has magnitude of features and paho seems to support it with there [photon release](https://projects.eclipse.org/projects/iot.paho/releases/1.4.0-photon)

As this upgrade doesn't seem to require much changes I was hoping if this can be done, it will attract lot more features and usage.

**Comment by huntc** [comment]
> As this upgrade doesn't seem to require much changes I was hoping if this can be done, it will attract lot more features and usage.

Pull requests are very welcome!
