### ISSUE TITLE
s3: Akka 2.6 features

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#2494]
- [x] Backports: If a `RetryFlow(Coordinator)` is used, remove it and use the Akka implementation
- [x] Replace `Source.setup` / `Flow.setup` with `Source.fromMaterializer` / `Flow.fromMaterializer` 
- [x] Tests: Use `ActorSystem` instead of `Materializer` when creating a stream
- [x] Resolve other Akka deprecations
- [x] Enable `fatalWarnings` for the connector
- [x] Docs: Remove references about the `Materializer` from the text

(This is a bulk-created issue to manage updating Alpakka for the 3.0 release. Not all items apply to all connectors.)

**Comment by ennru** [comment]
Fixed with #2513

**Comment by mirkof** [comment]
Hello @ennru,

Are there any plans to release this version with akka 2.6? 
I have a dependency on alpakka-s3, and keeping everything on 2.5 just for this library is really taking it's toll... :(

**Comment by seglo** [comment]
@mirkof Yes, see https://github.com/akka/alpakka/issues/2455#issuecomment-790126382
