### ISSUE TITLE
[XML] XML parsing exceptions (e.g. WFCException) should cleanly fail the XmlParsing stage rather than go unhandled

### ISSUE THREAD

**Issue by jphelp32** [akka/alpakka#2532]
In the XmlParsing stage, if any parsing error occurs, the exception from the underlying aalto parser goes unhandled and fails the stage. As a result, the exception is always logged at the ERROR log level by akka's logger. I think the better approach would be to catch all parsing exceptions and fail the stage cleanly via `failStage(ex)`, so that the exception is not automatically logged, and consumers of the XmlParsing stage can determine how to react wrt to logging.

**Comment by ennru** [comment]
Thank you for this suggestion, sounds reasonable.
Please feel free to suggest these changes in a Pull Request.

**Comment by ennru** [comment]
Fixed with #3003
