### ISSUE TITLE
AWS S3: discrete requests should also be retried on exceptions

### ISSUE THREAD

**Issue by bpiper** [akka/alpakka#2535]
### Versions used 

2.0.2

Akka version: 2.6.7

### Expected Behavior

S3 requests that use S3Stream.signAndRequest should retry on exceptions (e.g. connection resets, which are not uncommon with Amazon S3 - or perhaps could be symptomatic of some obscure Akka HTTP issue) as well as 5xx HTTP responses.

### Actual Behavior

Requests fail immediately in the event of an exception.

I had been wondering why on some occasions my multipart uploads would fail with an akka.http.impl.engine.client.OutgoingConnectionBlueprint$UnexpectedConnectionClosureException (basically a connection reset) despite the part uploads using retry logic that covers both 5xx HTTP errors and IO exceptions. I then realised that it could actually be the multipart upload initiation or even completion requests that were failing, which was more or less confirmed by the fact that I couldn't see any incomplete multipart upload requests in the bucket (because they'd never been successfully initiated).

I think it makes sense to just use RetryFlow in signAndRequest, similar to how it's used for the part uploads.  I'm just testing this change now and will likely submit a PR in the not too distant future.

**Comment by seglo** [comment]
Implemented in #2536
