### ISSUE TITLE
FTP: incorrect credentials should raise UserAuthException

### ISSUE THREAD

**Issue by polentino** [akka/alpakka#2541]
### Versions used 

Alpakka Ftp version: 2.0.2
Akka version: 2.5.26
Scala version: 2.12.11
Testcontainers version: 1.14.3

### Expected Behavior

In our test, we use [Testcontainers](https://www.testcontainers.org/) and [pure-ftpd docker container](https://hub.docker.com/r/stilliard/pure-ftpd/) to provide a simple ftp server to run our tests with. The server has one user, `foo`, with password `bar`. When I try to run a simple `Ftp.ls().runWith(Sink.seq)` against that server, using wrong credentials, I would expect it to return a failed Future containing `UserAuthException`, but it actually never throws.
In the small example below, I'd expect to recognize the `UserAuthException` and close both the container and actor system; instead, it hangs until it times out.
What's more strange is that I have enabled protocol command tracing, and indeed i can see `530 Login authentication failed` .

### Actual Behavior

When the username/password is incorrect, `Ftp.ls().runWith(Sink.seq)` should complete with a failed Future containing  `UserAuthException`.

### Relevant logs

```
USER foo
331 User foo OK. Password required
PASS wrong password
530 Login authentication failed
TYPE I
200 TYPE is now 8-bit binary
SYST
215 UNIX Type: L8
PASV
530 You aren't logged in
QUIT
221-Goodbye. You uploaded 0 and downloaded 0 kbytes.
221 Logout.
```

### Reproducible Test Case

```
import java.io.PrintWriter
import java.net.InetAddress

import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.alpakka.ftp.scaladsl.Ftp
import akka.stream.alpakka.ftp.{FtpCredentials, FtpFile, FtpSettings}
import akka.stream.scaladsl.Sink
import com.github.dockerjava.api.model.{ExposedPort, PortBinding, Ports}
import net.schmizz.sshj.userauth.UserAuthException
import org.apache.commons.net.PrintCommandListener
import org.apache.commons.net.ftp.FTPClient
import org.testcontainers.containers.GenericContainer

import scala.concurrent.Future

object Main extends App {

  implicit val as = ActorSystem.create("test")
  implicit val ec = as.dispatcher
  implicit val mat = ActorMaterializer()

  val container = new GenericContainer()
  container.setDockerImageName("stilliard/pure-ftpd:hardened")
  container.withEnv("PUBLICHOST", "localhost")
  container.withEnv("FTP_USER_NAME", "foo")
  container.withEnv("FTP_USER_PASS", "bar")
  container.withEnv("FTP_USER_HOME", "/home/foo")
  // Testcontainers by default randomize ports, but that messes up with PASV
  container.withCreateContainerCmdModifier(e => {
    val bindings = (0 until 10) map { idx =>
      val port = 30000 + idx
      new PortBinding(Ports.Binding.bindPort(port), new ExposedPort(port))
    }
    e.withPortBindings(bindings: _*)
  })
  container.start()

  val settings = FtpSettings
    .create(InetAddress.getByName("localhost"))
    .withPort(container.getMappedPort(21))
    .withCredentials(FtpCredentials.create("foo", "wrong password"))
    .withBinary(true)
    .withPassiveMode(true)
    .withConfigureConnection((ftpClient: FTPClient) => {
      ftpClient
        .addProtocolCommandListener(new PrintCommandListener(new PrintWriter(System.out), false))
    })

  val result: Future[Seq[FtpFile]] = Ftp.ls("/", settings).runWith(Sink.seq)
  result.failed.map {
    case x: UserAuthException =>
      container.stop()
      as.terminate()
  }
}
```

**Comment by ennru** [comment]
Thank you for this report.
Would you be in a position to suggest the necessary changes to improve this?

**Comment by polentino** [comment]
Hi @ennru , I have no experience with the codebase sadly; the reason why I know which exception should have been thrown, is because of this previous ticket https://github.com/akka/alpakka/issues/397

**Comment by polentino** [comment]
I decided to give it a go, but still downloading all the necessary docker-compose containers. On the plus side, I noticed it's using the very same ftp container I've used in the snippet here, albeit with fewer options :)

**Comment by ennru** [comment]
You don't need to run all things in Alpakka.

`docker-compose up -d ftp sftp squid`
`sbt ftp/test`

is enough.

**Comment by polentino** [comment]
@ennru question: how am I supposed to run the tests? 
I'm asking because, despite using branch `release-2.0` and running `docker-compose up` before executing `sbt test`, I cannot get a first green run, because the whole process crash:
```
Uncaught error from thread [SourceSpec-akka.actor.default-dispatcher-2]: org/slf4j/LoggerFactory, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[SourceSpec]
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
```

 And if I try to run the tests from the `ftp` subproject, not all tests pass
```
[info] Run completed in 1 minute, 20 seconds.
[info] Total number of tests run: 140
[info] Suites: completed 7, aborted 0
[info] Tests: succeeded 44, failed 96, canceled 0, ignored 6, pending 0
[info] *** 96 TESTS FAILED ***
```

**Comment by polentino** [comment]
Well, this is weird:
```
[info] ScalaTest
[info] Run completed in 1 minute, 1 second.
[info] Total number of tests run: 140
[info] Suites: completed 7, aborted 0
[info] Tests: succeeded 44, failed 96, canceled 0, ignored 6, pending 0
[info] *** 96 TESTS FAILED ***
```
lots of `java.nio.file.AccessDeniedException: tmp/home/sample_dir_/sample_dir_592000000`

**Comment by ennru** [comment]
Looking into it, there is https://github.com/akka/alpakka/issues/1810
