### ISSUE TITLE
S3: Discussion on Single Request vs Connection Pool 

### ISSUE THREAD

**Issue by Scalahansolo** [akka/alpakka#256]
While digging around in the S3 code I noticed that it uses a single request for all requests that come through. https://github.com/akka/alpakka/blob/master/s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala#L223. 

Should this not be using the pattern outlined at http://doc.akka.io/docs/akka-http/10.0.5/scala/http/client-side/host-level.html#using-the-host-level-api-with-a-queue so we end up using a the same pool instead of re-creating a connection over and over in the same client?

**Comment by 2m** [comment]
`singleRequest` uses the [cached default host connection pool](https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala#L526-L535).

**Comment by Scalahansolo** [comment]
Ahh okay. That makes sense. Ill close this out.
