### ISSUE TITLE
DirectoryChangesSource not capturing changes from network share

### ISSUE THREAD

**Issue by jorkzijlstra** [akka/alpakka#2565]
### Versions used 

Akka version: 2.6.10
Akka Stream Alpakka File: 2.0.2

### Expected Behavior

We are using the DirectoryChangesSource on a local directory which is a mount point for a network share. We are expecting that changes on that network share will propagate into the DirectoryChangesSource.

### Actual Behavior

When making a change to that directory from the same system as where the DirectoryChangesSource is running a change event is being triggered.
When a change is made to the same network directory from a different system nothing is triggered. The `doPoll` method doesn't see an event.

### Reproducible Test Case

```
val networkSharePath = Paths.get("/mnt/share")
implicit val system: ActorSystem = ActorSystem()
Source.single()
  .flatMapConcat(_ =>
    Directory
      .walk(networkSharePath)
      .flatMapMerge(Int.MaxValue, asDirectoryChangeSource)
  )
  .runWith(Sink.foreach { case (path, _) => logger.info(s"Change event for path: ${path.toAbsolutePath.toString}")})

private def asDirectoryChangeSource(path: Path): Source[(Path, DirectoryChange), NotUsed] = {
  logger.info(s"Capturing changes for: ${path.toString}")

  DirectoryChangesSource(
    path,
    pollInterval = 250 millis,
    maxBufferSize = 10000
  )
}
```

Make a change to the networkSharePath directory from a different system then where this is running and see no change flowing through.

**Comment by jorkzijlstra** [comment]
We suspect that the CIFS network mount might be the cause, but have found no fix yet

**Comment by seglo** [comment]
The `DirectoryChangesSource` implementation uses the Java standard library [`java.nio.file.WatchService`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/WatchService.html) to detect filesystem changes. The `WatchService` relies on the native platform's capabilities when it comes to file system events.

In the platform dependencies section of its javadocs it states:

> If a watched file is not located on a local storage device then it is implementation specific if changes to the file can be detected. In particular, **it is not required that changes to files carried out on remote systems be detected.**

If the `WatchService` isn't picking up remote file system events for your share then I'm not sure there's any way to support it as it depends on the platform you're running on.

**Comment by jorkzijlstra** [comment]
Thanks for replying.

We did indeed do some more research and indeed the system does not get notified. We found lots of articles describing this particular issue. We also explored the source code a bit and the DirectoryChangesSource does not support poll based changes which would be a solution to work with Windows shared drives.

To work around this we first tried:
Expand https://hub.docker.com/r/coppit/inotify-command with rsync which can monitor on pull basis, then rsync the data to a local directory on which the DirectoryChangesSource can natively listen.
This setup seemed to work, but was found to complex with the downside that we are copying all data which is more than a couple of Gb's.

The second solution, which we are going for, is setting up a sync to an S3 bucket. Adding an SQS Queue to get the notifications  and switch implement to the SQSSource.

**Comment by seglo** [comment]
> We also explored the source code a bit and the DirectoryChangesSource does not support poll based changes which would be a solution to work with Windows shared drives.

If this is something you are interested in prototyping it's possible we could include it in Alpakka in a future release.  Do you have bandwidth for a PR?
