### ISSUE TITLE
Google cloud storage: upload gzipped data

### ISSUE THREAD

**Issue by Fattouh92** [akka/alpakka#2571]
### Short description
Support gzipped uploads so files are eligible for automatic decompression when downloading 

### Details
GCS supports automatic decompression "transcoding" when downloading files out of the box given that the stored file is gzipped and has the Content-Encoding: gzip meta set. the requester has the possibility to opt out using Accept-Encoding: gzip. so imo this would be a plus to everyone. Currently the alpakka API does not support setting Content-Encoding. Would like to implement a new upload func that accepts the encoding and sends to GCS while writing as the http API does https://cloud.google.com/storage/docs/json_api/v1/objects/insert

I will investigate the project and how to implement but any help is welcome as I am really new here
Thank you

**Comment by seglo** [comment]
Sounds interesting. Please go ahead and submit a PR. Let me know if you need any assistance.

**Comment by Fattouh92** [comment]
Thanks a lot for the response. I found this PR https://github.com/akka/alpakka/pull/2551 which covers this issue as contentEncoding can be passed as part of the metadata

**Comment by seglo** [comment]
Of course!
