### ISSUE TITLE
Update jwt-core

### ISSUE THREAD

**Issue by seglo** [akka/alpakka#2580]
> Consider bumping the version for the entire Alpakka project? The latest is 4.2.0. The jump from 3 to 4 is apparently ["not really a breaking change release."](https://github.com/pauldijou/jwt-scala/releases/tag/v4.0.0)

https://github.com/akka/alpakka/pull/2548/files#r546329347

**Comment by armanbilge** [comment]
The new name is [jwt-scala](https://github.com/jwt-scala/jwt-scala) which is currently up to 7.1.3.

**Comment by armanbilge** [comment]
It turns out `google-common` is the only module that currently depends on `jwt-scala`, which is up-to-date, so actually we can close this issue.
