### ISSUE TITLE
Support of partial file download from S3

### ISSUE THREAD

**Issue by thereisnospoon** [akka/alpakka#264]
It would be great to have an ability to create stream for download only of a given bytes range of a file.

**Comment by johanandren** [comment]
As far as I understand, the range is just headers, would be good if this was solved the same way as #254, allowing for more custom headers to be added without changing the API every time. WDYT @thereisnospoon ?

**Comment by jrudolph** [comment]
Fixed by #265.

**Comment by jrudolph** [comment]
@johanandren not sure if the range header is as general as the ones tackled in #254. AFAICS the range header is mostly relevant for downloads so it seems to fit somewhat well here. The header added in #254 seemed to be more meta-level headers so it makes sense to configure them in a single place.

**Comment by johanandren** [comment]
Alright, thanks for clarifying @jrudolph
