### ISSUE TITLE
XmlParser throws exceptions when source is empty

### ISSUE THREAD

**Issue by moqichenle** [akka/alpakka#2655]
Hi, I m new to akka streams and I was trying the XML parser: https://doc.akka.io/docs/alpakka/current/data-transformations/xml.html

```
Source.empty[ByteString]
  .via(XmlParsing.parser)
  .toMat(Sink.seq)(Keep.right)
```
is throwing the exception ```IllegalStateException  Stream finished before event was fully parsed```
which is an odd behavior to me. 
I thought an empty source has nothing to emit and it will just complete.
How can I make it work with empty source? thank you

**Comment by ennru** [comment]
Fixed with #2658
