### ISSUE TITLE
[Google-FCM] Add additional properties for Android Notifications

### ISSUE THREAD

**Issue by Draigs** [akka/alpakka#2659]
At the moment only the most important properties of AndroidNotification are supported for sending messages to Android devices. Would be nice to add the missing properties defined in https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification

Another option to make the implementation more flexible would be to use a Map instead of a pre-defined object (AndroidNotification) similar to the implementation for APNS. What do you think of it?

**Comment by ennru** [comment]
Implemented with #2685
