### ISSUE TITLE
DB query not executing with alpakka slick

### ISSUE THREAD

**Issue by ramakrishna-hande** [akka/alpakka#2691]
Below is my code 

def main(args: Array[String]): Unit = {

    implicit val system: ActorSystem = ActorSystem()
    implicit val mat: ActorMaterializer = ActorMaterializer()
    implicit val ec: ExecutionContextExecutor = system.dispatcher
    val log = LoggerFactory.getLogger(this.getClass)
    implicit val session: SlickSession = SlickSession.forConfig("my-mysql")
    import session.profile.api._
    val eventualSessionCount = session.db.run(sql"""select count(*) from mytable  where user ='Ramakrishna';""".as[Int])
    eventualSessionCount.map {
      count =>
        log.info("Number of active connections before closing the session" + count)
        session.close();
      }
     }
    }

My applicarion conf looks like this 

       my-mysql{
              profile = "slick.jdbc.MySQLProfile$"
               dataSourceClass = "slick.jdbc.DatabaseUrlDataSource"
            db = {
                  driver = "com.mysql.jdbc.Driver"
                  numThreads = 10
                 connectionPool = disabled
                   # Need to provide these as environment variables
                 url = ${?DB_URL}
                user = ${?DB_USER}
                  password = ${?DB_PASSWORD}
               }
            }

However my code does not log this

      log.info("Number of active connections before closing the session" + count)

 and keeps hung forever.

The scala version I am using is 2.11 and I am using 

akka-stream-alpakka-slick_2.11-1.0-M1.jar

Is this code not terminating is a bug ? Or Am I missing anything ? 

Thanks in advance

**Comment by ennru** [comment]
Thank you, @ihostage.

For questions like this, please use [the forum](https://discuss.lightbend.com/c/akka/).
