### ISSUE TITLE
Add ability to perform generic http requests to S3 via S3Client API

### ISSUE THREAD

**Issue by thereisnospoon** [akka/alpakka#271]
Often there is a need to perform various http requests to S3 except for data upload and download (e.g. remove a key from a bucket, list buckets, list keys etc). In order to do these requests you need to parse application config for S3 related properties such as access-key, region and so on.

It would be convenient to reuse `S3Client` from Alpakka for such requests which already encapsulates parsed S3 connection properties. I suggest refactoring `S3Client.request(bucket, key)` method (which actually makes GET request for download of data by given key and bucket) to something like this:

`S3Client.request(request: HttpRequest): Future[HttpResponse]`

This method should change uri of given request according to S3 connection properties from app configuration and add authorization header to request.

I'm ready to implement this change and would like to discuss any concerns / implementation details.

**Comment by 2m** [comment]
I agree that giving access to the lower level APIs is useful. Common usecases then can be implemented using that and if common and general enough can be contributed back to Alpakka.

**Comment by zaharidichev** [comment]
Just to be clear, Is this just a matter of preprocessing the Raw HTTP Request and signing it, with the credentials and then fire-ing away. Nothing more ?

**Comment by thereisnospoon** [comment]
@zaharidichev Yes, you are right. Sorry for such a big delay in my response.

**Comment by francisdb** [comment]
This is still a valid issue, the current raw request only allows GET.

**Comment by fmsbeekmans** [comment]
It looks like this is supported now so this issue can be closed.

**Comment by ennru** [comment]
Thank you for pointing it out.
