### ISSUE TITLE
Alpakka Google doesn't resolve path to the well-known credentials file

### ISSUE THREAD

**Issue by marcelmojzis** [akka/alpakka#2711]
### Versions used 

Akka version: 2.6.15
Alpakka version: 3.0.2

### Expected Behavior

`alpakka.google.credentials.service-account.path` should resolve to the default location of the credentials file.

### Actual Behavior

Configuration of `alpakka.google.credentials.service-account.path` in `reference.conf` contains "relative" field `path` in substitutions (see https://github.com/akka/alpakka/blob/master/google-common/src/main/resources/reference.conf#L24) and it resolves to an invalid value. The following change should fix the problem:

```
alpakka.google {
  credentials {
    service-account {
      path = ${user.home}/.config
      path = ${?APPDATA} # Windows-only
      path = ${alpakka.google.credentials.service-account.path}/gcloud
      path = ${?CLOUDSDK_CONFIG}
      path = ${alpakka.google.credentials.service-account.path}/application_default_credentials.json
      path = ${?GOOGLE_APPLICATION_CREDENTIALS}
    }
  }
}
```

Marcel

**Comment by ennru** [comment]
Great find. Would you be able to suggest this change in a PR?
