### ISSUE TITLE
Upload large files to ftp

### ISSUE THREAD

**Issue by jtargui** [akka/alpakka#2737]
Hi!

Alpakka ftp is working perfectly uploading files to ftp. This is my code:

  val bytes = Files.readAllBytes(origin.toPath)
  val jobSuppliers = Source.single(ByteString(bytes)).runWith(Ftp.toPath(destinyFile, ftpSet))
  Await.result(jobSuppliers, timeout)

I've a doubt trying to upload a large file (200M or more). Of course, I can't read a big file and send to ftp. I will get "java.lang.OutOfMemoryError"...

Is there an alternative with inputStream or similar? I couldn't find the solution my self. Meanwhile I'm using the typical org.apache.commons.net.ftp.FTPClient

Thanks a lot for your help.

**Comment by ennru** [comment]
Yes there is. You compose Akka Stream components to achieve that.
Have a look at https://doc.akka.io/docs/akka/current/stream/stream-io.html#streaming-file-io

Please post these kinds of questions on the https://discuss.lightbend.com/c/akka/5 forum instead.
