### ISSUE TITLE
Google Pubsub GRPC Connector bundled certificate is no longer valid

### ISSUE THREAD

**Issue by MichelEdkrantz** [akka/alpakka#2738]
Hi, 
The certificate bundled with the Google Pub/Sub GRPC connection, GSR2.crt, seems not to work anymore. 

We are running alpakka 2.0.0, but the same certificate is also bundled in later versions.  

We got bitten hard in production last week, with apps starting to fail with SSL errors. Last Wednesday we saw errors from 
zone europe-west1-c, and on following Thursday, also the D zone started failing. 

This seems to not be the default config anymore, which is good. It should probably be stated somewhere in the docs that it will no longer work. I hope nobody else has to experience this. After changing to rootCa = none in the config, it worked again. 

It typically manifest like this: 

`message | Restarting graph due to failure. stack_trace:  io.grpc.StatusRuntimeException: UNAVAILABLE: io exception Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0] 	at io.grpc.Status.asRuntimeException(Status.java:533) 	at akka.grpc.internal.UnaryCallAdapter.onClose(UnaryCallAdapter.scala:40) 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) 	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 	at java.base/java.lang.Thread.run(Thread.java:829) Caused by: javax.net.ssl.SSLHandshakeException: No trust manager was able to validate this certificate chain: # of exceptions = 1 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131) 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349) 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292) 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287) 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654) 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473) 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369) 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443) 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074) 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061) 	at java.base/java.security.AccessController.doPrivileged(Native Method) 	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008) 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1494) 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.access$1900(SslHandler.java:166) 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler$SslTasksRunner.run(SslHandler.java:1681) 	... 3 more Caused by: com.typesafe.sslconfig.ssl.CompositeCertificateException: No trust manager was able to validate this certificate chain: # of exceptions = 1 	at com.typesafe.sslconfig.ssl.CompositeX509TrustManager.checkServerTrusted(CompositeX509TrustManager.scala:89) 	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1524) 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632) 	```

**Comment by ennru** [comment]
Thank you for reporting. Sorry that it didn't get discovered before it hit you.

Would you be in a position to send a PR for the docs and the default config?
