### ISSUE TITLE
S3: Suggestions on how to modify multipart upload to signal successful chunk upload?

### ISSUE THREAD

**Issue by mdedetrich** [akka/alpakka#2760]
For context + general discussion here is the relevant lightbend discord thread https://discuss.lightbend.com/t/committing-a-kafka-cursor-after-chunk-upload-on-multipart-s3-upload/8941.

I currently have a problem where as a client/user I need to know whenever a `S3.multipartUpload` successfully uploads a chunk and to act upon it. In my case specifically I want to upload Kafka commit information when a chunk/part has been uploaded into S3 (as well as when the multipart upload finishes but this is possible to figure out currently).

With the current API this does not appear to be possible since the all of the chunk/part handling is abstracted away, i.e. https://github.com/akka/alpakka/blob/master/s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala#L849-L855 only takes `Sink[ByteString, Future[MultipartUploadResult]]`.

One idea I had in mind is to provide an alternate implementation (also mentioned in the lightbend thread) that looks like this

```scala
def multipartUploadWithContext[T](
    s3Location: S3Location,
    contentType: ContentType = ContentTypes.`application/octet-stream`,
    s3Headers: S3Headers,
    chunkSize: Int = MinChunkSize,
    chunkingParallelism: Int = 4,
    chunkUploadSink: UploadPartResponse => Sink[T, NotUsed]
): Sink[(ByteString, T), Future[MultipartUploadResult]]
```

Here the `T` represents some context (in my case specifically its Kafka commit information) and the `chunkUploadSink` is a function that takes `UploadPartResponse` as an input (currently this is private so one solution is to make it public, it contains the result of a chunk/part upload i.e. such as if its successful or failed) and then as an output you have to provide a `Sink[T, NotUsed]` that defines what to do with that `T` (in my case commit the latest applicable Kafka cursor context). Basically the `chunkUploadSink` is like a callback that gets triggered whenever a chunk is uploaded.

It would also possible to just change `multipartUpload` to the above implementation since you can just define `T` as `NotUsed` and provide a a `chunkUploadSink` that doesn't do anything (or just make `chunkUploadSink` optional with `Option`).

Any thoughts?

**Comment by johanandren** [comment]
From reading this and peeking at the suggestion PR I have a hard time figuring out if something like this would be useful in general to Alpakka S3 users or if it is more a specific need for your particular use case. If it is the latter it would be better if the API had enough lower level primitives to let you build the advanced special use cases rather than provide a specific solution for the problem out of the box.

**Comment by mdedetrich** [comment]
The intention is definitely the former, i.e. I want it to be generic enough that other Alpakka S3 users could find it useful, the way I see it is that the change exposes the chunking mechanism specifically for the cases where you need to know about chunking.

> If it is the latter it would be better if the API had enough lower level primitives to let you build the advanced special use cases rather than provide a specific solution for the problem out of the box.

I also had this thought, but I realized I would just be needlessly re-implementing 90% of Alpakka S3 using these low level primitives (this is actually the same reason why there is boilerplate in the PR which is something I can remove, I just wanted feedback before spending time on it). All of the flows/chunking/signing etc etc is shared, the only real complication/s comes from

- Context propagation: i.e. no `Sink.withContext` and usability issues due to https://github.com/akka/akka/issues/28431 which basically means a lot of the specific code for this problem is just shuffling tuples around as you pass the cursor context/s. Since (I think) re-ordering is not actually needed, if these usability issues with context propagation was resolved I think a lot of the core internal logic can be shared by just using `FlowWithContext`/`SinkWithContext`/`SourceWithContext` and using `Nothing` for `Context` when its not needed
- Buffering: As mentioned in the PR this can actually be supported for my use-case but only in-memory buffering unless I add a `Context => Bytestring`/`Flow[Context, ByteString, NotUsed` as a parameter to the API.

Personally I think I found the right balance for something thats generic enough so its useful for other people while at the same time not needing to expose that much of the Alpakka internals (i.e. only `UploadPartResponse` was made public).

**Comment by johanandren** [comment]
Ok, thanks for the details. Let's go with the suggestion in the PR based on this.

**Comment by ennru** [comment]
Support for this was implemented by @mdedetrich in @2770.
