### ISSUE TITLE
Cassandra driver version bump 4.10 -> 4.11.0

### ISSUE THREAD

**Issue by GeluOltean** [akka/alpakka#2762]
### Short description

Update the Datastax Java driver. 

### Details

The current Datastax Java driver version is 4.10; 4.11 is backwards compatible while adding support for Cassandra's native protocol version 5 as well as the ability to add metric tags. The latter sounds particularly powerful. 

Looks like there's an issue (https://github.com/akka/alpakka/issues/2556) relating to Cassandra, not sure if that should be resolved first, but I'd like to open a PR with the updated version.

**Comment by ennru** [comment]
See an upgrade to 4.13.0 in #2804

**Comment by ennru** [comment]
Fixed by #2804
