### ISSUE TITLE
S3 + anonymous requests + Oracle Cloud's Object Storage S3 API

### ISSUE THREAD

**Issue by marcelmojzis** [akka/alpakka#2763]
### Versions used 

Akka version: 2.6.17
Alpakka version: 3.0.3

### Expected Behavior

Would be great if Oracle Cloud's Object Storage could be accessed anonymously via Amazon S3 Compatibility API

### Actual Behavior

Anonymous access to a bucket works OK when using AWS Java SDK, however current version of Alpakka fails to complete the same operation (response contains the following message: The secret key required to complete authentication could not be found. The region must be specified if this is not the home region for the tenancy). 

The only difference between the two requests is that the former is not signed (AWS SDK skips signing requests for [AnonymousAWSCredentials](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS3Signer.java#L65)) and the latter is signed (`Authorization: AWS4-HMAC-SHA256 Credential=null/20211026/eu-frankfurt-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=eec1aec...`).

[AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html) vaguely states that *For anonymous requests this* (Authorization) *header is not required*. 

If the current behaviour is not a bug, would it make sense to add a setting controlling whether anonymous requests are signed?

**Comment by ennru** [comment]
Implemented with a new setting in #2767
