### ISSUE TITLE
KinesisFlow has no handling of messages in a failed batch

### ISSUE THREAD

**Issue by hagerf** [akka/alpakka#2814]
I am currently writing an Akka Streams app reading from RabbitMQ and publishing to Kinesis. I am using `KinesisFlow.withContext[T]` for writing so that I can ack messages back to RabbitMQ as they are written to Kinesis. I also use `RestartFlow` so that the app doesn't crash immediately when some connection fails or so.

However, I at times noticed that the app stopped consuming messages from Rabbit and was just stuck. I figured out that it happened as soon as the `KinesisFlow` was restarted after a failed batch write. The issue is that the `KinesisFlow.withContext` will throw an error on any failed write, restarting the flow but the messages that were in the failed batch are stuck in the state `unacknowledged` from RabbitMQs point of view. So when the prefetch is filled with unacked messages, RabbitMQ will not send any more messages to the worker.

I see 2 solutions to this:

- We can make sure that the flow doesn't throw an error when writing a batch fails, and still emit some Failure messages (with the context for each message). This will change current behaviour, possibly introduce some new classes OR:
- We can add the possibility for applying some clean up of the contexts before throwing the error.

The first approach would probably be the most proper one, if it had been implemented from the beginning, but the second should be quite easy to do, without breaking any backwards compatibility.

If none of these approaches are adopted the only solution is to either let the app crash/restart (not great considering a failed batch write happens regularly), or ack messages before and live with some messages being lost (even worse)

**Comment by hagerf** [comment]
I have created a PR for the second solution, that should be a minor fix

**Comment by ennru** [comment]
Implemented with #2815

**Comment by hagerf** [comment]
@ennru As nice it is to be an Akka contributor I think I have made a mistake with the previous PR. I just discovered that still some messages are unacked in rabbit upon a failure of the client. They were much fewer than before which was why I did not find it out in the beginning. 

The issue is that if a batch fails indeed the failed batch is cleaned up by the cleanup function, however any messages that are still in the process of being batched before being sent to the client are lost. Currently if the API is adding the possibility of passing a clean-up function I believe it can be misleading for users, believing that their messages will be handled when in reality it's not true for all messages. I'm sorry I did not realize this before.

I have however created a solution that should be even nicer, allowing users to create their own flows and handling. I did this by separating the logic of the batching and the batch-writing into 2 different methods, and by adding the possibility of handling the errors in a nice way. The default stays the same, and no need for the ugly java-style overloading.

Please let me know what you think, and sorry again for any inconvenience.

**Comment by hagerf** [comment]
I'm a bit unsure if we'd like then to make the method `handlePutRecordsSuccess` non-private, as it could be useful for some cases when using the `batchingFlow` and `batchWritingFlow` to create your own custom flows. I would say yes.
