### ISSUE TITLE
[MQTT] Same client for subscribe and publish

### ISSUE THREAD

**Issue by tdroxler** [akka/alpakka#282]
Currently it seems to be impossible to use a same client for subscribe and publish, which is not convenient since we can't connect the same client twice to a MQTT broker, the second connection drop the first one.

We can't because the client is automatically created inside the mqtt `Source` and the `Sink`. 

To fit my need, I materialized the client in the `Source`. (see https://github.com/tdroxler/alpakka/commit/e83a641b18b17bf3368772836f793dd003c5c869)

So I can directly use my client to publish, but using directly the `IMqttAsyncClient` paho functions.

But this is not a clean solution, since we still can't create a `Source` and `Sink` at the same time. I don't know if you have plan to tackle this problem or maybe have some hints so I can make it cleaner and useful for others?

Thx, cheers

**Comment by 2m** [comment]
Have you tried using a different `clientId` [like so](https://github.com/akka/alpakka/blob/399b968ae5fcb003364a828226df31406fb95aa4/mqtt/src/test/scala/akka/stream/alpakka/mqtt/scaladsl/MqttSinkSpec.scala#L40). When `clientId`s are different, a second connection should not drop the first one.

**Comment by tdroxler** [comment]
Yes I tried, this is actually when I have a connection with an [auth](https://github.com/akka/alpakka/blob/399b968ae5fcb003364a828226df31406fb95aa4/mqtt/src/main/scala/akka/stream/alpakka/mqtt/Mqtt.scala#L78), as well as a [socketFactory](https://github.com/akka/alpakka/blob/399b968ae5fcb003364a828226df31406fb95aa4/mqtt/src/main/scala/akka/stream/alpakka/mqtt/Mqtt.scala#L79) that I get disconnected.
