### ISSUE TITLE
Move XML parser from akka-stream-contrib

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#283]
With Java API and docs.

**Comment by johanandren** [comment]
Isn't this superseded by the bigger json/xml-streaming-parsing ticket?

**Comment by 2m** [comment]
Eventually yes. #63 is going to have way more than this simple xmlparser from akka-stream-contrib. But in the mean time, I though I would move it here, so akka-stream-contrib can return to being GraphStages only.
