### ISSUE TITLE
Update AkkaGrpc to 2.x.x

### ISSUE THREAD

**Issue by joel-cain** [akka/alpakka#2831]
### Short description

We would like the AkkaGrpc dependency version to be updated from 1.0.0 to 2.x.x

### Details

We are trying to update sbt-akka-grpc to 2.1.3 , however this is binary incompatible with akka-stream-alpakka-google-cloud-pub-sub-grpc

**Comment by ennru** [comment]
References #2678

**Comment by ennru** [comment]
The next release will use Akka gRPC >= 2.1.4
