### ISSUE TITLE
SSE: Akka HTTP 10.2.8 changed message filtering

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#2832]
https://github.com/akka/akka-http/pull/4020 in Akka HTTP's SSE changes which messages are filtered out and breaks Alpakka SSE.

See https://github.com/akka/alpakka/pull/2820#issuecomment-1042665077

**Comment by jrudolph** [comment]
We will change the default handling back to the old behavior in 10.2.9.

**Comment by jrudolph** [comment]
Fixed in the mean by updating to akka-http 10.2.9. See #2820.
