### ISSUE TITLE
AWS S3: multipartCopy does not handle custom S3Headers correctly

### ISSUE THREAD

**Issue by jfromme** [akka/alpakka#2839]
### Versions used 

Using 2.0.2, although the code in question looks the same in the most recent version.

Akka version: 2.6.5

### Expected Behavior

When calling S3.multipartCopy() with a custom header (`x-amz-request-payer` in our case) that header should be used in all the requests associated with the copy: CreateMultipartUpload, UploadPartCopy, and CompleteMultipartUpload.

### Actual Behavior

Instead, it looks like the the custom header is only sent in an initial HeadObject request and in the CreateMultipartUpload request. It is not sent in the UploadPartCopy or CompleteMultipartUpload requests.

**Comment by ennru** [comment]
Thanks for reporting! 
Are you in a position to suggest a fix for this problem in a PR?

**Comment by jfromme** [comment]
Thanks for responding! Yes, I'll give it a try.

**Comment by ennru** [comment]
Fixed with #2844 

Thank you, @jfromme!
