### ISSUE TITLE
akka-stream-alpakka-sqs depends on  elasticmq-rest-sqs

### ISSUE THREAD

**Issue by marekzebrowski** [akka/alpakka#295]
dependency is compile time. if it is really needed it should be test-time only

**Comment by dpfeiffer** [comment]
Is someone actively working on this? @marekzebrowski?

**Comment by marekzebrowski** [comment]
I don't know. In my project I just excluded unwanted dependency:
`"com.lightbend.akka" %% "akka-stream-alpakka-sqs" % "0.8" exclude("org.elasticmq", "elasticmq-rest-sqs_2.11")`

**Comment by johanandren** [comment]
It's a small fix, please PR this if you feel like it @dpfeiffer

**Comment by dpfeiffer** [comment]
@johanandren if I remember correctly @jrudolph and @hseeberger were discussing a bugfix release for yesterday or today. Can that fix make it still in?

**Comment by johanandren** [comment]
I think it will not be released today, so likely, yes.
