### ISSUE TITLE
6.0.1 release not Java 8 compatible

### ISSUE THREAD

**Issue by jphelp32** [akka/alpakka#2994]
### Versions used 
6.0.0, 6.0.1

Appears to be a regression of issue #2680 

Seems to affect only the Enum classes. I've found these so far:
```
akka.stream.alpakka.csv.javadsl.CsvQuotingStyle
akka.stream.alpakka.xml.ParseEventMarker
```

e.g.
```
% javap -v akka.stream.alpakka.xml.ParseEventMarker | grep "major version"
  major version: 55
```

**Comment by patriknw** [comment]
Thanks for reporting. Fix in https://github.com/akka/alpakka/pull/2995
I'll try to release tomorrow.

**Comment by patriknw** [comment]
@jphelp32 6.0.2 has been released
