### ISSUE TITLE
FTP: Server encoding detection

### ISSUE THREAD

**Issue by TheDeadOne** [akka/alpakka#2998]
### Short description

Enable automatic FTP server encoding detection.

### Details

`org.apache.commons.net.ftp.FTPClient` has a `setAutodetectUTF8` method to determine if the server supports UTF-8. Enabling the detection on client creation would allow working with files that have non-Latin names.

**Comment by ennru** [comment]
Fixed with
- #2999 

Released in Alpakka 7.0.0
