### ISSUE TITLE
SQS: Allow requesting attributes for messages

### ISSUE THREAD

**Issue by lnr0626** [akka/alpakka#302]
I've been using alpakka's sqs connector (great work btw!), and need to be able to request message attributes for the messages that come in.

Would y'all accept a PR with this functionality?

**Comment by johanandren** [comment]
What is that, a property of the messages or something you fetch separately from SQS?

**Comment by lnr0626** [comment]
There are two additional properties you can request along with the messages - Attributes and MessageAttributes. Attributes are some aws metadata about the specific message, and MessageAttributes are custom attributes that the sender attached to the message. They have some info in their [documentation for ReceiveMessage](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#API_ReceiveMessage_RequestParameters) and more specifically about MessageAttributes in their [developer guide](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html).

**Comment by johanandren** [comment]
Thanks. I think that sounds interesting, a PR is welcome :)
