### ISSUE TITLE
Alpaka S3 - is it possible to pass custom s3 client ?

### ISSUE THREAD

**Issue by ArtemTraierLotus** [akka/alpakka#3037]
Greetings, we need to pass custom s3 client since we overriding metrics publisher like this:
`      val s3Clinet = S3Client
        .builder()
        .overrideConfiguration((t: ClientOverrideConfiguration.Builder) => {
          t.addMetricPublisher(metricsPublisher)
          ()
}.build()`
So it would be nice to pass s3 client to akka S3Settings . Is it possible somehow ?

**Comment by ennru** [comment]
No, Alpakka AWS S3 does not use the AWS `S3Client`.
