### ISSUE TITLE
AWS S3 delete object missing

### ISSUE THREAD

**Issue by francisdb** [akka/alpakka#313]
The alpakka client currently supports listing, adding, getting but not deleting. Is there a specific reason for that?

Something like this
```
s3Client.deleteObject(bucket, fileName)
```
(and deleteObjects())

I understand this is not a streaming call but still it's a bit annoying to have to depend on an other (blocking) client to do the delete.

What would the best return type be? Source[Unit, Unit] or Future[Unit]?

**Comment by gorbenkoya** [comment]
Guys, please implement this feature

**Comment by francisdb** [comment]
@raboof I can come up with something but I first would like to see my question answered
```
What would the best return type be? Source[Unit, Unit] or Future[Unit]?
```

**Comment by johanandren** [comment]
Since it is a single delete completing `Future[Done]` would fit best.
