### ISSUE TITLE
AWS S3 putObject missing

### ISSUE THREAD

**Issue by francisdb** [akka/alpakka#314]
The multipart upload is is rather slow (200-500ms) compared to a normal put operation (80-200ms) when used for small files.

**Comment by francisdb** [comment]
I want to implement this but I have a hard time wrapping my head around the streams api.

Can somebody explain me how I would create a Sink[ByteString] that appends everything to a single http PUT?
I need the bytes coming into the Sink to be transformed into a Source[ByteString,_] for the http request.

Any example would be welcome, any pointers @2m ?

**Comment by 2m** [comment]
The bytes that are coming into the Sink are already coming from a `Source[ByteString,_]`. So no transformation should be necessary.

Are you thinking about the same API that multipart upload has? That is calling `s3Client` to get a sink and then connecting `Source[ByteString,_]` to it?

**Comment by francisdb** [comment]
I just thought it might be a good idea to have the same signature for both yes

**Comment by francisdb** [comment]
It seems that S3 might not support chunked uploads without knowing the size upfront
https://forums.aws.amazon.com/message.jspa?messageID=561616

**Comment by francisdb** [comment]
And regarding the sink I created this stackoverflow question
https://stackoverflow.com/questions/45035590/creating-a-akka-streams-sink-that-sends-all-data-to-a-http-endpoint

**Comment by kag0** [comment]
I'd also find this useful. I'd put forward a proposition for a signature something like: 
```scala
upload(bucket: String, key: String, contentLength: Option[Long] = None, contentType: ContentType = ContentTypes.`application/octet-stream`, metaHeaders /*etc*/): Sink[ByteString, ResultType]
```
where not providing a content length will default to a multi-part upload, and some content length will use a direct upload.
