### ISSUE TITLE
CSV line scanner skipping last line?

### ISSUE THREAD

**Issue by kciesielski** [akka/alpakka#315]
I stumbled upon a weird problem in one stream where I read CSV from a file, transform it and then write results to another file. I managed to isolate this issue in a test here: https://github.com/kciesielski/akka-quickstart-scala/blob/master/src/test/scala/com/lightbend/akka/sample/CsvTest.scala
You can download the whole repo, it's created solely for the purpose of demostrating my issue.

The problem is that sometimes the last line from source CSV does not get emitted by the `CsvParsing` stage.  It happens only occasionally, so my test above has its assertion wrapped in `eventually` clause.

Important notes: Problem doesn't occur if source CSV ends with a newline OR if we read into a different kind of sink than file (for example, Sink.seq). 

Maybe (hopefully) I'm using some elements here incorrectly, can someone take a look? A bit of insight from @ennru would be awesome :)

**Comment by ennru** [comment]
Hi @kciesielski 

When there is no newline at the end of the source it is meant to parse the last line on stream completion. Interesting that it is connected to using a File sink.
I'll have a closer look soon.

**Comment by kciesielski** [comment]
Yes, I looked through the sources and I noticed the `onUpstreamFinish` case emitting last line, not requiring the newline char. It would be great if you could investigate this, thanks!

**Comment by ennru** [comment]
Hm, I think it might not be connected to CSV stuff. Adding a `.log()` and even a `.map(identity)` between `fromPath` and the line scanner makes the error go away. Will try other stuff...

**Comment by kciesielski** [comment]
Yeah, maybe it's caused by something in `FileIO`. With logging enabled I could spot that the source finishes earlier in cases when tests fail. However, I have no idea why adding a newline to the input file would make the problem go away, logging shows that the whole contet gets read at once anyway. Indeed a bizarre problem to trace :)

**Comment by ennru** [comment]
Just landed after Scaladays. 

There is a problem in the CSV stage when data and completion come in a certain way. I know a solution, but haven't succeeded in writing a test yet. 

Am 3. Juni 2017 21:48:23 MESZ schrieb Krzysiek Ciesielski <notifications@github.com>:
