### ISSUE TITLE
MqttSink is not compatible for Future

### ISSUE THREAD

**Issue by chandrujsr** [akka/alpakka#334]
Hi,

I have scenario where message is consumed from kafka topic, process some DB call(which is Futures) and publish to Mqtt(via MqttSink) 

MqttSink is not compatible for Future[MqttMessage]

Ex: 
This will not work,
Source(1 to 10)
      .map(i => Future { MqttMessage("t", ByteString("ohi")) })
      .to(MqttSink(MQTTConnection.connectionSettings, MqttQoS.AtLeastOnce))

My doubt is, How to publish the message to Mqtt with Futures? Please let me know, if i am wrong/missing anything.

Thanks.

**Comment by 2m** [comment]
Hi. Use `mapAsync` instead of `map`.

**Comment by 2m** [comment]
I am going to close this ticket as this is a general Akka Stream question. Please feel free to drop by https://gitter.im/akka/akka if you need to discuss Akka Stream usage further. ;)
