### ISSUE TITLE
Building for Scala 2.11?

### ISSUE THREAD

**Issue by Scalahansolo** [akka/alpakka#340]
Hey team. I have a couple open RBs. Since the last time I contributed, alpakka has started getting built for 2.12. However at Twitter we have yet to upgrade to 2.12 so in order to test my changes properly I need to build for 2.11. I'm sure that I am just doing something wrong, but I cant seem to figure out how to publish local jars built with 2.11 compatibility. 

Sorry for opening an issue for this, was unsure of how to best get ahold of the team for this quick question.

**Comment by raboof** [comment]
Indeed the issues are more meant for issues and not really for questions - you could try gitter (https://gitter.im/akka/akka, https://gitter.im/akka/dev) or the akka-user mailinglist at https://groups.google.com/group/akka-user next time.

Sounds like you're looking for `sbt ++2.11.11 publishLocal`?
