### ISSUE TITLE
Durable Subscriber for JMS Connectors

### ISSUE THREAD

**Issue by niranjan-kachhawa** [akka/alpakka#345]
How can i add durable subscriber in JMSConnector using below code:

`Source<String, NotUsed> jmsTopicSource = JmsSource
    .textSource(JmsSourceSettings
        .create(connectionFactory)
        .withTopic("topic")
        .withBufferSize(10)
    );`

**Comment by niranjan-kachhawa** [comment]
Can we extend the GraphStage< SourceShape< Message > > class and then override the method which creates an consumer ?

**Comment by ennru** [comment]
The Alpakka JMS API has gone through quite some updates with version 0.16. Please have another look and see, if it fits your needs now. If it doesn't please open a new issue.
