### ISSUE TITLE
[FTP -> S3] possible regression 0.7 -> 0.9

### ISSUE THREAD

**Issue by l15k4** [akka/alpakka#353]
Hey,

I'm using this stream to copy gzipped files from FTP to S3 : 
```scala
Ftp.fromPath(sourceFilePath, ftpConf).runWith { 
new S3Client(S3Settings(MemoryBufferType, diskBufferPath, proxy, awsCred, region, pathStyleAccess))
    .multipartUpload(targetBucket, targetFileKey))
}
```
and even though it happens very  rarely, sometimes the file on s3 is corrupted and cannot be gunzipped due to : 
```
java.io.EOFException: Unexpected end of ZLIB input stream
```
I'm thinking of a regression because I copied tens of thousands of files with `0.7` without a problem and once I bumped to `0.9`, it started happening occasionally.

Considering the fact that these things can happen during network transfer, what is the best way to defend against this? Comparing md5 hashes doesn't exactly go with the reactive philosophy.

```scala
  val akkaVersion                = "2.4.17"
  val alpakkaVersion           = "0.9"
  val akkaHttpVersion         = "10.0.5"
```

**Comment by l15k4** [comment]
I can confirm that this is happening even in `0.10` and `0.11`.

**Comment by juanjovazquez** [comment]
@l15k4 Just to be sure, please can you confirm that you're setting `binary = true` in your FTP configuration?.

**Comment by l15k4** [comment]
@juanjovazquez yes, `passive=true` and `binary=true`. It happens only ~ 1 from 5 000 files, but still, one cannot get defensive and double-check MD5 hashes as that information is only available on s3, not FTP.

**Comment by juanjovazquez** [comment]
@l15k4 Anything special about these particular files (size, name, etc)?. Of course, you are able to download them using another tool with no issues, right?.

**Comment by l15k4** [comment]
@juanjovazquez nothing special, they are almost equally sized (partitioned data), the same origin, there is no apparent networking problem, the machine has plenty resources.

Yeah the source file is valid.

**Comment by l15k4** [comment]
@juanjovazquez Can you think of a way how to get defensive?

S3 should be doing that under the hood, so if there is no error and it returns success response, then it sounds like there are 2 problems : 
1) data loss
2) md5 checking not working on s3 side

**Comment by juanjovazquez** [comment]
@l15k4 Wrt the possible data loss, we should determine where the issue arises whether in the FTP source or in the S3 sink. If it's viable on your side, you might decompose the ETL process in two parts and test both sides independently, i.e. FTP -> File (local)  + File (local) -> S3.

As for the md5 checking I can't tell as I'm not involved in the S3 component.

**Comment by l15k4** [comment]
@juanjovazquez I've done some digging at the FTP server logs and it looks that this is happening when the FTP server is under pressure and a connection times out, however this code : 
```
Ftp.fromPath(sourceFilePath, ftpConf).runWith { 
new S3Client(S3Settings(MemoryBufferType, diskBufferPath, proxy, awsCred, region, pathStyleAccess))
    .multipartUpload(targetBucket, targetFileKey))
}
```
**succeeds - returns successful future result** in case of an FTP error, it only fails in case of S3 error with this : 
```
akka.stream.alpakka.s3.S3Exception: We encountered an internal error. Please try again.
	at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$entityForSuccess$1(S3Stream.scala:263)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by l15k4** [comment]
Guys this is resolved, I noticed that the FTP stream materialized `Future[IOResult]` was ignored. The stream must be composed this way : 
```
val (ftpF, s3F) = 
   Ftp.fromPath(sourceFilePath, ftpConf).toMat { 
      new S3Client(S3Settings(MemoryBufferType, diskBufferPath, proxy, awsCred, region, pathStyleAccess))
         .multipartUpload(targetBucket, targetFileKey))
   }(Keep.both).run()
s3F.flatMap(_ => ftpF).flatMap {
  case IOResult(_, Success(_)) =>
    Future.successful(Done.getInstance())
  case IOResult(_, Failure(ex)) =>
    Future.failed(ex)
}

```
