### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by tycho01** [akka/alpakka#355]
This repo lists as its url this [link](http://developer.lightbend.com/docs/alpakka/current/), which for me gives a 404. Swapping out `current` for a version, e.g. [`0.9`](http://developer.lightbend.com/docs/alpakka/0.9/), works though.

**Comment by 2m** [comment]
The original link is now back. It was a result of an intermittent issue with bintray (http://status.bintray.com/) which is now being solved.
