### ISSUE TITLE
AWS S3 Invalid signature calculation

### ISSUE THREAD

**Issue by francisdb** [akka/alpakka#357]
There is still a case where signatures are wrong

when listing using non-path style access in `us-east-1`

```
S3Exception, with message: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

continuation of #342

notifying @2m

**Comment by 2m** [comment]
Thanks for quick turnaround. We will get it right, eventually. :)

**Comment by francisdb** [comment]
@2m fix was another documented exception case we did not handle
