### ISSUE TITLE
Windows - ls operation with nested folder structure fails with file not found exception

### ISSUE THREAD

**Issue by keyursuchdeo** [akka/alpakka#362]
This is a windows specific issues. In case of nested folder structure under FTP root (e.g. /foo/bar/sth.txt), the program converts it into foobar (loosing separator), and hence failing to find the file. 

The issue seems to be due to the following line which puts windows file separator in path, changing /foo/bar to \foo\bar...

alpakka/ftp/src/main/scala/akka/stream/alpakka/ftp/impl/SftpOperations.scala
`Paths.get(s"$path/${entry.getFilename}").normalize.toString,`

...and the jsch library doesn't like it. It changes \foo\bar to \foobar. Culprit code below.

jsch/src/com/jcraft/jsch/Util.java
`    while(i<pathlen){
      if(path[i]=='\\'){
        if(i+1==pathlen)
          break;
        System.arraycopy(path, i+1, path, i, path.length-(i+1));
        pathlen--;
        i++;
        continue;
      }
      i++;
    }`

**Comment by raboof** [comment]
We just switched to another backend due to (other) problems with Jsch, could you test if this is still an issue for you on latest master (or on 0.11 once it's out)?

**Comment by keyursuchdeo** [comment]
Tested with current master code. It's working fine.
