### ISSUE TITLE
S3 download fails when credentials are provided at EC2 level

### ISSUE THREAD

**Issue by shyamsalimkumar** [akka/alpakka#367]
```scala
val credentialsProvider = new DefaultAWSCredentialsProviderChain()
val credentials = credentialsProvider.getCredentials
val awsCredentials = AWSCredentials(
  accessKeyId = credentials.getAWSAccessKeyId,
  secretAccessKey = credentials.getAWSSecretKey
)
val settings = new S3Settings(
  MemoryBufferType,
  "",
  None,
  awsCredentials,
  appConfiguration.awsRegion,
  false
)
val s3Client = new S3Client(settings)

s3Client
  .download(bucketName, keyName)
  .toMat(FileIO.toPath(Paths.get(fileName)))(Keep.right)
  .run()
  .foreach { x =>
    if (x.wasSuccessful) {
      println(s"Downloaded")
    } else {
      throw x.getError
    }
  }
```

The above works when credentials are placed at `~/.aws/credentials` (and probably at lower levels too) but failed when they are set at a higher level (Amazon ECS container credentials/Instance profile credentials) with the message `The AWS Access Key Id you've used does not exist in our records.`. I don't think it has something to do with `DefaultAWSCredentialsProviderChain` as the Java SDK also uses the same thing internally afaik, but that was working fine. 

Code that I'd tried out using Java SDK 

```scala
val s3ClientBuilder = AmazonS3ClientBuilder.standard()
s3ClientBuilder.setRegion(region)
val s3 = s3ClientBuilder.build()

try {
  val o = s3.getObject(bucketName, keyName)
  val s3is = o.getObjectContent

  val in = scala.io.Source.fromInputStream(s3is)
  val out = new java.io.PrintWriter(new File(fileName))
  try {
    in.getLines().foreach(out.println)
  } catch {
    case NonFatal(t) => println(t)
  } finally {
    s3is.close()
    out.close()
  }
} catch {
  case e: AmazonServiceException =>
    System.err.println(e.getErrorMessage)
    System.exit(1)
  case e: FileNotFoundException =>
    System.err.println(e.getMessage)
    System.exit(1)
  case e: IOException =>
    System.err.println(e.getMessage)
    System.exit(1)
}
```

Another thing I noticed (not sure if its important) is that the credential value returned by `DefaultAWSCredentialsProviderChain` changes when it is at a higher level periodically, but that too doesn't seem to affect the Java SDK version.

**Comment by Tvaroh** [comment]
Having same issue.

**Comment by tkroman** [comment]
One reason for that might be that `InstanceProfileCredentialsProvider` refreshes these things every minute, so they might get outdated or something like that. Are you sure that's not the case?

@raboof do you think alpakka should support dynamic credential resolution? Using implicit credentials provided via the EC metadata service on AWS is a pretty common thing. I could try to do it if I find some time in the nearest future (assuming the work on that isn't already being done)
