### ISSUE TITLE
S3 signature doesn't match expected when path contains special chars

### ISSUE THREAD

**Issue by gipeshka** [akka/alpakka#374]
Hi guys.

Currently I'm facing an issue with alpakka s3 client 0.10 when accessing a file like `files/überall.csv`
```
The request signature we calculated does not match the signature you provided. Check your key and signing method.
```
When I pass the key with encoded special chars, e.g. `files/%C3%BCberall.csv` I get another exception: `The specified key does not exist.`

Supposedly the issue is related to https://github.com/akka/alpakka/issues/357 and https://github.com/akka/alpakka/issues/316 because in version 0.9 I had exactly the error
`akka.http.scaladsl.model.IllegalUriException: Illegal URI reference: Invalid input 'ü', expected '/', 'EOI', '#', '?' or pchar` for exactly same configuration.

**Comment by francisdb** [comment]
Will create a test and look into this!

**Comment by gipeshka** [comment]
Hey @francisdb I added one on my local branch, actually shows that it's broken. I'll try to look into it myself, but anyway hope it helps https://github.com/gipeshka/alpakka/commit/d10058bee8c3de4b3ad2fd54ff841466a1124558

**Comment by francisdb** [comment]
Also got this reproduced, I wonder if there is still some issue with the CanonicalRequest logic

**Comment by francisdb** [comment]
found the issue, non-ASCII chars are not correctly encoded by CanonicalRequest, fix on it's way
