### ISSUE TITLE
SSE reconnect issue

### ISSUE THREAD

**Issue by bayarmunkh** [akka/alpakka#375]
Hi,

`EventSource` is unable to reconnect to the server in the following scenarios.

1. The server is unavailable, the client starts - the client is unable to connect to the server when the server starts up. 
2. The server is available, the client connects to the server. Then the server gets restarted before sending any message to the client - the client is unable to reconnect to the server.

**Comment by hseeberger** [comment]
Thanks for reporting, I'll investigate.

**Comment by bayarmunkh** [comment]
The both issues are fixed in the 0.11 release. Many thanks!

**Comment by hseeberger** [comment]
Sure thing!
