### ISSUE TITLE
Druid connector

### ISSUE THREAD

**Issue by cheleb** [akka/alpakka#38]
Hi
  I can provide [Druid](http://druid.io)  sink connector.

  Any interest ?

**Comment by ktoso** [comment]
Sure, thanks a lot in advance :-)

**Comment by patriknw** [comment]
sounds cool, please go ahead

**Comment by cheleb** [comment]
Hum, I'm stuck with scala 2.12 dependencies ... Afraid that we have to wait for a while until tranquility supports scala 2.12 (finagle deps ...)

**Comment by patriknw** [comment]
I think we can have modules released only for 2.11 if needed. Should just be a matter overriding the `crossScalaVersion`?

**Comment by cheleb** [comment]
I tried to  override the properties but without success 
https://github.com/cheleb/alpakka/blob/druid/build.sbt#L24

Any idea ?

**Comment by patriknw** [comment]
I guess it's something special because of the `Common` auto plugin. @2m How to define another crossScalaVersion for a specific project?

**Comment by 2m** [comment]
I think you forgot to reload the project after editing the build file:
```
> amqp/crossScalaVersions
[info] * 2.11.8
[info] * 2.12.0
> reload
[info] Loading global plugins from /home/martynas/.sbt/0.13/plugins
[info] Loading project definition from /home/martynas/projects/alpakka/project
[info] Set current project to alpakka (in build file:/home/martynas/projects/alpakka/)
> amqp/crossScalaVersions
[info] * 2.12.1
```

which is with the following configuration:
```
lazy val amqp = project
   .enablePlugins(AutomateHeaderPlugin)
   .settings(
     name := "akka-stream-alpakka-amqp",
     crossScalaVersions := Seq("2.12.1"),
     Dependencies.Amqp
   )
```

**Comment by 2m** [comment]
I just tried with your branch and it works. :)

```
> show druid/crossScalaVersions
[info] * 2.11.8
```

**Comment by cheleb** [comment]
(Sorry for this late reply)
I agree that "druid/crossScalaVersions" print right configuration. But AFAIU 
+package still tries to package 2.12.x version.

**Comment by 2m** [comment]
Aha. It looks like we will have to use [sbt-doge](https://github.com/sbt/sbt-doge) until sbt adds support for sub-project cross scala version support.

**Comment by cheleb** [comment]
Closing until 2.12 dependencies are resolved

**Comment by 2m** [comment]
Okay.

Original PR had two Scala 2.12 dependencies missing. I see that `com.metamx:scala-util_2.12:1.13.5` is already available. And for the second one here is the relevant PR: https://github.com/druid-io/tranquility/pull/229

**Comment by laszlovandenhoek** [comment]
The code in @cheleb's branch uses Tranquility for ingesting data. According to the current Druid docs (https://druid.apache.org/docs/latest/ingestion/index.html):

> The most recommended, and most popular, method of streaming ingestion is the Kafka indexing service that reads directly from Kafka. The Kinesis indexing service also works well if you prefer Kinesis.

Since Alpakka connectors for both Kafka and Kinesis exist, is this really still needed? I'm asking because this open issue is the top hit when I search Google for "alpakka druid". They might draw the wrong conclusion (i.e., "I can't use Alpakka with Druid/Imply").

**Comment by cheleb** [comment]
Feel free to close this issue.
