### ISSUE TITLE
Kinesis publisher Flow/Sink

### ISSUE THREAD

**Issue by aserrallerios** [akka/alpakka#382]
We can implement a Kinesis publisher Flow/Sink for alpakka.

I already have a working implementation, fully tested and pretty performant. If you're ok with it I can migrate it to alpakka & open a PR.

**Comment by aserrallerios** [comment]
I'm working on it. I'll open a PR soon implementing the first Flow that publishes records to Kinesis with retries.

**Comment by aserrallerios** [comment]
https://github.com/akka/alpakka/pull/408

**Comment by ennru** [comment]
This one has been release looong time ago now.
