### ISSUE TITLE
S3Settings(Config) takes config with "akka.stream.alpakka.s3" prefix

### ISSUE THREAD

**Issue by yaroot** [akka/alpakka#388]
Just wondering why the config for `S3Settings.apply()` would need that prefix, the change is done in 1b513be3589aa64f88e4bab281d912906a0e3dfd, but did not explain this change. Suppose someone would like to connect to multiple s3/s3-compatible services, the original one would make more sense.

If no one objects I'll make a PR.

**Comment by ennru** [comment]
Please do open a PR. See #606

**Comment by ennru** [comment]
As of #645 the config prefix can be passed to the `S3Settings` `apply` and `create` metods.
