### ISSUE TITLE
FTP: RemoteFileSettings classes inside or outside companion object?

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#395]
Most subclasses of `RemoteFileSettings` are defined inside the `RemoteFileSettings` companion object, but `SftpSettings` are defined outside.

What do we prefer?

**Comment by juanjovazquez** [comment]
@raboof We should review the entire model looking for consistency. I didn't want to do it in the context of #373 in order to not face too many changes at once. Maybe we can deal with that after merging. WDYT?.

**Comment by raboof** [comment]
I agree we should treat this as a separate issue and not roll it into #373
