### ISSUE TITLE
FTP: incorrect credentials should fail the stream

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#397]
Given this simple example:

```
import java.net.InetAddress

import akka.actor.ActorSystem
import akka.stream._

import akka.stream.alpakka.ftp._
import akka.stream.alpakka.ftp.scaladsl._

object Main extends App {
  val settings = SftpSettings(
    host = InetAddress.getByName("pi.bzzt.net"),
    strictHostKeyChecking = false
  )

  implicit val as = ActorSystem.create("test")
  implicit val ec = as.dispatcher
  implicit val mat = ActorMaterializer()

  val done = Sftp.ls("/tmp", settings)
    .runForeach(v => println(s"XXXX $v"))

  done.onComplete(_ => as.terminate())
}
```

This will not work as this host does not allow anonymous login.

Indeed the logging confirms authentication fails, but the application just hangs (until it hits some timeout) rather than failing the stream.

**Comment by juanjovazquez** [comment]
@raboof Please, could you clarify which would be the expected output?. After executing your program in REPL and inspecting the value of `done` I get:

```scala 
@ done: concurrent.Future[akka.Done] = Future(Failure(net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods))
@ done.isCompleted 
res25: Boolean = true
```
`Sftp.ls` produces a stream with no materialization so, in my opinion the outcome is correct, a failed future wrapping the underlying authentication exception. What am I missing?.

**Comment by raboof** [comment]
This is really weird, that indeed is the behaviour I'd expect.

I remember vividly my above example would stall indefinitely, but I can't reproduce that anymore, not even with alpakka 0.9.

Not sure if this was fixed or I was just confused when creating this ticket, sorry :)
