### ISSUE TITLE
S3 connector cannot upload file with ":" in name

### ISSUE THREAD

**Issue by jochenschneider** [akka/alpakka#404]
I am getting the following error (note the filename `log-2017-07-08T00:00:00.211`):

    [DEBUG] [07/07/2017 22:00:00.361] [server-akka.actor.default-dispatcher-362] [server/Pool(shared->https://s3-eu-central-1.amazonaws.com:443)] [2] </172.17.0.2:38468->s3-eu-central-1.amazonaws.com:443> Received response: POST /server/log-2017-07-08T00:00:00.211 Strict(0 bytes) -> 403 Forbidden Chunked
    [ERROR] [07/07/2017 22:00:00.371] [server-akka.actor.default-dispatcher-318] [akka://server/user/$b] Uploading log-2017-07-08T00:00:00.211 to server failed with java.lang.Exception: Can't initiate upload: <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>`

It works without the colons. If I urlencode the filename by replacing ":" by "%3A", "%3A" ends up in the filename on S3, not ":". Uploading a filename with colons works with other libraries.

**Comment by jochenschneider** [comment]
Might be fixed by #376, will check.

**Comment by jochenschneider** [comment]
Just checked, unfortunately not fixed by #376.

**Comment by francisdb** [comment]
Might look into this one, I guess we are still missing an exceptional encoding handling at
https://github.com/akka/alpakka/blob/master/s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala#L48
