### ISSUE TITLE
Set attributes in jms.Message on response in jmsSink

### ISSUE THREAD

**Issue by lvn2000** [akka/alpakka#409]
Currently, as I understood, jmsSink just send TextMessage without possibility to set ext.attributes(for example CorrelationId). Would be great if there is possible to set these attributes.

**Comment by lewismj** [comment]
Slightly, related to this, I was thinking of something (roughly along the lines of) ....

```
final case class JmsSinkSettings(....
                                   messageHeaders: Option[Map[String,String]] = None)
    extends JmsSettings {
....
    def withMessageHeaders(headers: Map[String,String]) = copy(messageHeaders = Some(headers))
  }

  final case class Credentials(username: String, password: String)
```

Then inside the `JmsSinkStage` 

```
settings.messageHeaders.foreach { case (k,v) => textMessage.setStringProperty(k,v)}
````
So that message headers can be applied (I have a use case where this is necessary).

I'd be happy to pick to do this, if someone wanted to confirm a design, i.e. someone from lightbend want be happy to include this? Could have separate maps per type of JMS property type or something else.

**Comment by lewismj** [comment]
I would also maybe add (optional) 'clientId' 

```
  sealed trait JmsSettings {
    def connectionFactory: ConnectionFactory
    def destination: Option[Destination]
    def credentials: Option[Credentials]
 //
   def clientId: Option[String]

  }
```

Inside `openSession`, setClientId can be applied if supplied.

Thoughts?

**Comment by lvn2000** [comment]
sounds good.. 

and maybe possible to realize  
 jmsSink funtion apply function, like:

def apply(jmsSettings: JmsSinkSettings): Sink[Message, NotUsed] =
    Sink.fromGraph(new JmsSinkStage(jmsSettings))

and in JmsSinkStage  like:
...
      setHandler(
        in,
        new InHandler {
          override def onPush(): Unit = {
            val elem = grab(in)
           elem match {
             case m:Message => jmsProducer.send(m)
            case _ => 
                val textMessage: TextMessage = jmsSession.session.createTextMessage(elem)
                jmsProducer.send(textMessage)
           }
            pull(in)
          }
        }
      )

**Comment by lvn2000** [comment]
I think variant "add properties' taking a list of 'any' " is better..

**Comment by lvn2000** [comment]
I think variant "add properties' taking a list of 'any' " is better..

**Comment by lvn2000** [comment]
Hello,

I've seen in version alpakka version 0.11 possibility to set properties in JmsMessage. Super! Thank you. Sorry, but I don't understand - how can be set property of message in case when client is sending message builded using alpakka to server where consumer that developed on Java with checking JmsCorrelationId, like:

`
import org.apache.activemq.{ActiveMQConnectionFactory, ActiveMQSession}
..
class ThatConsumer extend MessageListener {
...
override onMessage(message:Message)={
  if(message.getJMSCorrelationID){
    ...
  }
}
...
}
}`
Thank you

**Comment by ennru** [comment]
Please have a look at the Java code at [Alpakka JMS docs: Sending messages with properties to a JMS provider](https://developer.lightbend.com/docs/alpakka/current/jms.html#sending-messages-with-properties-to-a-jms-provider).
Is that what were looking for?

**Comment by lvn2000** [comment]
Thank you for comment.
I'm not sure that this is what I want. Exactly I need to get a message with CorrelationId  from producer (java application on customer side) and send my an answer message with same CorrelationId to customer.
