### ISSUE TITLE
Redirect website main URL to latest version

### ISSUE THREAD

**Issue by dluc** [akka/alpakka#42]
Nice to see Alpakka website online 👍 

It would be nice to allow this URL 
> http://developer.lightbend.com/docs/alpakka 

and automatically redirect (302) visitors to the latest version. That URL currently returns 403.

**Comment by ennru** [comment]
Alpakka moved to `docs.akka.io` now
https://doc.akka.io/docs/alpakka/ is not pretty, but works.
