### ISSUE TITLE
Allow CsvParsingStage to emit lines without a newline character before the upstream completes

### ISSUE THREAD

**Issue by rucek** [akka/alpakka#428]
Currently, if the last line in a CSV file doesn't contain a newline character, it's only emitted downstream when the upstream completes. So I was wondering whether it would be reasonable to modify `CsvParsingStage` to expose the `requireLineEnd` value in `tryPollBuffer` as a class field, so that it becomes configurable when instantiating the stage (with a default value of `true` to keep the current behavior)? 

## Motivation

In my scenario I have something like:
```scala
DirectoryChangesSource(...)
  .flatMapConcat(FileIO.fromPath)
  .via(CsvParsing.lineScanner())
```

and I'd like all the lines (including the last ones possibly missing the newline character) from the CSV files to be emitted downstream. However, since the `DirectoryChangeSource` never completes by itself, the last lines without a newline are never emitted. Thus I'd like to be able to write:
```scala
.via(CsvParsing.lineScanner(requireLineEnd = false))
```
to emit the last lines even though the source hasn't completed.

Looking forward to your comments. If you think this makes sense, I can obviously submit a PR.

**Comment by hochgi** [comment]
Is there a way to ensure that unreceived input won't contain the rest of the line, which may not be a `\n`?
Maybe, instead of a boolean, you can take a `FiniteDuration` as "emitEagerlyWithin", which will make the flow wait for more input, and only emit when time elapses, if no `\n` has been received since last `onPush`

**Comment by Voltir** [comment]
I will say that this behavior was kind of confusing in relation to using `Framing.delimiter(ByteString("\n")` - that explicitly does not include the framing character. I would much prefer a way to say "this byte string is the whole line, please just eagerly split it.."

**Comment by johanandren** [comment]
Doing a flatMapConcat of the bytes and then parsing them as csv is basically like first just concatenating them and then parsing that - if a file is missing a newline in the end that becomes a long line with the first line in the next file. There is no way for the downstream to know that you concatenated the streams of bytes.

From what I understand `flatMapConcat(path => FileIO.fromPath(path).via(CsvParsing.lineScanner()))` is what you want. The line scanner will parse linefeed separated lines until the stream ends witch causes the last line to be parsed as well, and the parsed entries will be emitted through `flatMapConcat`.

If you really really want to concatenate the bytes but need a separator that is missing can also be done through `flatMapConcat(path => FileIO.fromPath(path).concat(Source.single(ByteString("\n")))` which will add an additional linefeed after each stream of bytes from the files.

**Comment by ennru** [comment]
@rucek Did Johan's suggestion solve your question?

If the CSV parser didn't require line ends we'd get very strange output depending on how the data is chunked on its way to the parser. E.g. file sources split the read data into byte strings of a certain size, not necessarily full lines.

**Comment by ennru** [comment]
I hope you found a working solution. I don't see how we could change the current implementation to support your request and still work with chunked data.

**Comment by rucek** [comment]
@ennru @johanandren Sorry for replying so late. The suggestion to put the `lineScanner` inside `flatMapConcat` seems to do the trick, I haven't thought about that. Thank you!
