### ISSUE TITLE
MongoDB connector

### ISSUE THREAD

**Issue by stephennancekivell** [akka/alpakka#43]
Hi,

I can start the mongo connector.

**Comment by stephennancekivell** [comment]
Never mind, reactive mongo has good support for akka-streams.
I guess  this is not required then. Ill close the issue.

http://reactivemongo.org/releases/0.12/documentation/release-details.html#akka-stream

**Comment by patriknw** [comment]
Right, reactive mongo should be listed in the [external connectors](https://github.com/akka/alpakka/blob/master/docs/src/main/paradox/external-connectors.md). @stephennancekivell can you create a pull request adding it there?
