### ISSUE TITLE
Please consider to include Reajames functionality to Alpakka/JMS Connector

### ISSUE THREAD

**Issue by dobrynya** [akka/alpakka#431]
[Reajames](https://github.com/dobrynya/reajames/wiki) is JMS connector written in terms of pure org.reactive-streams specifications. It allows to operate any JMS aspect during sending/receiving JMS messages. So you can easily implement such integration patterns as Request - Reply.  I use Reajames in Akka Stream environment, it's stable enough in production.

**Comment by johanandren** [comment]
Since the library has RS connectors nothing more is needed to use it with Akka streams. `Source.fromPublisher` and `Sink.fromSubscriber` is all you need.

It's more like an alternative library than something to include as far as I can see?

**Comment by dobrynya** [comment]
You are right as I can use reajames in Akka Streams using AS adapters. But currently there is no way to use Alpakka JMS connector in real life as we need more control over JMS channel. So I believe that my approach applied in reajames is useful and can be used in Alpakka JMS connector. 
As I can see issues https://github.com/akka/alpakka/issues/441 and https://github.com/akka/alpakka/issues/442 are requests from real life.
So I just wanted to help because I use Akka and Stream and like these products.
