### ISSUE TITLE
DynamoDB: Support receiving all pages of scan and query operations

### ISSUE THREAD

**Issue by rtimush** [akka/alpakka#443]
DynamoDB `Scan` and `Query` operations are paged by nature — even if not requested explicitly, the result is truncated at 1 MB of data. Clients are expected to repeat requests with `ExclusiveStartKey ` set to `LastEvaluatedKey` obtained from the response (see [Query Pagination](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.Pagination) and [Scan Pagination](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.Pagination)
 for details). 

It will be convenient if DynamoDB connector provided a ready-to-use utility for paginated queries.

**Comment by joost-de-vries** [comment]
Cool. Have you considered using `Source.unfoldAsync` for the pagination logic? Might make the implementation more simple...

**Comment by dpfeiffer** [comment]
@joost-de-vries I thought about adding better support for common paginated sources (in my opinion `Source.unfoldAsync` is cumbersome if you just want to provide a paginated resource). I already created a ticket in `akka/akka-stream-contrib` https://github.com/akka/akka-stream-contrib/issues/93. Maybe this could also benefit from it?

**Comment by rtimush** [comment]
@joost-de-vries I had an impression that implementing it as a single graph has some benefits comparing to one graph asynchronously calling another. However, after some thinking I don't see a big difference, and `unfoldAsync` will probably result in a simpler code.

**Comment by joost-de-vries** [comment]
I definitely think that it's not so easy to find `Source.unfoldAsync` when you're thinking about "how do I call this paginated api". So some kind of help for new users would be useful.
 Now I'm a bit used to it I find it pretty easy to implement though. It's a very generic api. 
I hadn't seen that PR @dpfeiffer . Nice. For me personally a cookbook example or a `Spec` file in Alpakka would probably be enough. But that's just me. 

I _have_ been idly wondering whether an `unfoldAsync' that returns Sources instead of Futures would be more generic. F.i. to handle throttling while doing pagination. But so far I haven't needed that.

**Comment by rtimush** [comment]
I realized what is the difference between `unfoldAsync` and my implementation. `unfoldAsync` will internally materialize a new graph for every page, while the cyclic graph implementation will materialize it only once. I suppose this makes some performance impact (probably, negligible comparing to the actual DynamoDB query cost), but the bigger issue is that multiple materializations doesn't allow the internal HTTP connection pool to backpressure.
Honestly speaking, for a method returning `Source[op.B, NotUsed]` it is still not a big difference, as it requires materialization for each request, but if an API is extended to a single-flow version (something like `Flow[(AwsPagedOp, T), (AwsPagedOp#B, T), NotUsed]`) it will become an important difference.

**Comment by joost-de-vries** [comment]
@rtimush Interesting. `multiple materializations doesn't allow the internal HTTP connection pool to backpressure` In what sense do you mean 'backpressure'? I think that in general the completion of the `Future` that you return in Akka Streams apis provides backpressure. An async library doesn't need to be 'backpressure enabled' right?
Maybe I'm misunderstanding your point.

**Comment by rtimush** [comment]
@joost-de-vries If you materialize Akka HTTP flow multiple times concurrent requests may fail with `BufferOverflowException`. With a single materialization it instead would backpressure to the requests producer letting it to reduce the rate of requests. However, as I already said, for an `AwsOp => Source[...]` method failing when request rate is too high is probably an expected behavior.

**Comment by ennru** [comment]
Implemented by #444
