### ISSUE TITLE
improve usability of Dynamodb `flow`

### ISSUE THREAD

**Issue by joost-de-vries** [akka/alpakka#446]
The current `flow` implementation requires casting of the returned result in a way that's not very handy or intuïtive.
In fact I find myself forgoing the use of `flow` completely and just use `client.single` which returns a Future. As a result I end up using none of the streams support. As if I was using a simple async dynamodb client!

I've fiddled around a bit with the implementation of `flow`. You can find example code [here](https://github.com/joost-de-vries/alpakka/blob/dynamodb-flow-proposal/dynamodb/src/test/scala/akka/stream/alpakka/dynamodb/ExampleSpec.scala)
Instead of
```scala
def flow: Flow[AwsOp, AmazonWebServiceResult[ResponseMetadata], NotUsed] = ???
```
`flow` becomes
```scala
def flow[Op <: AwsOp]: Flow[Op, Op#B, NotUsed] = ???
```
This is what current usage of flow looks like
```scala
      Source
        .single[AwsOp](new CreateTableRequest().withTableName("testTable"))
        .via(client.flowOrig)
        .map(_.asInstanceOf[CreateTable#B]) // <-- this is not very intuitive
        .map[AwsOp]( // <-- this is required to trigger the following implicit conversion, which takes some time to find out as well
          result => new DescribeTableRequest().withTableName(result.getTableDescription.getTableName)
        )
        .via(client.flowOrig)
        .map(_.asInstanceOf[DescribeTable#B])
        .map(result => result.getTable.getItemCount)
```

This becomes
```scala
    Source
      .single(new CreateTableRequest().withTableName("testTable").toOp) // we keep the concrete subtype of AwsOp here
      .via(client.flow)
      .map(
        result => // that's why code completion 'understands' the type of 'result' here. which makes a big difference in usability
          new DescribeTableRequest().withTableName(result.getTableDescription.getTableName).toOp
      )
      .via(client.flow)
      .map(result => result.getTable.getItemCount)
```

And with an extra function `client.source`:
```scala
  client
      .source(new CreateTableRequest().withTableName("testTable")) // creating a source from a single req is common enough to warrant a utility function
      .map(result => new DescribeTableRequest().withTableName(result.getTableDescription.getTableName).toOp)
      .via(client.flow)
      .map(result => result.getTable.getItemCount)
```

I have most of the code for a PR. But I thought I'd create an issue first.

**Comment by areyouspiffy** [comment]
👍 I went down that road a bit [here](https://github.com/akka/alpakka/compare/master...areyouspiffy:178-AWS-Lex#diff-3094190b6c072f8695a7a1973ddd9844R57) but never really finished. Great idea!

**Comment by joost-de-vries** [comment]
Glad you like it. I created a PR: #451
