### ISSUE TITLE
Parallel file-system walker/scanner

### ISSUE THREAD

**Issue by michaelyaakoby** [akka/alpakka#448]
Hi,
I happened to build a while ago a stream-source that recursively scans a file-system using multiple threads - it is much faster then the regular BFS/DFS scanning.
If you think this can fit into the File component, I'll be happy to contribute.
M.

**Comment by 2m** [comment]
Hi, this sounds interesting. How did you manage parallelism? Was it manual by starting and stopping threads, or did you use some existing stream combinatorics, like mapAsync?

**Comment by michaelyaakoby** [comment]
Its a custom graph stage, using futures for the ".next" of the dir-iterator which are flattened into the stream similar to mapAsyncUnordered. The algorithm is kind of parallel BFS, so everytime a directory is encountered it is enqueued to be listed later.
In order to respect the "streaming expected behavior", it'll never list more then the downstream can take.

**Comment by ennru** [comment]
@michaelyaakoby are you still interested in contributing your file system scanner? 
Please close this, if not.

**Comment by michaelyaakoby** [comment]
Sure I want to contribute this.
How would you suggest to proceed?
Should I post the current version here and then we'll discuss the interface? Then I'll adjust the code and issue a pull request.

**Comment by ennru** [comment]
Great, go ahead and show what you have in a PR.
You might want to check out our [recommended layout](https://github.com/akka/alpakka/tree/master/reference/src/main/scala/akka/stream/alpakka/reference) which we are in the midst of applying to all modules.

**Comment by michaelyaakoby** [comment]
Will do. 
Will add it "as is" together with the tests (and added dependencies) and we'll discuss how to make it alpakk-ish.
Probably Thursday night.

**Comment by michaelyaakoby** [comment]
Hi Enno,

I just recalled that last November I've committed an example to my sandbox in github: https://github.com/michaelyaakoby/scalafun 
Usage example is in https://github.com/michaelyaakoby/scalafun/blob/master/src/main/scala/io/github/michaelyaakoby/scalafun/fscanner/ScannerMain.scala
```
implicit val sys: ActorSystem = ???
implicit val mat: ActorMaterializer = ???
implicit val ec: ExecutionContext = ???

val dirScanner = new DirScannerSource(Paths.get("/tmp"))

val scanF = dirScanner
  .scanSource()
  .groupedWithin(10000, 10.seconds)
  .scan((0, 0L, System.currentTimeMillis())) { (acc, paths) =>
    val now = System.currentTimeMillis()
    (acc._1 + paths.length, now - acc._3, now)
  }
  .runWith(Sink.foreach {case (entries, time, _) =>
    println(s"$entries new entries in $time millis")
  })
  .map(_ => dirScanner.cleanup())

```

My goal was to quickly scan recursively a monster file-system/directory dealing with the following challenges:
1. Since `java.nio.file.DirectoryStream` is synchronous, use multiple threads to scan directories in parallel.
1. Memory usage should be kept low

To solve this, I:
1. Used bluejeans's biqueue for storing child directories to be scanned in a off-heap queue 
1. Built an akka-stream that reads directories to be scanned from the queue then scanning them in a child graph

Note that the flow-control enforced by the stream results with as many open dir-iterators as `flatMapMerge` allows. Also, the `childrenSource` function creates a custom graph that performs IO operations asynchronously using futures.

Abyways, I was looking at the recommended layout and am not sure how to apply this to the parallel-scanner and wouldn't mind some guidance...

**Comment by michaelyaakoby** [comment]
Hi Enno,
The version I have doesn't perform well when scanning local file-systems - I used it to scan NFS volumes with 50M-200M files and the standard java scanner/walker was horribly slow compared to my parallel scanner, probably because of the high latency (compared to local disk).
Will close this issue for now and work on a better version, then I'll try to PR.
Thanks,
M.
