### ISSUE TITLE
Error trying to get a shard iterator from Kinesis stream

### ISSUE THREAD

**Issue by ccheneson** [akka/alpakka#450]
With `scala 2.12.3`, I have tried the `akka-stream-alpakka-kinesis` `v0.11` and I got the error 

> Failed to get a shard iterator for shard xxxxx

This is due to an incompatible version of `jackson-dataformat-cbor (v2.6.6) ` and `jackson-core (v2.8.8) ` which `akka-stream-alpakka-kinesis` depends on.

One workaround is to upgrade the jackson-dataformat-cbor to the latest `2.9.0`

```
libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-stream" % "2.5.4",
  "com.typesafe.akka" %% "akka-stream-testkit" % "2.5.4" % Test,
  "com.lightbend.akka" %% "akka-stream-alpakka-kinesis" % "0.11" exclude("com.fasterxml.jackson.dataformat", "jackson-dataformat-cbor"),
"com.typesafe.play" %% "play-json" % "2.6.0",
  "com.fasterxml.jackson.dataformat" % "jackson-dataformat-cbor" % "2.9.0"
)

```

I got the information necessary to debug from `KinesisSourceStage#awaitingShardIterator` and the entire  error message is 
```
com.amazonaws.SdkClientException: Unable to marshall request to JSON: Jackson jackson-core/jackson-dataformat-cbor incompatible library version detected.
You have two possible resolutions:
		1) Ensure the com.fasterxml.jackson.core:jackson-core & com.fasterxml.jackson.dataformat:jackson-dataformat-cbor libraries on your classpath have the same version number
		2) Disable CBOR wire-protocol by passing the -Dcom.amazonaws.sdk.disableCbor property or setting the AWS_CBOR_DISABLE environment variable (warning this may affect performance)
```

**Edit**: Sorry , this difference in versions is due to `play-json`. Without `play-json`, we don't encounter this problem. This issue can be closed

**Comment by dayyan** [comment]
If you're using Play, this issue can be fixed by hinting at the version you want.

`build.sbt` example:
```scala
lazy val dependencies = Seq(
  // Force jackson-dataformat-cbor to match Play.
  // │  │  │  │  ├─ com.amazonaws:aws-java-sdk-core:1.11.218 -> 1.11.226
  // │  │  │  │  │  ├─ com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.6.7
  //..
  // │  │  ├─ com.typesafe.play:play_2.12:2.6.1 -> 2.6.7
  // │  │  │  ├─ com.fasterxml.jackson.core:jackson-core:2.8.10
  "com.fasterxml.jackson.dataformat" % "jackson-dataformat-cbor" % "2.8.10",
...
```

**Comment by ennru** [comment]
As @ccheneson recommended, I close this issue.
Thank you @dayyan for giving helpful advice how to solve this, as well.
