### ISSUE TITLE
FTP - Ability to limit the ls function when recursively traversing remote folders

### ISSUE THREAD

**Issue by mpricope** [akka/alpakka#452]
Currently when you call one of the Ftp.ls functions like:
```
def ls(basePath: String, connectionSettings: S)
```
It recursively list the remote paths. Sometimes this can be sub-optimal (if you want to get the content of a folder but avoid it's sub-folders for example). 

I made a little extension of the method that also accepts a
```
FtpFile => Boolean
```
to decide if it should go on that folder or not. 

Like:
```
  def ls(basePath: String,
         connectionSettings: S,
         branchSelector: FtpFile => Boolean): Source[FtpFile, NotUsed] =
```

Would be happy to contribute if anyone else is interested

**Comment by eerlich** [comment]
Yeah, I just came across this issue myself. Even just a non-recursive `ls` would be great to have, but that should be easy to implement as a special case of your proposal.

**Comment by mpricope** [comment]
Cool ... I will try

**Comment by juanjovazquez** [comment]
The requirement might well be generalized to arbitrary filtering based on a predicate. This might be useful not only for pruning the tree but for ignoring certain types of files for instance.

**Comment by mpricope** [comment]
I actually thought that you can filter the files after they are emitted (not a big deal) ... but you need to prune the tree before being walked ... anyway, I'll make a pull request these days and you guys can comment on that until it feels right :)

**Comment by mpricope** [comment]
hey guys ... it seems that I am affected by #371  :(
