### ISSUE TITLE
EIP - Splitter

### ISSUE THREAD

**Issue by mpricope** [akka/alpakka#456]
Hi everyone,

I remember that back in the days when I was learning Camel, a very good and useful source was the Enterprise Integration Patterns page, describing how you implement each of these with Camel. 

I think this would be a very useful piece of documentation for people new to Akka Streams (like myself) :).
 
So I started implement a few patterns (some can be done in pure Akka Streams). Maybe we can update:
http://developer.lightbend.com/docs/alpakka/current/patterns.html

So here's the first one. EIP Splitter. With and without an aggregator:

```
    //A source that nees splitting
    val source: Source[String, NotUsed] = Source(List("1-2-3", "2-3", "3-4"))

    //Some Sink
    val printSink = Sink.foreach[Any](f => {
      println(f)
    })

    //Simple Split
    source.map(s => s.split("-").toList)
    .mapConcat(identity)
      .map(s => s.toInt)
      .runWith(printSink)


    //Split - Aggregate
    source.map(s => s.split("-").toList)
      .splitWhen(a => true)
      .mapConcat(identity)
      .map(s => s.toInt)
      .reduce((a, b) => a + b)
      .mergeSubstreams

      .runWith(printSink)
```

Let me know how this looks

**Comment by johanandren** [comment]
Good idea! Create a PR, that makes the review interaction much smoother.
