### ISSUE TITLE
Server-Sent Events Connector

### ISSUE THREAD

**Issue by hseeberger** [akka/alpakka#47]
[Server-Sent Events](https://www.w3.org/TR/eventsource/) (SSE) are a W3C standard for streaming simple UTF-8 encoded text based events via HTTP from a server to a client (one-way).

While the primary focus is pushing events from a webserver to a webbrowser (well supported except for IE), SSE can also be used to exchange events between services, i.e. allow for event-based collaboration. An example can be found in the [Gabbler](https://github.com/hseeberger/gabbler) demo project which uses the [akka-sse library](https://github.com/hseeberger/akka-sse).

In the above example SSE is used to establish a point-to-point connection between two services. If more services need to consume events published by one service, integration via Alpakka might be an attractive alternative to opening up many point-to-point connections. Also, data transformations could be applied by Alpakka and arbitrary endponints with an available connector could consume the events.

**Comment by patriknw** [comment]
sounds good, will it be listed as external connector with link to akka-sse?

**Comment by ktoso** [comment]
SSE we'll also want to promote in Akka HTTP somehow.
I was thinking that we might focus on tagging projects on scala-index btw – such that akka-sse is tagged akka-http and alpakka etc.

**Comment by hseeberger** [comment]
My idea is to split akka-sse into a core/server part which should go into Akka HTTP and a client/connector part which should go here. Packagewise the unreleased 2.0 is already split.

**Comment by ktoso** [comment]
Yup, totally on board with this plan
