### ISSUE TITLE
Alternative to InetAddress

### ISSUE THREAD

**Issue by msiddiqi** [akka/alpakka#482]
Apparently we can't use InetAddress.getByName() behind corporate proxy for building FTP / Sftp settings. Any idea how this can be resolved?

var address = InetAddress.getByName("HOST_URI")
    val settings = SftpSettings(
      host= address,
      strictHostKeyChecking = false,     
    )

**Comment by raboof** [comment]
Does that mean you cannot do any DNS requests at all? That seems really strange.

It might be good to get some more details on exactly what your corporate proxy does and does not allow before we can give advice.

The github issues aren't really meant for 'user' discussion, perhaps [gitter](https://gitter.im/akka/akka) would be a better place to discuss this?
