### ISSUE TITLE
Switch to scalafmt

### ISSUE THREAD

**Issue by hseeberger** [akka/alpakka#49]
For me it looks like scalafmt is the future of Scala code formatters. Ain't this project a nice way to give it a try in the Akka world?

**Comment by ktoso** [comment]
I don't have a strong opinion on formatter choice here. 
Only reason I'm a bit worried about scalafmt is that it's again someone's grad project, 
so I'm afraid if it will continue to be developed once it's served it's graduation purpose hm...

**Comment by hseeberger** [comment]
There are 30 contributors to scalafmt: https://github.com/olafurpg/scalafmt/graphs/contributors.
Scalariform has 37, i.e. almost the same number even though it is years older. I hope that (a) the fact that Scalariform is very hard to maintain and (b) the upcoming hype about ScalaMeta will result in a vibrant community around scalafmt. But hey, I don't have a crystal ball ...

**Comment by ktoso** [comment]
Yeah, would be nice if it takes off.
I wouldn't mind applying it in alpakka first, PR please? :)

**Comment by hseeberger** [comment]
Here's the PR: https://github.com/akka/alpakka/pull/52

**Comment by hseeberger** [comment]
I have also updated sbt-header to the latest version and gave some love to some of the build files.

**Comment by hseeberger** [comment]
Closed by #52.

**Comment by patriknw** [comment]
@hseeberger @ktoso Let's make sure we assign the milestone for closed issue (or PR if there is no issue). It's the responsibility of the one that merges the PR to do that. The purpose is to know what is in each release.

**Comment by ktoso** [comment]
Right, will do.

**Comment by hseeberger** [comment]
Got it!
