### ISSUE TITLE
Javadsl for MongoDb Connector

### ISSUE THREAD

**Issue by patriknw** [akka/alpakka#494]
In https://github.com/akka/alpakka/issues/115 a MongoDB connector was added, but without Java API. It would be great to add `javadsl` (I don't know if that would require a different underlying implementation/driver).

**Comment by stephennancekivell** [comment]
I'd recommend a different module for the a java connector, as there is a different driver that returns different document types to the scala one.

https://mongodb.github.io/mongo-java-driver/
http://mongodb.github.io/mongo-scala-driver/

**Comment by ennru** [comment]
Or base both on the [Reactive Streams compliant driver](http://mongodb.github.io/mongo-java-driver-reactivestreams/)?

**Comment by dbuschman7** [comment]
On the separate connector/driver issue. 
The Scala driver uses the "core" jars from the java driver so a separate connector would not be needed.

**Comment by dotbg** [comment]
Looks like it was done in #1514

**Comment by ennru** [comment]
That's right, thank you. Closing.
