### ISSUE TITLE
MongoDb Sink for scala

### ISSUE THREAD

**Issue by stephennancekivell** [akka/alpakka#495]
We should have a sink as well as a source for the mongo connector :)

I have a old branch for this I can rebase then submit a PR https://github.com/stephennancekivell/alpakka/commit/d3c95d9ec17dc8003b855d2c3d46dd4f36e53678

This will not provide a java api, as discussed in #494 and #148

**Comment by stephennancekivell** [comment]
I have a PR for this here.  #164 I had forgotten about it. Just updated.

**Comment by ennru** [comment]
#164 is now merged and will be part of Alpakka 0.15
