### ISSUE TITLE
S3 download with metadata

### ISSUE THREAD

**Issue by kag0** [akka/alpakka#497]
The current return type for downloading from S3 is `Source[ByteString, NotUsed]`, it would be immensely useful if the source could materialize with the object metadata like last modified and content type (see `com.amazonaws.services.s3.model.ObjectMetadata`). So something like `Source[ByteString, ObjectMetadata]`.

Any interest in adding this?

**Comment by francisdb** [comment]
We have this locally in our code for getting only the metadata (HEAD)
We could reuse the existing `ListBucketResultContents` you get when doing listings

Might have a go at this one

**Comment by kag0** [comment]
@francisdb sounds awesome

**Comment by francisdb** [comment]
@kag0 you might want to have a look if #563 satisfies your needs. It returns a `ObjectMetadata` as materialized value that contains all response headers

**Comment by kag0** [comment]
@francisdb looks great, thanks.
