### ISSUE TITLE
Google PubSubMessage missing attributes

### ISSUE THREAD

**Issue by yanns** [akka/alpakka#510]
A `PubSubMessage` can have a map a key/values as `attributes`:
https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage

**Comment by mertkavi** [comment]
and `publishTime`

**Comment by ennru** [comment]
It should be enough to add these fields to the `PubSubMessage` case class and Spray JSON will convert them to JSON when calling the service.

**Comment by ennru** [comment]
Fixed with #747
