### ISSUE TITLE
AMQP Connector

### ISSUE THREAD

**Issue by mvbaffa** [akka/alpakka#512]
Hi,

I am new to the AMQP Connector. 

I am using a driver that does not work well when the connection closes. In fact it recreates the connection but does not rebind the variable associated with the connection. It does not even notify the occurence.

Does AMQ Connector recover from connection down. Does it recreates the connection and rebind the source when the connection closes unexpectly ? 

Thanks

**Comment by johanandren** [comment]
Hi @mvbaffa, we use the issue tracker exclusively for bugs and feature tracking, please use the Akka gitter channel https://gitter.im/akka/akka or the mailing list for questions like this https://groups.google.com/forum/#!forum/akka-user thanks!
