### ISSUE TITLE
akka-stream-alpakka-sqs_2.12-0.14 artifact missing in public maven repo

### ISSUE THREAD

**Issue by an-tex** [akka/alpakka#533]
https://repo1.maven.org/maven2/com/lightbend/akka/akka-stream-alpakka-sqs_2.12/

contains only up to 0.13

Cheers

**Comment by johanandren** [comment]
Thanks for letting us know, there were some other problems with the arteficts of the 0.14 release as well, we will relatively soon do a new release to fix the issues.

**Comment by ranchoiver** [comment]
@an-tex 
@johanandren 

Same with AMQP connector: 
https://repo1.maven.org/maven2/com/lightbend/akka/akka-stream-alpakka-amqp_2.12/

**Comment by raboof** [comment]
Notice 0.14 is still a 'draft release' in https://github.com/akka/alpakka/releases :).

We actually just did the sync from bintray to sonatype, and while http://search.maven.org/#search%7Cga%7C1%7Calpakka does not list 0.14 versions yet, the artifacts should be starting to show up. Indeed https://repo1.maven.org/maven2/com/lightbend/akka/akka-stream-alpakka-amqp_2.12/ in fact now *does* contain the 0.14 jar ;).

**Comment by raboof** [comment]
I'm curious where you found a reference to 0.14? Indeed it took somewhat longer than usual due to some infrastructure hiccups and Reactive Summit, but it should be making its way out now :).

**Comment by ranchoiver** [comment]
IIRC I found it in the docs of the connector

**Comment by raboof** [comment]
Aah yes probably the docs were updated from travis even though the jars weren't successfully uploaded to bintray/sonatype. Makes sense. Anyway, the jars should be making their way to the sonatype index as we speak :+1:
