### ISSUE TITLE
Elasticsearch connector - encoding bug

### ISSUE THREAD

**Issue by mbknor** [akka/alpakka#547]
Hi,

Elasticsearch connector 0.14 fails to post json to elastic if json contains special characters.

Elastic is unable to parse the json and is reporting *Invalid UTF-8 middle byte 0x20*

The problem is located on this line:
https://github.com/akka/alpakka/blob/master/elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala#L135

By changing it from:

     new StringEntity(json)

to

     new StringEntity(json, "utf-8")

the problem is fixed

**Comment by takezoe** [comment]
I will try to reproduce in test and will create a pull request to fix it!

**Comment by mbknor** [comment]
hehe... I didn't see you PR :)
