### ISSUE TITLE
Failed: No output from build for 10 minutes

### ISSUE THREAD

**Issue by johanandren** [akka/alpakka#553]
Something with downloading cassandra?

```
Pulling cassandra (cassandra:3.0.15)...
3.0.15: Pulling from library/cassandra
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

https://travis-ci.org/akka/alpakka/jobs/293118545

**Comment by raboof** [comment]
I saw some similar ones (geode I think) recently, perhaps dockerhub was just out? Good to keep track though.

**Comment by johanandren** [comment]
Weird thing is that 3 out of four builds in the matrix succeeds but one (random one I think) fails

**Comment by raboof** [comment]
I'm blaming https://www.traviscistatus.com/incidents/v4jnp6nkgzqx
