### ISSUE TITLE
Clarify introduction in documentation

### ISSUE THREAD

**Issue by patriknw** [akka/alpakka#58]
What is required of an Alpakka connector?

The connectors in the alpakka repository must have an Akka Streams api (for java and scala). External connectors must have Akka Streams or Reactive Streams api.

**Comment by skhatri** [comment]
Hello Patrik,
Would also be good to specify what you would want to take as part of core alpakka components and what you would like to see as external contributions.

Also, will you have a "core" module with ref implementation of some EAI Patterns, much like Camel's.

**Comment by patriknw** [comment]
> Would also be good to specify what you would want to take as part of core alpakka components and what you would like to see as external contributions.

The purpose of external connectors is if the connector is maintained in another github repository.

Otherwise it can be accepted as core Alpakka component if it has an Akka Streams api and is considered useful and in scope of the integration domain.

> Also, will you have a "core" module with ref implementation of some EAI Patterns, much like Camel's.

Yes, that is the purpose of the currently empty http://developer.lightbend.com/docs/alpakka/latest/patterns.html section of the documentation.

A pattern can be a GraphStage or combination of existing stages exposed as a `Flow` or other shape. It can also be just documentation of how to solve a specific integration scenario.

**Comment by ennru** [comment]
With the current state of Alpakka it is quite well defined what is required from an Alpakka connector.
