### ISSUE TITLE
S3: Default credentails resolver is "anon"

### ISSUE THREAD

**Issue by gipeshka** [akka/alpakka#580]
Currently in reference.conf the default credentials provider is set to `anon`.

According to comment on the reference.conf:
```
# If this section is absent, the fallback behavior is to use the
# com.amazonaws.auth.DefaultAWSCredentialsProviderChain instance to resolve credentials
```

Therefore comment or reference.conf file should be changed accordingly.

**Comment by ennru** [comment]
Fixed by #644
