### ISSUE TITLE
S3 SigningKey should not cache credentials

### ISSUE THREAD

**Issue by gregbeech** [akka/alpakka#587]
The `akka.stream.alpakka.s3.auth.SigningKey` class currently caches the credentials from `AWSCredentialsProvider` in the constructor:

```scala
private val credentials: AmzAWSCredentials = credProvider.getCredentials
```

This causes problems with credentials that need to be refreshed, such as those provided to containers based on their role (e.g. using `EC2ContainerCredentialsProviderWrapper`). The `AWSCredentialProvider` interface includes a `refresh` method, and the documentation indicates that the result of the `getCredentials` method is not referentially transparent as a result.

Because of this, we need to work around the issue by recreating the `S3Client` class each time the credentials are refreshed which isn't hard but adds unnecessary complexity to application code.

**Comment by gipeshka** [comment]
@ennru this one is apparently solved by https://github.com/akka/alpakka/pull/545

**Comment by ennru** [comment]
@gregbeech Thank you for pointing this out.
