### ISSUE TITLE
Google cloud storage client

### ISSUE THREAD

**Issue by francisdb** [akka/alpakka#588]
This is rather a feature request, we might be able to contribute this in the future depending on what path we choose.

Can be implemented using akka-http
Should be simpler than the s3 client

https://cloud.google.com/storage/docs/json_api/

**Comment by francisdb** [comment]
We have this ready and I plan to send in a pr once #563 is done

**Comment by ennru** [comment]
Hej @francisdb Any plans to go on with this now that 0.16 is out?

**Comment by francisdb** [comment]
Yes, should come back to this one, will try to find the time to finish this up

**Comment by josefelixh** [comment]
Hey @francisdb, has this been abandoned?

**Comment by josipgrgurica** [comment]
@josefelixh I'm near the end with it, PR should be ready this weekend.

**Comment by francisdb** [comment]
> Hello Google Cloud Storage Customer,
>
> We are writing to let you know that starting June 20, 2019, Cloud Storage will allow JSON API requests to be sent to storage.googleapis.com in addition to www.googleapis.com (the current endpoint).
What do I need to know?
>
> On June 20, 2019, we will begin updating the Cloud Client Libraries and gsutil to use the new endpoint; storage.googleapis.com. After the update, your JSON API requests will start using the new endpoint.
>What do I need to do?
>
>If your production or test code doesn't check for endpoint-specific details, no action is required on your part.
>
>If your production or test code checks for endpoint-specific details, you will need to modify them before June 20, 2019 as follows:

>    If your code checks that the ‘baseUrl’ or ‘rootUrl’ fields in the JSON API Discovery document point to www.googleapis.com, you will need to modify those checks to allow either storage.googleapis.com or www.googleapis.com. Note that the oauth2 scopes fields in the Discovery document will not change and will continue to point to www.googleapis.com.
>    If your code checks that the ‘selfLink’ field in bucket or object metadata points to www.googleapis.com, you will need to modify that check to allow either storage.googleapis.com or www.googleapis.com.
>    If you access Cloud Storage through a firewall, you will need to ensure that requests to storage.googleapis.com are allowed by your firewall rules.
