### ISSUE TITLE
akka-stream-alpakka-mongodb artifact is missing in maven

### ISSUE THREAD

**Issue by anoo-muthuswaami** [akka/alpakka#593]
I'm unable to locate mongoDB connector artifact in Maven https://repo1.maven.org/maven2/com/lightbend/akka/

**Comment by johanandren** [comment]
I noticed that the module was not part of the build in #597 but then it turned out the tests do not pass, so there's more work than just adding it to the build and fixing the code formatting. We need help from the community to get this in.

**Comment by ennru** [comment]
@gosubpl  @stephennancekivell Could you have a look at the existing MongoDB tests in master?

**Comment by stephennancekivell** [comment]
Hi guys. I suspect its just missing a docker-compose entry. The tests worked for me locally months ago when I was first looking at it, connecting to my locally running mongo.

Should be something like this.
```
+  mongo:
+    image: mongo
+    ports:
+      - "27017:27017"
```
However Im struggling to run the build locally I get a unresolved dependency error for `com.thoughtworks.paranamer#paranamer;2.8`...

**Comment by ennru** [comment]
It does the trick locally for me. I'll send a PR.
