### ISSUE TITLE
SSE clients seem not to disconnect when downstream terminates

### ISSUE THREAD

**Issue by ionos** [akka/alpakka#598]
The feedback loop for the last-event-ID in the SSE client (v 0.14) keeps the upstream connection alive indefinitely.

Would it be possible to add `eagerCancel=true` to the broadcast, or to make it user-configurable?

**Comment by ennru** [comment]
@hseeberger Anything you'd want to comment on this?

**Comment by hseeberger** [comment]
The whole idea of this connector is keeping the connection alive. If you don't need that, simply use plain Akka HTTP. Or am I missing something?

**Comment by ionos** [comment]
@hseeberger In our use case, we wanted to keep the connection alive in cases upstream disconnects, but terminate in cases when the downstream side finishes processing (i.e. client going away).

Background: We have a service that accepts SSE requests from clients, creates SSE connections to upstream sources itself, retrieves items, processes them, and sends them on to the client. New connections to the upstream sources are created for every client (for auth reasons, and to keep this service stateless). Without eager cancel, upstream connections seem to stay alive when a client terminates. Thus, we ended up with many alive-but-stale connections over time, leading to resource starvation both in our service as well as the upstream sources.

**Comment by hseeberger** [comment]
@ionos the connector gives you a `Source[ServerSentEvent, NotUsed]`, you can use it as you wish. In particular you (downstream) can complete a running stream whenever you want.

In the tests there is an example where downstream takes a finite number of events:
https://github.com/akka/alpakka/blob/master/sse/src/test/scala/akka/stream/alpakka/sse/scaladsl/EventSourceSpec.scala#L142

**Comment by hseeberger** [comment]
@ionos sorry, I misunderstood. I think your suggestion is reasonable, I'll take a closer look.

**Comment by hseeberger** [comment]
See https://github.com/akka/alpakka/pull/737.
