### ISSUE TITLE
CSV Component

### ISSUE THREAD

**Issue by skhatri** [akka/alpakka#60]
I can write CSV component, if you like.

I was thinking of creating a CSVFlow as well as CSVSourceStage.
Where CSVFlow will take a ByteString and chunk it, the CSVSourceStage could be a wrapper around FileIO. Let me know if this will be an acceptable component.

**Comment by hseeberger** [comment]
AFAIK Camel has it, too, so this makes sense to me.

**Comment by stephennancekivell** [comment]
Great idea!
Might be nice to wrap open csv or something to take care of the escaping nuance's.

Or scala-csv / pure-csv / mighty csv.

**Comment by joearasin** [comment]
Not sure if it's optimal, but we've been using something along the lines of this to write CSVs, built around commons-csv:

```
  def forFormat(csvFormat: CSVFormat, charset: Charset = StandardCharsets.UTF_8): Flow[Seq[Any], ByteString, NotUsed] = {
    Flow[Seq[Any]].map {
      cells => {
        val buf: ByteStringBuilder = ByteString.newBuilder
        val writer = new OutputStreamWriter(buf.asOutputStream, charset)
        csvFormat.printRecord(writer, cells.map(_.asInstanceOf[AnyRef]): _*)
        writer.close()
        buf.result()
      }
    }
  }
```

On top of this, one thing worth keeping ind mind with an API sort of like this is possibly padding the inputs, to deal with varying-length sequences that may be truncated.

**Comment by ennru** [comment]
@skhatri Did you put any more effort into this?

What I find in the existing CSV libraries (commons-csv, open csv, scala-csv) is that they tend to take control over file IO, which is not what we want in an Akka Stream. I've done some parsing Stages with scala-csv, but converting to CSV is a bit like what @joearasin shows for commons-csv.

**Comment by johanandren** [comment]
On the parser side we'd want it to be push/record based, in that we can push bytestrings on it and potentially get a record back, just like the JSON framing in Akka stream core: https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/scaladsl/JsonFraming.scala

**Comment by ennru** [comment]
So the expected signature could be something like 
`val csvFlow: Flow[ByteString, Source[ByteString, NotUsed], NotUsed] = CsvFraming()` 
where the created stream contains one element per column in the incoming CSV ByteString and a new element for every "line" (CSV columns may contain line breaks).

Or should it make things simpler and create elements of `immutable.Seq[ByteString]`.

**Comment by johanandren** [comment]
Or the stage would both frame and parse and emit `CsvRecord`s or something like that?

**Comment by johanandren** [comment]
Can you think of a use-case where it is interesting to consume fields rather than entire records?

**Comment by ennru** [comment]
That would be this extra-wide Excel data a former colleague of mine produced, in case I'd only be interested in the first 100 columns. 
But the framing would need to go through the rest anyway, so a fixed length thingy will be best. I would not want to introduce a `CsvRecord`. Another step in the stream would be to convert the list of elements to a map out of the column names (`Map[String, String]`), which on request could be read as the first record in the stream.

**Comment by johanandren** [comment]
Ok, sounds like you have a plan! 👍
