### ISSUE TITLE
Support UpdateTimeToLiveRequest in DynamoDB connector

### ISSUE THREAD

**Issue by gregbeech** [akka/alpakka#603]
The DynamoDB connector doesn't currently support the `UpdateTimeToLiveRequest` which is necessary for creating expiring rows. It would be good to add this support.

**Comment by ennru** [comment]
Thank you for making the DynamoDB connector more useful.
Would you have the chance to add something about the TTL in the docs?

**Comment by ennru** [comment]
I reckon people needing it will find it even without text in the docs. Cheers.

**Comment by gregbeech** [comment]
Hey, sorry, missed the notification about your previous comment regarding docs. As you say, I'm not sure there's that much value in putting anything specific in the Alpakka docs as it should be pretty easy to find once you've looked at the AWS docs (which I assume people will read in conjunction given the Alpakka lib is a fairly thin wrapper over it).
