### ISSUE TITLE
Streamlining connector settings

### ISSUE THREAD

**Issue by johanandren** [akka/alpakka#606]
This may be a topic where there are different opinions on. Mine:

Only Akka-core configuration should live in the akka namespace. 

Alpakka should have its own top-level namespace `alpakka.connector-x` for default connector configs. 

Connectors providing config should provide one `ConnectorXSettings(ActorSystem)` factory which reads the default path and one `ConnectorXSettings(Config)` which just accepts the config block of the connector so that a user can have multiple configs for the same connector in her application.conf.

We should make a checklist for connectors, including a description of this as a requirement, and update existing connectors.

**Comment by ennru** [comment]
Let's review `CONTRIBUTING.md` and come up with a good checklist there.

**Comment by ennru** [comment]
I find these uses of the config namespaces
* akka.stream.alpakka.dynamodb
* akka.stream.alpakka.ironmq
* akka.stream.alpakka.s3

So it is not huge to migrate, I'd say.

**Comment by 2m** [comment]
Lets use `s"alpakka.$javaModuleName"` as the namespace for a given connector:

DynamoDB: `alpakka.aws.dynamodb`
IronMQ: `alpakka.ironmq`
S3: `alpakka.aws.s3`

**Comment by ennru** [comment]
This migration happened a while back.
