### ISSUE TITLE
Using Docker service on Travis fails Cassandra connector build

### ISSUE THREAD

**Issue by dpfeiffer** [akka/alpakka#62]
I think it is related to that: travis-ci/travis-ci#5502

I tried to use docker service to run elasticmq as it is not available for Scala 2.12 yet. Even if elasticmq will be available soon as they are just waiting for akka-http, I think that other connectors could need docker as well.

**Comment by hseeberger** [comment]
Oops :-(

**Comment by dpfeiffer** [comment]
I think it would be better to run cassandra also in a docker container even it is available in Precise Travis images, so other modules can use docker as well.

**Comment by hseeberger** [comment]
Fine for me. I do similar stuff for ConstructR (with etcd). What do others think?

**Comment by ktoso** [comment]
About elasticmq: I expect @adamw to be able to release it as soon as we call the 10.0 which could be this week already. Refs: https://github.com/adamw/elasticmq/issues/84

Don't mind the docker solution in general though :)

**Comment by 2m** [comment]
I think this sounds good. Lets run `cassandra` and `rabbitmq` in docker as well. Lets use the same docker images as we suggest to use on the development machines: https://github.com/akka/alpakka/blob/master/docs/src/main/paradox/cassandra.md#running-the-example-code
https://github.com/akka/alpakka/blob/master/docs/src/main/paradox/amqp.md#running-the-example-code

Even better, we could start docker containers from the test itself. That way contributors will not need to do that manually when running tests.

**Comment by dpfeiffer** [comment]
@2m In general I agree that it would be cool to let the tests start the docker containers so it's easier to run all tests locally. I'm not sure if there is a sbt plugin for that right now. 

I used https://github.com/whisklabs/docker-it-scala before but I don't think thats a good idea as well. Maybe providing a docker compose file as mentioned by in #24 would be a better idea?

**Comment by hseeberger** [comment]
My experiments with automatic starting of containers didn't go well. docker-it-scala could be a way out. @dpfeiffer, why don't you like that (just asking, I have no experience at all with it).

But personally I prefer to start containers manually (we should provide scripts) for local tests and use the Docker service of Travis for CI. If we have the tests start containers, we can't use the Docker service of Travis.

**Comment by dpfeiffer** [comment]
I had some problems with it. Especially when it comes to using the same docker container from multiple test classes, because docker-it-scala starts and stops per suite. I think another problem will be trying to do that with the tests for the java api as they are no scalatest specs.
