### ISSUE TITLE
Provide Unix Domain Socket support

### ISSUE THREAD

**Issue by huntc** [akka/alpakka#620]
Provide Unix Domain Socket support for Akka Streams; perhaps in the spirit of [the `Tcp` Akka Streams class](https://doc.akka.io/docs/akka/current/stream/stream-io.html?language=scala). Unix Domain Sockets permit a secure local-only stream-oriented connection protocol.

**Comment by huntc** [comment]
I'm unable to assign myself to the issue, but please be advised that I've now started to port my existing implementation to Alpakka:

* Main: https://github.com/huntc/landlord/blob/master/landlordd/daemon/src/main/scala/com/github/huntc/landlord/UnixDomainSocket.scala
* Tests:
https://github.com/huntc/landlord/blob/master/landlordd/daemon/src/test/scala/com/github/huntc/landlord/UnixDomainSocketSpec.scala

Introduced dependencies and their licensing - all should be favourable - please confirm:

```
[info] No license specified
[info] 	 org.ow2.asm:asm-util:5.0.3 (BSD/Apache: https://mvnrepository.com/artifact/org.ow2.asm/asm)
[info] 	 org.ow2.asm:asm-analysis:5.0.3 (BSD/Apache: https://mvnrepository.com/artifact/org.ow2.asm/asm-analysis)
[info] 	 org.ow2.asm:asm-commons:5.0.3 (BSD/Apache: https://mvnrepository.com/artifact/org.ow2.asm/asm-commons)
[info] 	 org.ow2.asm:asm-tree:5.0.3 (BSD/Apache: https://mvnrepository.com/artifact/org.ow2.asm/asm-tree)
[info] 	 org.ow2.asm:asm:5.0.3 (BSD: https://mvnrepository.com/artifact/asm/asm)
[info] 
[info] Common Public License - v 1.0
[info] 	 com.github.jnr:jnr-posix:3.0.35
[info] 
[info] MIT License
[info] 	 com.github.jnr:jnr-x86asm:1.0.2
[info] 
[info] The Apache Software License, Version 2.0
[info] 	 com.github.jnr:jnr-unixsocket:0.18
[info] 	 com.github.jnr:jnr-enxio:0.16
[info] 	 com.github.jnr:jnr-constants:0.9.8
[info] 	 com.github.jnr:jnr-ffi:2.1.4
[info] 	 com.github.jnr:jffi:1.2.15
```

**Comment by huntc** [comment]
Profiled with YourKit within my Landlord project and, in particular, ensured that resources are observed to be released when expected - particularly the NIO channels.

**Comment by huntc** [comment]
Thanks for the review/merge @2m and @hseeberger!

**Comment by 2m** [comment]
Thank you, @huntc. Awesome stuff, as always. :)
