### ISSUE TITLE
akka-stream-alpakka-mongodb not in Maven Central

### ISSUE THREAD

**Issue by asarkar** [akka/alpakka#622]
The other components seem to be present, but not MongoDB. Same issue was reported in https://github.com/akka/alpakka/issues/593, which has been merged, but still nothing shows up in Maven. Is there a SNAPSHOT/milestone repo somewhere that I can use for time being?

**Comment by ennru** [comment]
We plan to release 0.15 this week. Hold your breath just a few more days.
