### ISSUE TITLE
Drop Akka 2.4 support

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#624]
We have an Alpakka PR (https://github.com/akka/alpakka/issues/623) that utilizes functionality from Akka 2.5 series and 2.4 is approaching its EOL. We should consider dropping the support for Akka 2.4 in Alpakka.

Is there anyone that uses Alpakka with Akka 2.4 and can not migrate to Akka 2.5?

Otherwise we can declare Alpakka 0.14 as the last version having 2.4 support and continue with only 2.5 builds.

**Comment by ennru** [comment]
I'd say we release 0.15 as planned this week and state that it will be the last to support Akka 2.4.
