### ISSUE TITLE
Wrap up 0.15 release

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#626]
Two weeks ago I propsed to target 6 December for Alpakka release 0.15.
We've seen quite some activity during this time and a lot of things wait to get release.

But a few things - e.g. the issues listed below - we hoped to get in are not completely finished yet. 

Should we release on Thursday, or is it worth waiting a few more days?

* #515
MQTT manual acks
Flaky tests? Weird behaviour?

* #596
Connector for orientdb
Builds stall, no obvious connection to the new code

* #601
Add proxy support for sFTP
Tests not fully implemented?

* #506
Amqp reusable connections
Changes requested

* #434
Add Kinesis KCL Source
Amazon License questions

* #164
Add mongodb sink
Good API? (execution context required)

* #603
Support UpdateTimeToLiveRequest in DynamoDB connector
Merged, but not documented

* #558
elasticsearch connector fails to extract error from response
Merged, but open

**Comment by gosubpl** [comment]
https://github.com/akka/alpakka/pull/164 looks fine.

**Comment by johanandren** [comment]
Closed #558

**Comment by ennru** [comment]
#164 is now merged and closed.

**Comment by ennru** [comment]
Closed #603 even without docs.

**Comment by ennru** [comment]
Alpakka v0.15 is now released: https://github.com/akka/alpakka/releases/tag/v0.15
