### ISSUE TITLE
KinesisFlowSettings.byNumberOfShards(shards: Int) issue

### ISSUE THREAD

**Issue by nvrs** [akka/alpakka#642]
There is an error on the helper method byNumberOfShards(shards: Int) on KinesisFlowSettings companion in calculating the maxRecordsPerSecond and maxBytesPerSecond values. Specifically, the method is calculating the respective values by doing
```
maxRecordsPerSecond = shards * MAX_BYTES_PER_SHARD_PER_SECOND,
maxBytesPerSecond = shards * MAX_RECORDS_PER_SHARD_PER_SECOND
```

instead of 

```
maxRecordsPerSecond = shards * MAX_RECORDS_PER_SHARD_PER_SECOND,
maxBytesPerSecond = shards * MAX_BYTES_PER_SHARD_PER_SECOND
```

**Comment by ennru** [comment]
Fixed with #643
