### ISSUE TITLE
KinesisFlow will not allow application termination

### ISSUE THREAD

**Issue by osbornk** [akka/alpakka#678]
I am having a strange issue that I am not sure how to solve. I am running the KinesisFlow within an application. I am trying to run the KinesisFlow within a command-line application. But the application will not respond to system terminate.

In the code below, I get into onComplete, but the application itself does not exit.

```
val z = Source.single("test").map(r => {
      logger.info("test")
      new PutRecordsRequestEntry().withPartitionKey("partition-key").withData(ByteString(Json.obj().toString).asByteBuffer)
    }).
      via(KinesisFlow(kinesisStreamName)).runWith(Sink.ignore)

    z.onComplete { _ =>
      logger.info("Completed Sending data to Kinesis")
      system.terminate()
    }
```
This seems to be specific to KinesisFlow. If I remove the "via(KinesisFlow(kinesisStreamName))", the program exists normally.

I am really at a loss here. Perhaps because it is using the AsyncKinesisClient (wrapped into Futures)?

**Comment by aserrallerios** [comment]
The Flow logs interesting info on DEBUG. Can you run it again with DEBUG and show us the output? Have you seen any strange error on amazon or akka loggers? 

I'm on vacation right now, I'll have a closer look when I get back.

**Comment by aserrallerios** [comment]
I've tested it against a real `Kinesis` stream and it worked. Are you still having these problems?

**Comment by osbornk** [comment]
I finally got a chance to debug do this in debug mode and I am still having these problems. I have tried quite a few variations without success. The only way I can exit my application is with a system.exit(0).

I have attached the debug log.

[application.log](https://github.com/akka/alpakka/files/1624560/application.log)

It seems like the system gets stopped, but for some reason never gives control back to the application.

I also ran the debug logs against the version that does work (without "via(KinesisFlow(kinesisStreamName))"). The debug out put basically looks exactly the same.

```
val z = Source.single("test").map(r => {
      logger.info("test")
      new PutRecordsRequestEntry().withPartitionKey("partition-key").withData(ByteString(Json.obj().toString).asByteBuffer)
    }).runWith(Sink.ignore)

    z.onComplete { _ =>
      logger.info("Completed Sending data to Kinesis")
      system.terminate()
    }
```

Again, the Kinesis stream works. And I get to the onComplete. But after the onComplete, it never exits the application. There is nothing in the application code beyond the onComplete.

**Comment by aserrallerios** [comment]
Are you expecting the JVM to shutdown after calling `system.terminate()`? Can you paste your whole `Main` please?

**Comment by aserrallerios** [comment]
I think I know what you mean. I've reproduced it, and the JVM exits when `system.terminate()` is called, even when it's called in a different thread other than the `Main`'s thread! I don't know the JVM spec that explains that behaviour. It's a bit of black magic to me.

About your problem, try this:

```scala
z.onComplete { _ =>
    logger.info("Completed Sending data to Kinesis")
    kinesisClient.shutdown()
    system.terminate()
  }
```

**Comment by ennru** [comment]
As you may want to share the Kinesis client across streams, you may use
`system.registerOnTermination(kinesisClient.shutdown())`
which will shut ut down on actor system termination.
I'll add it to the docs.
