### ISSUE TITLE
Cannot load Alpakka AMQP dependency

### ISSUE THREAD

**Issue by jvvasques** [akka/alpakka#68]
Hi there!

I followed the [guidelines](http://developer.lightbend.com/docs/alpakka/latest/amqp.html) to add the AMQP Alpakka library and I'm getting a `unresolved dependency` error on sbt.

Bellow is a snippet of my build.sbt file. I am missing something like a resolver? Thanks!

```
libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-stream-experimental" % "2.0.1",
  "com.typesafe.akka" %% "akka-stream-alpakka-amqp" % "1be3b7fc"
)

scalariformSettings

ScalariformKeys.preferences := ScalariformKeys.preferences.value
  .setPreference(AlignSingleLineCaseStatements, true)
  .setPreference(AlignSingleLineCaseStatements.MaxArrowIndent, 100)
  .setPreference(DoubleIndentClassDeclaration, true)
  .setPreference(PreserveDanglingCloseParenthesis, true)

fork in run := true

```

**Comment by johanandren** [comment]
`1be3b7fc` is some junk that probably ended up in the docs by mistake, it should be `0.1`

**Comment by johanandren** [comment]
@2m do you have any clue, the .md file has "$version$" in it, which seems to have been replaced with a git revision?

**Comment by johanandren** [comment]
@jvvasques where did you see that, if I go to http://developer.lightbend.com/docs/alpakka/0.1/amqp.html it has "0.1" as expected in the import instruction.

**Comment by patriknw** [comment]
it might be like that if you build the docs locally from a commit without tag

**Comment by 2m** [comment]
Couple of issues here that we need to solve. Tech Hub builds alpakka docs for every new commit to master, and it puts those under the [latest](http://developer.lightbend.com/docs/alpakka/latest/amqp.html). The version over these is only a short commit hash. This means, that tech-hub does not checkout tags when doing master docs build. This needs to be fixed, so the version becomes `0.1+17-6d6c77c2`, which indicates it is 17 commits in front of the latest release `0.1`.

But now I see another issue. We do not publish artifacts for every push to master, but we have docs which reference such versions. I think we could publish such master artifacts to JCenter as well, and amend master docs, that one needs an additional resolver to get these. This way early adopters can try out features whenever they get merged into master.

**Comment by jvvasques** [comment]
@johanandren I was forwarded to the `latest`alpakka docs and not `0.1`. Looks like the version that is exposed there is a short commit hash. @2m already identified the main issues

**Comment by jvvasques** [comment]
Changed my `build.sbt` to `0.1` but I'm still getting unresolved dependencies

`build.sbt` sample
```
scalaVersion := "2.11.8"

libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-stream-experimental" % "2.0.1",
  "com.typesafe.akka" %% "akka-stream-alpakka-amqp" % "0.1"
)

```

output of `sbt reload clean compile`

```
[warn]  module not found: com.typesafe.akka#akka-stream-alpakka-amqp_2.11;0.1
[warn] ==== local: tried
[warn]   /Users/joaovasques/.ivy2/local/com.typesafe.akka/akka-stream-alpakka-amqp_2.11/0.1/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /Users/joaovasques/activator-1.3.7-minimal/repository/com.typesafe.akka/akka-stream-alpakka-amqp_2.11/0.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream-alpakka-amqp_2.11/0.1/akka-stream-alpakka-amqp_2.11-0.1.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/akka/akka-stream-alpakka-amqp_2.11/0.1/akka-stream-alpakka-amqp_2.11-0.1.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.akka/akka-stream-alpakka-amqp_2.11/0.1/ivys/ivy.xml
[info] Resolving org.scala-lang#scalap;2.11.8 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.akka#akka-stream-alpakka-amqp_2.11;0.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
```

**Comment by johanandren** [comment]
It seems the docs are using the wrong group id. It should be "com.lightbend.akka" not "com.typesafe.akka".

As a side note, Akka stream 2.0.1 is really old and will likely not work with Alpakka, please use the latest release (currently 2.4.12).

**Comment by jvvasques** [comment]
Thanks for the heads up @johanandren 🙏
