### ISSUE TITLE
Make Alpakka docs more google-able

### ISSUE THREAD

**Issue by ktoso** [akka/alpakka#700]
Say you’re some spring person, and googling “i want reactive AMQP”…
You would not find Alpakka (I just tried), since there we talk about Akka all the time.

I think we should include some keywords or phrases in each page that would make them more googlable, even if people don't know the "alpakka" name.

What do you think about either adding keywords or some other text on all Alpakka integration docs pages such that they would show up on google searches for “reactive [thingy]” / "reactive streams [thingy]" and "akka [thingy]".

Perhaps we should also link to Alpakka modules from Akka docs etc?

**Comment by ennru** [comment]
Good point. The docs are too code centric right now. They don't know what you can achieve.

Adding some "good" text in the page template's footer could help.

**Comment by ktoso** [comment]
Yeah, I think it could be a number of things:

-  like an Alpakka "pitch" in the footer as you propose,
- each doc page somehow explain "this is reactive streams integration to blabla tech, using akka streams" maybe
- maybe also `<meta name="keywords"` if those work nowadays? Would need help from paradox to allow adding those but could be pretty nice

**Comment by ennru** [comment]
The docs and the cross-linking with other Akka projects has improved a lot. We will keep improving on it...
