### ISSUE TITLE
Use ByteString instead of byte[] for JMS bytesSink and bytesSource

### ISSUE THREAD

**Issue by viktorklang** [akka/alpakka#701]
https://developer.lightbend.com/docs/api/alpakka/0.15.1/akka/stream/alpakka/jms/scaladsl/JmsSink$.html#bytesSink(jmsSettings:akka.stream.alpakka.jms.JmsSinkSettings):akka.stream.scaladsl.Sink[Array[Byte],akka.NotUsed]

**Comment by johanandren** [comment]
Updated title as a change request instead of a question.

**Comment by viktorklang** [comment]
@johanandren I initially worded it as a change request but I didn't want to presume to know something I didn't, hence the question. :)

**Comment by ennru** [comment]
I can see another side to this: The underlying JMS message supports transport of byte arrays and a receiver could expect some kind of "all" data for a message in this array.
Akka `ByteString`s have more focus on the possibly unlimited flow of bytes and do often split on spots where no "whole" message is contained in the ByteString.

But yes, there is nothing stopping anyone from stating a good contract for the content in the messages.

The JMS Sink should support `ByteString`, as well as `Array[Byte]`.

**Comment by viktorklang** [comment]
@ennru I'm not entirely sure I understand what you mean by ByteStrings is for unlimited flow of bytes—it is an immutable version of Array[Byte] (in a similar vein to String being an immutable version of Array[Char]), which happens to support cheap manipulations due to its rope-like structure.

**Comment by ennru** [comment]
Yes, I understand the benefits of ByteString over Arrary[Byte].
What I see in Akka Streams and Alpakka is that people forget that a stream element of type ByteString not necessarily makes sense on its own. Using `_.utf8String` might fail if a Unicode-char happens to be split accross two ByteStrings.
All this applies to Array[Byte], as well - but I can see a slight "tone" towards whole messages there.
Not supporting ByteString is the Alpakka API an oversight. (The contributor just went for the types supported in standard JMS.)
We look forward to your contribution :-)

**Comment by viktorklang** [comment]
I understand your line of thinking but I disagree. Had it meed "BLOB" or similar it would signal more "whole message". (String has methods for constructing using byte-array and Charset, and creating a byte-array using a Charset, so in that respect they are indeed 1:1, w.r.t. partiality.)

(ByteString doesn't really have anything to do with Strings *per se*, it's just binary data)
