### ISSUE TITLE
Fix groudId name for Cassandra connector

### ISSUE THREAD

**Issue by BranislavLazic** [akka/alpakka#71]
Using: 
`"com.typesafe.akka" %% "akka-stream-alpakka-cassandra" % "0.1"`
reported unresolved dependencies. However, using
`"com.lightbend.akka"` groupId made it work. Please update documentation.

**Comment by ktoso** [comment]
Thanks for reporting, making the change is very simple, just edit the page here: https://github.com/akka/alpakka/edit/master/docs/src/main/paradox/cassandra.md
Thanks for your upcoming Pull Request with the fix then :)
