### ISSUE TITLE
dependency on old Akka library version.

### ISSUE THREAD

**Issue by london-coder** [akka/alpakka#710]
I would like to use alpakka **amqp** in a new project, using Play 2.6.10, that in turn has dependency on Akka 2.5.8. However, alpakka **amqp** still has a dependency on Akka 2.4.19. When might alpakka be updated to make it usable on an up to date project, built using sbt 1.0.4? 

B.T.W I am using RabbitMQ version 3.7.2

Thanks, 
Alan Lewis

**Comment by ennru** [comment]
You may use Alpakka with Akka 2.4 as Akka versions are binary compatible in very high degree and Alpakka 0.15 is compiled against both Akka 2.4 and 2.5.

We'll release Alpakka 0.16 today, which the first version not compatible with Akka 2.4 anymore.

**Comment by london-coder** [comment]
Thanks. What repositories will 0.16 be available from? That is, what resolvers will need to be included in sbt build file to retrieve 0.16?

**Comment by ennru** [comment]
The release is being built right now. 
Expect it to hit Maven Central within 10 hours.

**Comment by london-coder** [comment]
That's great. Many thanks.
