### ISSUE TITLE
JMS snippet tags duplicated

### ISSUE THREAD

**Issue by akara** [akka/alpakka#721]
Perhaps this is a Paradox issue. But for example: https://developer.lightbend.com/docs/alpakka/current/jms.html#transactionally-receiving-s-from-a-jms-provider

You'll see duplicate Java code samples. Checking the source snips/references, I cannot find anything wrong there. There is only one snip and there are no duplicates on the references.

**Comment by ennru** [comment]
Interesting. But yes, more a Paradox issue.
Anything you have seen somewhere else @raboof ?

**Comment by johanandren** [comment]
He'll be on vacation until next tuesday, so don't hold your breath for an answer.

I haven't seen it before. I just verified that there is nothing funky with the sources and the snippet markup here: https://github.com/akka/alpakka/blob/master/jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsAckConnectorsTest.java

**Comment by jonas** [comment]
I found [two labels](https://github.com/lightbend/paradox/issues/181#issuecomment-357714619) that are used in two different contexts.

**Comment by akara** [comment]
Hmm, even I missed it after searching!!!
