### ISSUE TITLE
jms: Connection in JmsSink is not closed when stream stop

### ISSUE THREAD

**Issue by russellyou** [akka/alpakka#733]
in 0.16 , we introduced multiple session per connection.

< 0.16 
we close connection along with session close which is ok as we have only one session per close

But in 0.16, we have multiple sessions. We close current session only 
      private[jms] def closeSession(): Unit = session.close() // class JmsSession

That's also ok, as we don't want to impact other session.

The issue is in we should close connection in postStop method in JmsSinkStage instead

      override def postStop(): Unit = {
        if (!completionPromise.isCompleted) completionPromise.tryFailure(new AbruptStageTerminationException(this))
        jmsSessions.foreach(_.closeSession())
      }

Each time one stream materialized and close, one connection leak will happen.

**Comment by ennru** [comment]
Would this be solved by adding a `connection.close()` in `postStop`, where we reach the connection from any of the sessions?

**Comment by russellyou** [comment]
That's also my proposed fix.

**Comment by ennru** [comment]
We look forward to your Pull Request.

**Comment by russellyou** [comment]
I am preparing PR,  may need a little bit help to verify the connection is closed. 

The jmsConnection in JmsSinkStage is not exposed anywhere. I can think of creating my custom ConnectionFcatory to get hold a connection before passing to JmsSettings. But sound over kill. Any better suggestion?

**Comment by ennru** [comment]
You want to get hold of the connection to verify it is properly closed in the tests?
Providing a connection factory proxy via jms settings seems reasonable to me.

**Comment by ennru** [comment]
Fixed with #756
