### ISSUE TITLE
Elasticsearch: Can I update documents of different index and type using one sink

### ISSUE THREAD

**Issue by lxw-mesoor** [akka/alpakka#734]
I need to update docs of many indices and types. Can ElasticsearchSink set the index and type when update?

**Comment by ennru** [comment]
No. That is not supported in Alpakka.
You may run a new (index and type specific) flow in a mapAsync function of an outer flow.

**Comment by ennru** [comment]
This will partly be supported with PR #763

**Comment by ennru** [comment]
Try out what we have in Alpakka 0.17 now. Open a new feature request if you're still missing what you need.
