### ISSUE TITLE
Object metadata available before stream materializtion in s3 download

### ISSUE THREAD

**Issue by kag0** [akka/alpakka#740]
So I messed up.
in https://github.com/akka/alpakka/issues/497 I suggested a return type like this `Source[ByteString, Future[ObjectMetadata]]` for s3 downloads. 
I'm coming to realize that that was not well thought out, and that a return type more like `Future[(Source[ByteString, ObjectMetadata], ObjectMetadata)]` or `(Source[ByteString, Future[ObjectMetadata]], Future[ObjectMetadata])` would be better.
The reasoning for this is that it's desirable to have access to the metadata before the stream materializes. 
One simple use case would be an akka http route that simply downloads a file from s3 and streams it back to the client. We would most likely want to use the metadata in the headers of our response, but won't have access to the metadata since the stream materialization is done by akka http.

I'm happy to take a shot at this if you're open to it.

**Comment by ennru** [comment]
@francisdb Any comment?

**Comment by francisdb** [comment]
@kag0 makes sense, wondering if the `Future[(Source[ByteString, xxx], ObjectMetadata)]` could be something else that brings value or maybe just `Done`

**Comment by ktoso** [comment]
Yeah it makes sense. 
I wonder if for convenience the current API can be kept in case people don't need the metadata for some reason? Or do you think it should be dropped?

**Comment by kag0** [comment]
I think a `(Source[ByteString, xxx], Future[ObjectMetadata])` return could replace the current api with little inconvenience to users since their existing `val source = download(...)` could be easily replaced with `val (source, _) = download(...)`

**Comment by francisdb** [comment]
Should indeed not be to hard to switch: `Source.formFutureSource(download(...).map(_._1))`

**Comment by francisdb** [comment]
I see you went for the other option of returning a tuple.
Any the akka/alpakka api design best practices regarding these return types?
 * `(Source[ByteString, NotUsed], Future[ObjectMetadata])`
 * `Future[(Source[ByteString, NotUsed], ObjectMetadata)]`

**Comment by kag0** [comment]
Yes, I found the convenience of being able to use `val (source, _) = download(...)` tipped me in that direction.
But indeed if anyone knows if there are any best practices or conventions here then I'll switch it to whatever that is.

**Comment by ennru** [comment]
Fixed by #742
