### ISSUE TITLE
Google Pub/Sub gRPC API Support

### ISSUE THREAD

**Issue by mina-mishriky-ck** [akka/alpakka#741]
Are there any plans to add support for the gRPC API exposed by Google in the pub/sub connector?

**Comment by ennru** [comment]
You mean as in #556 ?
The plans for Alpakka are made by the contributors (that might be you - wink wink). There is no roadmap we're working after.

**Comment by mina-mishriky-ck** [comment]
Fair enough 😄

**Comment by ennru** [comment]
This is available now https://doc.akka.io/docs/alpakka/current/google-cloud-pub-sub-grpc.html
