### ISSUE TITLE
Hashicorp Vault integration

### ISSUE THREAD

**Issue by huntc** [akka/alpakka#757]
My project requires integration with [Hashicorp's Vault](https://www.vaultproject.io/). I'm writing here to gauge interest in such an integration as I may be able to see that that my development is open-sourced once done (no promises though as I'm not in control of that bit!).

Integrating with Vault is more than just dealing with requests via akka-http. It would also require stateful actors representing a principal and its authentication state including associated tokens. These tokens are leased and so must be updated periodically. Secrets are also associated with a principal and are similarly subject to their lease being renewed periodically.

I'm unsure about there being an akka-streams API associated with this - there's nothing particularly streamy about the Futures-based API that I'm thinking. It is enterprise integration though and would utilise akka-streams/http. Would it, therefore, belong in Alpakka or somewhere else?

Incidentally, having now written this, there appears to be [a similar request for Apache Camel](https://issues.apache.org/jira/browse/CAMEL-11030).

**Comment by raboof** [comment]
I agree this sounds super useful but not necessarily streams-related - perhaps it would fit better as a separate project?

**Comment by ktoso** [comment]
Agreed, not every useful Akka based library needs to live in Alpakka after all, just the Streams ones :)

**Comment by ktoso** [comment]
Hope you don't mind if I close, as we seem to be in agreement. Hope you can spin up the project and ping us about it then!

**Comment by huntc** [comment]
Ok, thanks guys.
