### ISSUE TITLE
Backpressure on ProvisionedThroughputExceededException in DynamoDB?

### ISSUE THREAD

**Issue by an-tex** [akka/alpakka#767]
Every DynamoDB table has a provisioned throughput. Once exceeded, the client returns a ProvisionedThroughputExceededException . Wouldn't this be an indication to back pressure?

**Comment by joost-de-vries** [comment]
I seem to remember that the AWS client itself does already do a retry/backoff mechanism. So I'm not sure doing another backoff mechanism on top of that makes sense.

**Comment by an-tex** [comment]
I'm not sure about the implementation details of the backoff / retry but it certainly doesn't expose any back pressure to the upstream, so it's either buffering or dropping items. Either way it's not the akka streams way of handling things ;)
Sure it's better than nothing, but I guess especially as the aws client is already signalling an overloading / throttling of the next stage, why don't make use of it and make it visible to the whole stream.

**Comment by codynhat** [comment]
I have run into many issues of `ProvisionedThroughputExceededException` being hit and retries by the AWS client just making the problem worse. The retries do not necessarily stop new requests from coming in flight. Especially when the upstream is much faster. Signaling back pressure when the AWS client sees this would help.

It's also very akka stream-y and intuitively seems like the expected behavior.

**Comment by 2m** [comment]
I would be in favor of adding a new `flow` to the DynamoDB connector that would return responses wrapped in `Try[...]`. Then upon failure a [`Retry`](https://developer.lightbend.com/docs/api/akka-stream-contrib/current/akka/stream/contrib/Retry$.html) could be used to retry the failed request after some time, which would be backpressuring.

**Comment by julianhowarth** [comment]
Just been trying to use the connector and have immediately run into this issue - this makes this lib a complete non-starter for me. My use case is that I need to scan a 100k row DynamoDB table when bootstrapping my service instances - I need to get the data as fast as possible but after 5k rows the flow just stops.

Just for additional information I'm use OpenJDK 11.0.4, scala 2.12.7, akka-streams 2.5.25, and 1.1.1 of Alpakka Dynamo - even with a logging supervision strategy the flow just stops silently. The onlmy clue something is wrong is a JDK warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil (file:/home/julian/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.6/jackson-databind-2.8.6.jar) to field java.lang.Throwable.cause
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.databind.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by ennru** [comment]
For Alpakka 2.0 we'll use AWS SDK 2 (in master already).
I'm currently working on the `Retry` ideas @2m suggested earlier. Retrying with backoff will become available. I hope it will solve this scenario, as well.

**Comment by julianhowarth** [comment]
For scan requests, it's trivial with AWS SDK 2 as `DynamoDbAsyncClient` provides:
```
ScanPublisher scanPaginator(ScanRequest scanRequest)
```
where `ScanPublisher` implements `Publisher`, so creating a akka-streams `Source` is as simple as: `Source.fromPublisher(dynamoClient.scanPaginator(myScanRequest))`. Similar handling is available for `batchGetItems` too

**Comment by ennru** [comment]
Interesting, I haven't looked into those. Would you be able to suggest what needs to be done in a Pull Request?

**Comment by ennru** [comment]
I looked into this now and @RustedBones actually made use of the AWS reactive streams APIs in https://github.com/akka/alpakka/pull/1725 to implement the sources.
That PR did not include the use of the publisher for `BatchGetItem`, though.

For write operations the AWS SDK 2 does not seem to support Reactive Streams natively. But they are clear about the original idea of this issue:

> If you're not using an AWS SDK, you should retry original requests that receive server errors (5xx). However, client errors (4xx, other than a ThrottlingException or a ProvisionedThroughputExceededException) indicate that you need to revise the request itself to correct the problem before trying again. 

See [DynamoDB docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#Programming.Errors.RetryAndBackoff)

**Comment by ennru** [comment]
My understanding is that the AWS SDK 2 -- which Alpakka starts using with the upcoming 2.0 release -- has built-in retrying logic which we should rely on.
I create https://github.com/akka/alpakka/pull/1986 to document it in Alpakka.

**Comment by ennru** [comment]
So with #1986, we will do not anything special on those exceptions in Alpakka, please re-open or create a new issue if we can do better than what we have with AWS SDK 2's support for back-off.
