### ISSUE TITLE
Add automatic module names (for JDK9) to all Alpakka modules

### ISSUE THREAD

**Issue by ktoso** [akka/alpakka#769]
In order to be usable as JDK9 modules, Alpakka modules should add module names.
We have a mini helper for it in akka: https://github.com/akka/akka/blob/master/build.sbt#L56 

Impl: https://github.com/akka/akka/blob/master/project/AutomaticModuleName.scala 

Though be aware that it seems to break when combined with the osgi plugin?
https://github.com/akka/akka/issues/24520

Once https://github.com/akka/akka/issues/24520 is fixed, apply the module names to alpakka

**Comment by ennru** [comment]
Would we expect the Alpakka modules to live in the "akka" namespace? Or should they be placed in "alpakka"?

**Comment by ktoso** [comment]
Akka is fine I think; `akka.alpakka.s3` etc

**Comment by raboof** [comment]
In packages we even do `akka.stream.alpakka`, might make sense to follow that?

**Comment by ktoso** [comment]
Module names don't have to be the same as package names, though this could work if people like it I guess

**Comment by ktoso** [comment]
No stream in the name leaves a bit space for future expansion if it may ever happen

**Comment by raboof** [comment]
Or healthy scoping :nerd_face: - either is fine by me :+1:!
