### ISSUE TITLE
AWS Kinesis and DynamoDB

### ISSUE THREAD

**Issue by areyouspiffy** [akka/alpakka#77]
A little over a month ago I started working on akka-http based dynamodb and kinesis clients [here](https://github.com/areyouspiffy/reactive-aws). Would this be helpful for me to port over here?

**Comment by patriknw** [comment]
That sounds very interesting, thanks

**Comment by markusjura** [comment]
I was not aware that such libraries exist when starting a Dynamo connector for Alpakka: https://github.com/markusjura/reactive-dynamo.

The current version is not yet in shape to use widely. The library has implemented currently only the activity stream API: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html

@areyouspiffy Does it makes sense to merge our efforts? I am happy to add you as a contributor to my repo. I am also happy to contribute to your repo. Whatever you think is best.

**Comment by areyouspiffy** [comment]
Hey @markusjura, the primary difference I can see between our two projects is that yours uses [AmazonDynamoDBStreamsClient](https://github.com/markusjura/reactive-dynamo/blob/master/reactive-dynamo/src/main/scala/reactive/dynamo/DynamoDbSource.scala#L34) (I think) and mine uses [akka-http](https://github.com/areyouspiffy/reactive-aws/blob/master/core/src/main/scala/reactive/aws/AwsClient.scala). The reason I went with akka-http is because I saw complaints about the number of threads used by the aws sdk, [like this one here](https://github.com/akka/akka-persistence-dynamodb/issues/3). Having said that I think both approaches are totally valid and have their own pros and cons. If you're okay with using the akka-http approach then I can add you (and anyone else) as a contributor and I would love to have your help! I also understand if you prefer to stick to your own approach.
