### ISSUE TITLE
Elasticsearch: no way to query all the indexes at once

### ISSUE THREAD

**Issue by migesok** [akka/alpakka#774]
It seems there is no way to query not a particular ES index but all the indexes at once.
In the ES client one can construct `org.elasticsearch.action.search.SearchRequest` with no indexes specified and it would mean that all indexes are going to searched.
But in `ElasticsearchSource` index name is a required attribute.

**Comment by mbknor** [comment]
You can probably  use "*" as indexName. I'm using it to querying multiple indexes like this:  "my-index-2018-*"

**Comment by florian-f** [comment]
Maybe making "*" the default value for the index parameter would make sense?

**Comment by mbknor** [comment]
I do not think it should have a default value.

Searching all indexes is not a common use-case, I think..

**Comment by mbknor** [comment]
But I'm thinking about creating a PR making both indexName and typeName optional
