### ISSUE TITLE
Allow SQS sources to terminate 

### ISSUE THREAD

**Issue by Norwae** [akka/alpakka#776]
I do a lot of batch processing via SQS. A common pattern is to accumulate a queue for several hours, then process it until it is fully drained. 

Unfortunately, out of the box, this requires mucking around with timeouts, which fail the flow and potentially cause skipped elements. A much cleaner approach would be to provide a setting that allows terminating the stage when an empty receive has occurred.  The setting can default to "false", maintaining current semantics unless explicitly enabled when the graph is created. 

When an empty message is received, the source can drain any remaining buffer or outstanding requests, and complete once no request still open and the buffer is empty.

**Comment by ennru** [comment]
Implemented with #778
