### ISSUE TITLE
Alpakka 0.17 artifacts are not in Maven Central

### ISSUE THREAD

**Issue by ngbinh** [akka/alpakka#794]
https://mvnrepository.com/artifact/com.lightbend.akka/akka-stream-alpakka-s3 shows 0.16 as latest

**Comment by ktoso** [comment]
The release was not successful yesterday @ennru : 

![nexus_repository_manager](https://user-images.githubusercontent.com/120979/36407060-c8d11c6a-163e-11e8-98f9-dbd96931e638.png)

**Comment by ngbinh** [comment]
fixed. Thanks

**Comment by ktoso** [comment]
Seems it was on its way all along to begin with ;)
Patience pays off
