### ISSUE TITLE
Spelling/grammar issues in Kinesis connector

### ISSUE THREAD

**Issue by gregbeech** [akka/alpakka#816]
Doesn't affect functionality, but it's nice to have the right spelling and grammar in interfaces.

- `KinesisFlow` and `KinesisSink` have a method `byParititonAndBytes`; this should be `Partition` (i.e. the `i` is in the wrong place).

- `KinesisFlowSettings` uses `Lineal` ("consisting of lines") but `Linear` ("progressing from one stage to another in a series of steps") is more appropriate.

**Comment by ktoso** [comment]
Could you submit a PR fixing those? Thanks in advance!

https://github.com/akka/alpakka/blob/master/CONTRIBUTING.md

**Comment by gregbeech** [comment]
Yep, happy to do so. Just wanted to make an issue to track it.

**Comment by ktoso** [comment]
Thanks!
