### ISSUE TITLE
Add link to pulsar

### ISSUE THREAD

**Issue by sksamuel** [akka/alpakka#823]
My project [pulsar4s](https://github.com/sksamuel/pulsar4s) offers and akka streams source and sink.
Please consider adding a link on your list of external components https://doc.akka.io/docs/alpakka/ffa20494/external-connectors.html

**Comment by ktoso** [comment]
Oh, very cool integration. Feel free to submit a PR adding it to the list :)
Could you mention in the main readme the akka streams integration? Seems it talks mostly about RS publishers, saying the wrappers are provided would be nice :)

**Comment by sksamuel** [comment]
I have updated the documentation to provide full examples of akka streams sources and sinks.
https://github.com/sksamuel/pulsar4s#akka-streams

I have also opened a PR here: https://github.com/akka/alpakka/pull/824
