### ISSUE TITLE
Don't need API Key for all endpoints if Service account is used

### ISSUE THREAD

**Issue by vertexclique** [akka/alpakka#825]
Alpakka Google Cloud PubSub doesn't need api_key. `GOOGLE_APPLICATION_CREDENTIALS` is enough for accessing to PubSub.

**Comment by jacobg** [comment]
I agree. It would be nice to have a parameterless PubSubConfig constructor that checks for a `GOOGLE_APPLICATION_CREDENTIALS` environment variable pointing to a private key json file. That is the typical pattern for Google Cloud client libraries.

**Comment by 2m** [comment]
We are approaching Alpakka 2.0 which allows API breaking changes. Now would be a perfect time to work on this as this change would require breaking the API.

**Comment by Habitats** [comment]
Any update on this?

**Comment by pbonito** [comment]
Any update on this? We can't  write private keys directly in application.conf  so I'm not able to understand how can is use aplakka library. In my case I'm trying to use the storage package.

**Comment by ennru** [comment]
Please suggest the necessary changes in a pull request, I'm not aware of anybody working on this.

**Comment by armanbilge** [comment]
This is being fixed in #2613.

**Comment by seglo** [comment]
Fixed in #2613
