### ISSUE TITLE
SQS refactor

### ISSUE THREAD

**Issue by aserrallerios** [akka/alpakka#829]
Honestly, the SQS module is a bit overloaded, could use better naming conventions and have a more consistent design.

Also, it'd be interesting to study how to use `AmazonSQSBufferedAsyncClient` properly in alpakka.

**Comment by ennru** [comment]
Yes, I'm looking into the SQS connector (see #922) as we have test instabilities and I agree we can improve the API. I try to improve the Java API experience, but I will try to change it in a backwards compatible way for now.

**Comment by ennru** [comment]
Now that the Alpakka 1.0 changes are merged, do you think there are more changes we should consider?

**Comment by aserrallerios** [comment]
Still not sure about the `AmazonSQSBufferedAsyncClient`. It could make part of the alpakka features redundant. But, it's kinda out of scope, so this issue could be closed.

**Comment by ennru** [comment]
I created issue #1238 to discuss AmazonSQSBufferedAsyncClient further.
Closing this.
