### ISSUE TITLE
S3 client as akka extension.

### ISSUE THREAD

**Issue by agolubev** [akka/alpakka#84]
Perhaps more like discussion point.

**Comment by johanandren** [comment]
Wouldn't that limit it to accessing one s3 account per actor system? What about streaming things between different accounts?

**Comment by agolubev** [comment]
> Wouldn't that limit it to accessing one s3 account per actor system? What about streaming things between different accounts?

It's possible (maybe need to create a ticket for adding such example in doc). API will be changed anyway.

**Comment by agolubev** [comment]
@johanandren, let me know if it makes sense. 
And streaming things between accounts is one of use cases here. (will add tests for this case)

**Comment by francisdb** [comment]
What exactly would an 'akka extension' bring compared to what is currently available?
Isn't it already possible to have multiple clients in one jvm?

**Comment by agolubev** [comment]
@francisdb  it's about having configuration along with akka configuration. Extensions fill natively within akka ecosystem (clustering and typed actors are also extensions).  
Right now s3 has an implementation for using in streams but not pretty match in actors - that's the reason for adding an extension support. 
Also, currently it can be loaded only as a single instance from a conf file.

**Comment by ennru** [comment]
The handling of S3 configuration will be improved as of release 0.16. Now it is easier to set up several S3 connectors within one actor system.
Alpakka connectors should not be seen as part of akka configuration as we discuss in #606 .
