### ISSUE TITLE
Support Akka Http 10.1.x

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#847]
Quite a few connectors rely on Akka Http. Alpakka should work with Akka Http 10.0.11 and 10.1.x.

Compiling against Akka Http 10.1.0 is hindered by the SSE and S3 modules which need to convert between `scaladsl.Uri` and `javadsl.Uri` (S3) and the other way round (SSE).

**Comment by francisdb** [comment]
how will you make this compatible with both 10.0.11 and 10.1.x?

**Comment by ennru** [comment]
The only way compatible with both versions would go via the String representation and reparsing.

**Comment by ktoso** [comment]
We can back port the new way to 10.0

**Comment by ktoso** [comment]
Please remind me so I don’t forget once I’m back @raboof @patriknw (this is for the 10.0.12 release)

**Comment by ennru** [comment]
0.18 will be compatible with both Akka Http 10.1.1 and 10.0.13.
When 10.1.1 is published, I'll add an extra build configuration for it.

**Comment by ennru** [comment]
We'll default to Akka Http 10.1.3 from Alpakka 0.20, but intend to keep compatible with 10.0.13+ for a while.
