### ISSUE TITLE
S3 Connector - ContentType header not present in ObjectMetadata

### ISSUE THREAD

**Issue by chetanmeh** [akka/alpakka#853]
S3 returns the `Content-Type` header as part of object download response and its expected that this should be accessible from the `ObjectMetadata#contentType`. However as akka-http [drops this header][1] it is not included in the headers passed to `ObjectMetadata`.

Probably `S3Stream#download` should extract them from the `ResponseEntity` and add them to the headers passed to `ObjectMetadata`.

[1]: https://doc.akka.io/docs/akka/2.4.11/scala/http/common/http-model.html#HTTP_Headers

**Comment by chetanmeh** [comment]
Would try create a testcase and fix PR for this issue

**Comment by ennru** [comment]
Fixed with #858
