### ISSUE TITLE
Named temporary queues (with exchange binding)

### ISSUE THREAD

**Issue by Synesso** [akka/alpakka#869]
I'm unsure if this is not possible in the current version, or if it is a feature request.

I would like to create temporary queues with specified names or naming hints.

e.g. the following creates a temporary queue with a random name (starting with `aqm.gen-`)

```
val queueSettings = TemporaryQueueSourceSettings(
  AmqpUriConnectionProvider(amqpUri),
  exchange
)
val source = AmqpSource.atMostOnceSource(queueSettings, bufferSize = 10)
```

whereas this will created a named, _permanent_ queue (i.e. it does not disappear after the client disconnects).

```
val queueName = s"myapp-${env}-${Random.alphanumeric.take(10).mkString}"
val queueSettings = TemporaryQueueSourceSettings(
  AmqpUriConnectionProvider(amqpUri),
  exchange,
  declarations = Seq(QueueDeclaration(queueName, autoDelete = true))
)
val source = AmqpSource.atMostOnceSource(queueSettings, bufferSize = 10)
```

Is it possible to created named temporary queues?

**Comment by juanjoDiaz** [comment]
It is a feature request. Since passing the name to a temporary queue is not supported at the moment. :)

**Comment by juanjoDiaz** [comment]
I've dug a bit more into the issue.
`TemporaryQueueSourceSettings` is a convenient way of getting a temporary unnamed queue that's declared implicitly.

You can declare a `QueueDeclaration("YOUR_NAME", false, true, true, null)` so it's not durable, exclusive and autodeletable (like temp queues) and use a normal `NamedQueueSourceSettings` for it.

Would this solve your issue? Or what would you expect?

**Comment by Synesso** [comment]
Thanks @juanjoDiaz. I tried this just now.

With `NamedQueueSourceSettings`, there is no exchange binding. So the queue is created with the name and deleted afterwards as expected, but never bound to the target exchange.

This is suggested by [AmqpSourceStage.scala#L136](https://github.com/akka/alpakka/blob/master/amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala#L136) being the only place where queue binding occurs in `AmqpSourceSettings`.

This is what I tested with:

```
      val exchange = s"estimation-$region-${env}_line"

      val queueName = s"myapp-$region-${env}_line-${Random.alphanumeric.take(10).mkString}"

      val queueSettings = NamedQueueSourceSettings(
        AmqpUriConnectionProvider(amqpUri),
        queueName,
        declarations = Seq(
          ExchangeDeclaration(exchange, "fanout"),
          QueueDeclaration(queueName, durable = false, exclusive=true, autoDelete = true)
        )
      )
```

**Comment by juanjoDiaz** [comment]
You are missing the binding.

```
val exchange = s"estimation-$region-${env}_line"
val queueName = s"myapp-$region-${env}_line-${Random.alphanumeric.take(10).mkString}"

val queueSettings = NamedQueueSourceSettings(
  AmqpUriConnectionProvider(amqpUri),
  queueName,
  declarations = Seq(
    ExchangeDeclaration(exchange, "fanout"),
    QueueDeclaration(queueName, durable = false, exclusive=true, autoDelete = true),
    BindingDeclaration(queueName, exchange).withRoutingKey("*")
  )
)
```

Temporary queues are automatically binded. Named queues are not.
The binding occurs at https://github.com/akka/alpakka/blob/03521d28b3c5f0221cba114bddb146bf6c152d1b/amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpConnector.scala#L51

**Comment by Synesso** [comment]
Sweet. This resolves the issue for me. Thank you very much.
