### ISSUE TITLE
FTP: SecureRandom hangs on docker

### ISSUE THREAD

**Issue by fmsbeekmans** [akka/alpakka#874]
In environments with low entropy such as docker the creation of an `SSHClient` in the `ftp` module can take very long. In situations where security is not important such as testing on a build server this can be problematic.

**Comment by johanandren** [comment]
I think it may be the case of /dev/random being used, and that blocking until there is enough entropy (For example https://stackoverflow.com/questions/26021181/not-enough-entropy-to-support-dev-random-in-docker-containers-running-in-boot2d) 

Did you try explicitly pointing it to /dev/urandom instead?

**Comment by johanandren** [comment]
Ups, pasted the wrong link: https://stackoverflow.com/questions/137212/how-to-solve-slow-java-securerandom

**Comment by fmsbeekmans** [comment]
It is indeed but it's an environment where we can't mount `/dev/urandom`. Our proposed solution was to use a different ssh config that uses a different random

**Comment by ennru** [comment]
With #875 in place, it is now possible to inject a custom SSH config.
