### ISSUE TITLE
rabbitmq (amqp) cached connection shutdown listeners, memory leak

### ISSUE THREAD

**Issue by drobert** [akka/alpakka#883]
While investigating some issues with heap size in an application I work on, I opened an hprof file in a memory analyzer tool which suggested a 'leak suspect' to be `akka.stream.alpakka.amqp.AmqpConnectorLogic$$anon$1` (screenshot attached). At the time of the analysis, there were 57,000 instances of this. Looking at the common paths, this appears to be distinct instances of the rabbitmq underlying `shutdownListeners` array.

I am working on distilling this down to a minimally-reproducible block of code, however I think the important aspect is that I'm using the `AmqpCachedConnectionProvider` (backed by `AmqpUriConnectionProvider` with `automaticRelease=true`).

(_Update_: it would be reproducible by re-establishing a new akka stream with a new sink, delivering 1+ messages, then closing the stream. Repeat this process with a cached connection provider and ultimately the heap should exhaust.)

As it stands, each graph started with a single connection will augment the shutdown listeners array by one, and since the connection remains open, shutdown listeners are accumulated on the heap for each created graph.

Note that there is currently no issue with *channel* shutdown listeners as channels are used within a single graph stage and never shared or reused.

![alpakka_amqp_heap](https://user-images.githubusercontent.com/455162/38508296-d553c356-3bec-11e8-9017-5c5b89421c38.png)

**Comment by drobert** [comment]
Despite the two PRs up right now, I think the bigger issue is the lack of test coverage for this use case. I'm going to try to take a pass at this later this evening (I'm in TZ `America/New_York`) but would gladly accept some help as this is my first time contributing to alpakka.

**Comment by drobert** [comment]
Took a pass at adding tests for this case in https://github.com/akka/alpakka/pull/887, but I'm having some issues. What I currently have is passing for me locally, but I left some questions in the PR. I'd appreciate some feedback/help on this as I'm still coming up to speed.

**Comment by ennru** [comment]
Fixed by #887
