### ISSUE TITLE
Is there an appetite for an alternate MQTT connector

### ISSUE THREAD

**Issue by huntc** [akka/alpakka#892]
I've just observed the MQTT component use 8 threads in my live production environment. I believe the number relates to Paho's blocking based approach. 8 threads equate to 2MiB of memory in stack space given a 256k stack size (the min). IMHO, 2MiB is excessive as no threads should have to be dedicated solely to MQTT i.e. MQTT I/O should be non-blocking and a consumer of the regular Akka dispatchers.

Would there be interest in a re-write of the MQTT connector, perhaps without the bells and whistles of Paho in terms of function? My intent would be to provide an MQTT connector based purely on Akka streams with no other dependencies. The new connector would satisfy the major use-cases of subscribing/posting messages securely. My approach would be to provide a minimal starting point on which others in the community could build on.

**Comment by ennru** [comment]
Yes, please give it a go to implement a non-blocking MQTT connector.

**Comment by schrepfler** [comment]
Is there any repo where this development might be happening?

**Comment by huntc** [comment]
Not to my knowledge. Things have been a bit hectic here.

**Comment by huntc** [comment]
@ennru I'm starting to think about this again, particularly in light of a problem I've noticed where [Paho is retaining many, many threads](https://github.com/eclipse/paho.mqtt.java/issues/402). This latter issue is causing us some pain in production.

My thinking is to compose existing stages. So, to subscribe to a topic, receive subscriptions and publish to that same topic, it might go something like this:

```scala
Source.single(Mqtt.Connect("someuser", "somepassword"))
  .via(Tcp().outgoingConnection("localhost", 1883))
  .flatMapConcat {
    case Mqtt.ConnectAck =>
      Source.single(Mqtt.Subscribe("sometopic"))
        .flatMapConcat {
          case Mqtt.SubscribeAck =>
            Source.single(Mqtt.Publish("sometopic", ByteString("hi")))
          case x => 
            x // Let through anything else including PubRec pass through
        }
    case x => 
      x // Let through anything else
  }
  .runForeach {
    case Mqtt.PubRec(topic, message) => println(s"Received: $message from $topic")
    case x                           => println(s"Received: $x")
  }
```

I realize that this operates at a lower level than at present, and perhaps higher level compositions should be declared. My thinking is to start with the lower-level components, composing as much out there as possible.

Thoughts?

**Comment by 2m** [comment]
Interesting.

In your example you have the same flow that handles messages meant for the server as well as ones coming from the server. Therefore you needed to add the `case x =>` passthroughs.

Another approach could be to use bi-directional flows, where one flow would be for messages coming from server, and another for messages directed to the server. However this separation would mean a bit more work when it comes to sending a message to the server when a particular message arrives from the server, which is way easier in your example.

**Comment by huntc** [comment]
Thanks for the thoughts @2m. I've never used `BidiFlow`, so I'll dwell on this. Meanwhile, if you've got time to re-form my example with a `BidiFlow` then that'd be wonderful! :-)

**Comment by 2m** [comment]
Here is something I came up with: https://github.com/2m/akka-stream-sandbox/blob/d325e6b99a7c9ad9fc134d7cd4c03f2efec4520b/src/main/scala/MqttBidi.scala#L33-L50 Note that while it compiles, it still has some bits missing.

It is tricky to model protocols using Akka Streams. Akka Typed actors are way more suited for that. I think the most desired solution would be to mix and match the two.

**Comment by huntc** [comment]
Thanks @2m - I was also subsequently thinking about an actor to manage the state of the connection. While I like your example, I think it takes a few looks before one can comprehend what's going on. So, perhaps something like this then instead:

```scala
Source(Seq(Mqtt.Connect("someuser", "somepassword")), Mqtt.Subscribe("sometopic"))
  .via(Mqtt.sessionFlow(Tcp().outgoingConnection("localhost", 1883)))
  .collect { case publishReceived: Mqtt.PubRec => publishReceived }
  .runForeach {
    case Mqtt.PubRec(topic, message) => println(s"Received: $message from $topic")
  }
```

In this case, `sessionFlow` could be backed by an actor, although that's an implementation concern. But most likely an actor. I envisage the `sessionFlow` would allow everything to pass through, but what gets passed through affects its state machine. This way, other stages could process various low-level acks etc. if required.

WDYT?

**Comment by 2m** [comment]
Yea, looks good! Note that in your example `Mqtt.sessionFlow` is also a BidiFlow shape just incognito. :)

In your example `Mqtt.sessionFlow(Tcp().outgoingConnection("localhost", 1883))` is of type `Flow[Mqtt, Mqtt]`.

Now imagine `Mqtt.sessionBidiFlow()` is `BidiFlow[Mqtt, ByteString, ByteString, Mqtt]`. Then `Mqtt.sessionBidiFlow().join(Tcp().outgoingConnection("localhost", 1883))` is `Flow[Mqtt, Mqtt]` same as in your example, just IMHO more decoupled.

BTW, you can replace

```scala
  .collect { case publishReceived: Mqtt.PubRec => publishReceived }
```

with

```scala
  .collectType[Mqtt.PubRec]
```

And for implementing a custom stages my choice in order of decreasing preference is typed actors, graph stages, classic actors.

**Comment by huntc** [comment]
Awesome - thanks @2m - particularly for the enlightenment of the `BidiFlow`. I think that this discussion gives me a start point.
