### ISSUE TITLE
AWS S3: prepare docker image to run Minio tests

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#938]
The AWS S3 connector code even contains integration tests that can run against Minio.
We could prepare a docker image and run those tests in the CI cycle, as well.
Instructions to run it are found in the `MinioS3IntegrationSpec` comment.

**Comment by ennru** [comment]
@sfali Would be great if you could PR the Docker config you used with #951 and propose a way to add and remove buckets for testing.

**Comment by sfali** [comment]
Sure, I will.

**Comment by 2m** [comment]
Fixed in #1395
