### ISSUE TITLE
Docs use version 0.18+58-16127f1a instead of 0.19 and point to an unpublished API doc

### ISSUE THREAD

**Issue by giftig** [akka/alpakka#949]
Many links in the docs (eg. https://developer.lightbend.com/docs/alpakka/latest/amqp.html) which refer to the API documentation point to nginx 404 pages. It looks like it's because they're pointing to a transient version, 0.18+58-16127f1a, instead of 0.19, and replacing that version with 0.19 or current works in most cases (though some are still broken, possibly because they were moved in 0.19, eg. AmqpLocalConnectionProvider)

**Comment by 2m** [comment]
The link that you posted is to the `latest` version of Alpakka which is built from master. To reach the documentation of the recently released `0.19` version use the `current` docs: https://developer.lightbend.com/docs/alpakka/current/amqp.html

**Comment by giftig** [comment]
Good to know, but as "latest" is the first relevant hit when you google `alpakka ampq docs` and "current" doesn't appear in the results, it's quite confusing that all of its links are dead because the associated API docs haven't been published.

**Comment by 2m** [comment]
I was wondering where these links to the `latest` are coming from. Thanks for letting us know that the source is Google Search. We will need to turn some knobs to demote `latest` and promote `current`.

**Comment by 2m** [comment]
As "latest" is semantically very close to "current" it is not always obvious that one is browsing documentation built from master when on the "latest" page.

Therefore we decided to change the URL of docs from current master. From now snapshots from master are hosted under "snapshot" and "latest" now redirects to "current".
