### ISSUE TITLE
API doc: incorrect links to other libraries' API docs

### ISSUE THREAD

**Issue by giftig** [akka/alpakka#950]
Links targeting classes in other API docs seem to only point to the root of those docs instead. For example on this page:

https://developer.lightbend.com/docs/api/alpakka/0.19/akka/stream/alpakka/amqp/AmqpLocalConnectionProvider$.html

The fragments in the URLs make it obvious it's attempting to point to a specific class, but the `Unit` link, just points to the root of the scala library doc, and `Connection` points to the root of the `com.rabbitmq.client` javadoc. It looks like some configuration issue in how those links are being generated or maybe a scaladoc version incompatibility?

**Comment by ennru** [comment]
We've improved Scaladoc generation quite a bit, and this should work correctly now.
