### ISSUE TITLE
Use java.time.Duration for Java APIs

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#979]
New conversion support in java8-compat.

**Comment by adamtrousdale** [comment]
@ennru I couldn't find the use of scala.concurrent.Duration in any of the Java APIs, only in the tests. Is this issue to change the tests to use java.time.Duration or have I misunderstood the purpose of this issue? :)

**Comment by ennru** [comment]
I think right now the Java APIs most often use `(Long, TimeUnit)` as parameters and construct Scala Durations with those. We'd like to move that to use `java.time.Duration` wherever Scala Duration is accepted in the Scala APIs.
To start with we'll mark the current methods as deprecated.

**Comment by adamtrousdale** [comment]
Okay, I see now. I might start taking a look and see if I can identify the areas it needs changing. I'm keen to help out with some of these lower level tasks while I'm getting to grips more with the library!

**Comment by ennru** [comment]
My search in the code did not find any settings not using `java.util.Duration`.
Closing.
