### ISSUE TITLE
S3: Multipart uploading huge ByteString causes BufferOverflowException

### ISSUE THREAD

**Issue by jypma** [akka/alpakka#980]
When doing multipart uploads to S3, alpakka tries to chop up the incoming stream into chunks of configurable size (but at least 5MB, required by amazon's API specs). To this end, `SplitAfterSize` starts a new chunk after that size.

However, if the incoming `ByteString` instances are very big (say, >10MB each), `SplitAfterSize` doesn't split them up before creating chunks. This overflows the buffer instances where the chunks are stored (`MemoryBuffer` and `DiskBuffer`), which have internal safety limits of `chunkSize * 2`, after which they throw `BufferOverflowException`.

Instead, `SplitAfterSize` should actively chop up incoming huge `ByteString` objects.

**Comment by kevinmehall** [comment]
I'm seeing this as well. The actual exception in 0.20 seems to be an `IllegalStateException`, which I'll include to make this issue easier to find with Google:
```
java.lang.IllegalStateException: Buffer size of 10485760 bytes exceeded.
        at akka.stream.alpakka.s3.impl.MemoryBuffer$$anon$1.onPush(MemoryBuffer.scala:33)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
        ...
```

**Comment by jguido** [comment]
Is there any updates for this issue?

**Comment by omnipresent07** [comment]
We're getting this issue as well. Has there been a resolution to this?
