### ISSUE TITLE
Commitable source is not closing the connection in case of downstream finished

### ISSUE THREAD

**Issue by griffhun** [akka/alpakka#988]
Commitable source is not closing the connection in case of downstream finished. This cause trouble because with rabbitmq there is no timeout for acknowledging messages only connection closing can enforce the resend of unacknowledged messages. When the downstream finished (for example with error) but the program is not terminated then the connection will stay alive and the messages infly won't be redelivered.

More information about the nature of the problem:
https://stackoverflow.com/questions/30546977/is-there-a-timeout-for-acking-rabbitmq-messages

**Comment by juanjoDiaz** [comment]
Currently, the RabbitMQ will stay open for as long as the connection to RabbitMQ is open and there are unacked messages.

It would make sense to have a configurable timeout though...

**Comment by griffhun** [comment]
Hi @juanjoDiaz, 
I'm wondering on the reason. Because as far as I know if the downstream is finished then there won't be any stage which will ack the message.

**Comment by juanjoDiaz** [comment]
Doing the acking-nacking as part of the stream and have the sink completing first would be ideal.

However, that's making a pretty wild assumption... 
What about side effects?
What if you sink to a list and then ack the elements in the sink?
What if you have a `take(10)` flow followed by a slow flow and then a sink that ack back to rabbit? The take flow will complete much before the last element is acked.

There are many cases where downstream will close before the last message is acked.

**Comment by griffhun** [comment]
@juanjoDiaz Thanks for the clarification.

**Comment by juanjoDiaz** [comment]
I think that this is already solved. Can someone with enough powers close this issue? @ennru ?
