### ISSUE TITLE
Elasticsearch connectors

### ISSUE THREAD

**Issue by larousso** [akka/alpakka#99]
It could be interesting to have source and flow for the corresponding scroll and bulk in elasticsearch.

**Comment by hochgi** [comment]
@larousso we use this API:
https://github.com/akka/akka-stream-contrib/issues/32
Providing a specific ES API from `unfoldFlow` API is trivial.
Hope this helps :-)

**Comment by takezoe** [comment]
I'm working on this topic here:
https://github.com/takezoe/alpakka/tree/elasticsearch/elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch

**Comment by hochgi** [comment]
@takezoe are you aware of: https://github.com/yannick-cw/elastic-indexer4s ?
Also, it looks like you're using a blocking http client against ES. Maybe you can use https://github.com/sksamuel/elastic4s or use akka-http connection flows as a more natural http client to work with streams.

**Comment by takezoe** [comment]
@hochgi Yes! I know that. elastic4s is a really cool library to use Elasticsearch in Scala, but I feel it's overkill to implement Source and Sink of Akka Streams.

In addition, HTTP support in elastic4s is still experimental and its reactive streams support works with the transport client only for now.

**Comment by larousso** [comment]
Hi, there is a performAsync request on the elastic rest client. you need to register a ResponseListener so it's easy to transform this into a scala future. 
Hope that help!

**Comment by hochgi** [comment]
@takezoe you can use `unfoldFlow` API to unfold an akka-http connection flow :)
