### ISSUE TITLE
akka http to akka amqp

### ISSUE THREAD

**Issue by Gittekken** [akka/alpakka#992]
Hi,
I am new to the whole world of akka and scala. My setup is using Rabbitmq and akka. I am currently using akka http, alpakka amqp, and akka streams. I have managed to get akka http and amqp running separately but I want to combine the two. I am completely stuck. I have akka http obtaining all the name of the queues in my rabbitmq api json and then I want alpakka amqp to connect to the queue names obtained.

**1.**
First, I just want to know how to go about connecting to one queue from the data of akka http.
I tried 

 def connect (queue: String) = {
    AmqpSource.atMostOnceSource(NamedQueueSourceSettings(amqpUri, queue),10)
  }

val httptoamqp = obtainallqueuenames .map(_.apply(1).toString()).map(_ => connect(_)) 

I also did 
  obtainallqueuenames.map(_.map( NamedQueueSourceSettings(amqpUri, _))).map(_.map(AmqpSource.atMostOnceSource(_, bufferSize = 10))).map(_.apply(1))

httptoamqp ~> sink

I just want to make a connection to rabbitmq. I'm not sure how to go about doing this. 

**2.**

I would like to know how to connect to multiple queues?

Thank you,
Ken

**Comment by 2m** [comment]
Hi @Gittekken,

I think it is great that you have chosen Akka Http and Alpakka AMQP connector for your task. Those two work really nice together. From the code that you posted I see that you do not run the source that is created in the `connect` method.

I would suggest to dedicate a little bit of time and read Akka Streams quickstart for an introduction to Akka Streams: https://doc.akka.io/docs/akka/current/stream/stream-quickstart.html This will help you to get familiar with concepts used in Akka Http and Alpakka as both of them use Akka Streams APIs extensively.

I will close this ticket, as we use this issue tracker for development of Alpakka.  Feel free to post more questions in the discussion forums: https://discuss.lightbend.com/c/akka/streams-and-alpakka
